### ISSUE TITLE
Delete pkg-config

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage#1018]
Currently, `mirage` tool calls `pkg-config` to get some information about how to link a Solo5 _unikernel_. _dunification_ of MirageOS highlighted that `pkg-config` is, may be, not the right direction to do that when it chooses to use an other way (provide some files which contains flags - eg. mirage/ocaml-freestanding#66).

The question is not so easy where it's not clear what we really need (when we link an _unikernel_) and it can have a non-obvious impact into the MirageOS eco-system. At least, implications are not (yet!) fully knowable at this stage.

To re-contextualize:
The _dunification_ of MirageOS requires some information of:
- how to compile C stubs and be usable into an _unikernel_ (`cflags.sexp`)
- how to link a Solo5 unikernel (`ldflags`)
- with which libraries we need to link (`libs.sexp`)
- who will link the _unikernel_ (`ld`)

**NOTE**: all of these requirements are not fundamentally true. The _dunification_ is not yet done! But let's start with that.

However, `pkg-config` can provide this information. @hannesm denotes that with mirage/ocaml-freestanding#66, we will have 2 ways to get these information and we should delete one of them.

> In a Mirage3 world (ocamlbuild), pkg-config and .pc files are used to pass around cflags/ldflags/.. . Now, in a Mirage4 world (dune), the same information is embedded in separate files, and pkg-config is still around, called at installation time of solo5 + ocaml-freestanding. Is this correct?

My concerns is that `pkg-config` is more expressive that simple files when the `Requires` field appear into a `*.pc` file - so expansion of these information can be more complex. However, according mirage/ocaml-freestanding#66, all information come from a call of `pkg-config` (with a post-process with `sed`).

In other side, `mirage` already integrates a call to `pkg-config`. So, from what I know about the _dunification_ of MirageOS and what we have, we can move forward without mirage/ocaml-freestanding#66.

@mato, then, described where `pkg-config` is really needed:

> As far as I can tell, the dependencies on pkg-config in the whole Mirage(/Solo5) stack are:
> 
> - `solo5-bindings-*`
>     - `ocaml-freestanding`
>         - `mirage-solo5`
>             - (indirectly) the `mirage` tool and generated _unikernel_ build system
>         - `gmp-freestanding`
>         - `zarith-freestanding`
>         - (unclear, indirect?) `nocrypto` / `mirage-entropy`

Then, a consensus from these people is clear:
> @mato: If we can replace `pkg-config` with something different, then we should try and do that.

> @hannesm: Will the result be .pc file free, and not depending on pkg-config (highly appreciated since we already discovered some divergence between Ubuntu, other Linux, and OpenBSD (where we install a custom symbolic link IIRC))?

In other word, should we delete `pkg-config`?

As I said, _dunification_ is not done and still continues to use `pkg-config` in some ways according the current status of the MirageOS ecosystem. This issue exists to keep in our mind that it should be very interesting to delete `pkg-config` from the MirageOS eco-system and may be use something more powerless but more predictable/reproducible.

But to avoid any overlap with the _dunification_, this issue should be fixed __after__ the _dunification_ and see what the _dune_ ecosystem can offer and what we can do then.

**Comment by mato** [comment]
> My concerns is that pkg-config is more expressive that simple files when the Requires field appear into a *.pc file - so expansion of these information can be more complex.

That shouldn't matter. We control the whole stack, and there are other ways to structure the passing-around of this information that don't necessarily depend on `Requires` and composing information from multiple `.pc` files.

> provide some files which contains flags - eg. mirage/ocaml-freestanding#66

Assuming "some files that contain flags" are indeed the right thing to do. In the referenced PR, I asked:

**Q**: What are the _available mechanisms_ for a `dune`-based project/package _X_ to query dependency _Y_ for some key/value based metadata published by _Y_, which is then "expanded" by `dune` during build of package _X_?

To elaborate:

- Are we limited to expansion of the content of "some file published by _X_"?
- How does the location of "some file" get determined? 
- What formats of "some file" can `dune` parse?
- Can this mechanism also work in some sensible way without depending on `dune`? For example, "cross"-builds of C packages such as `gmp-freestanding`?

Without answering the above and understanding what's available I can't offer any potential solutions / replacements for pkg-config.

@mirage/core ? Feel free to rope in some dune folks here also.

**Comment by mato** [comment]
> But to avoid any overlap with the dunification, this issue should be fixed after the dunification and see what the dune ecosystem can offer and what we can do then.

So, you'd like mirage/ocaml-freestanding#66 merged regardless? My concern is that adds a bunch of build-time APIs (`flags` files), and if those are not the right/complete solution to get to a `pkg-config`-free world then we will just be creating more work for ourselves later.

We should be able to get this right once, in a way that can be used by both the _current_ non-dunified (`ocamlbuild`-based) Mirage and the _future_ dunified one.

**Comment by hannesm** [comment]
...a year later, I think this is superseeded by #1195, right!? TL;DR: ocaml-freestanding will provide an ocaml cross compiler, embedding the CFLAGS -- and solo5*, openlibm will use pkg-config files to be used by ocaml-freestanding. But all the OCaml code will no longer require pkg-config. Please let us discuss the future state in #1195.
