### ISSUE TITLE
netif implementations catch exceptions

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1036]
in MirageOS 3.0 we switched to use the `result` type for errors. But still, the `listen` implementations in mirage-net implementations use a `Lwt.catch` around the user-provided callback function. This catch is triggered i.e. by ocaml-cohttp which IO.write may lead to an exception ("trying to write to closed channel" / ...). I propose to remove the Lwt.catch with the next major Mirage release. This means we need to fix all libraries and applications (from what I see in my unikernel fleet it is really only cohttp).

The main downside of catching exceptions is that the netif implementations catch all of them, which hides Out of memory, which may lead to e.g. empty replies (pretty inconvenient). I can think (abstractly) of HTTP client requests which require the server to allocate a lot of memory (such that a unikernel gets out of memory -- I have not looked into HTTP code, but there may even be a single request leading to huge allocation, it is unfortunate if this happens that a single request can lead to a crash), thus we should memory-limit each HTTP request (so a HTTP request A does not starve the memory requirements of B; by A exhausting their memory, B could still operate within the memory bound). But I've no clue what a good size for such a limit should be. 5MB? what if you would like to upload/download bigger things?

As we do it now, i.e. relying on it being captured in netif.listen, is for sure not the right thing to do. The following PRs exclude as a first step the `Out_of_memory` from the catches:
- [x] https://github.com/mirage/mirage-net-solo5/pull/36
- [x] https://github.com/mirage/mirage-net-unix/pull/49
- [x] https://github.com/mirage/mirage-net-xen/pull/97
- [x] https://github.com/mirage/mirage-net-macosx/pull/38 https://github.com/mirage/mirage-net-macosx/pull/39

**Comment by hannesm** [comment]
while this issue didn't get any comment, it looks like various developers appreciate the do-not-catch out-of-memory condition. I'll move along and merge the remaining PRs tonight (unless someone beats me) and cut a release of the above mentioned packages.

This issue should be kept open to remind us that we should clean this a bit more for MirageOS 4.0. As outlined above, the mirage-net fix I have in mind is to get rid of the exception handler (and document this in the mirage-net interface accordingly). This implies that all users do not raise exceptions (atm at least cohttp does throw exceptions). It would be great if someone could look more deeply into cohttp and whether its interface can be modified to not raise exceptions under normal conditions.

**Comment by hannesm** [comment]
update: the out of memory exception is no longer caught in mirage-net-xen since 0.13.1, mirage-net-solo5 since 0.6.2, mirage-net-unix since 2.8.0, mirage-net-macosx since 1.9.0.

leaving this open to remind ourselves that listen should at some point not catch any exception at all anymore. I'm curious whether cohttp/conduit with 3.0 no longer raise exceptions!?

**Comment by samoht** [comment]
What's the status of this issue? Are we still catching exceptions in `listen`?

**Comment by hannesm** [comment]
Yes we still catch exceptions https://github.com/mirage/mirage-net-solo5/blob/40f3045d30f0b43875c0a106a7933ef67f9d5865/src/netif.ml#L124-L132 -- I'm still not sure what the cohttp story in respect to exceptions is. I'd be happy to remove the exception handler there.

**Comment by hannesm** [comment]
Not capturing exceptions:
- [ ] https://github.com/mirage/mirage-net-solo5/pull/41
- [ ] https://github.com/mirage/mirage-net-xen/pull/103
- [ ] https://github.com/mirage/mirage-net-unix/pull/50
- [ ] https://github.com/mirage/mirage-net-macosx/pull/40

**Comment by hannesm** [comment]
Interesting -- are you able to spot which part of the ecosystem transforms the (mirage-flow) `` `Closed `` write error into an exception?

**Comment by hannesm** [comment]
@dinosaure would you mind to test with conduit-mirage pinned to https://github.com/mirage/ocaml-conduit/pull/413 ?

In general, I think conduit could use some result types (e.g. the `connect` (client side) can never fail, just by raising an exception). The PR above uses a log message instead of an exception for the server loop (listen). But given the development of mimic, happy-eyeballs, ... -- I'm not sure whether there are many users of conduit(-client). In any case, I fear to break the API there and won't revise the code.

**Comment by dinosaure** [comment]
I can confirm that:
1) the unikernel does not fail anymore
2) the version of `conduit-mirage` fits with other dependencies

> I'm not sure whether there are many users of conduit(-client). In any case, I fear to break the API there and won't revise the code.

This part only concern us (MirageOS side) and `conduit-mirage` becomes unfortunately outdated for any of us. I planned to propose something else with `mimic`/`paf` which is more accurate with the ecosystem in many ways. So let's merge these PRs, cut releases and improve our ecosystem.

**Comment by hannesm** [comment]
I cut a conduit 5.1.0 release https://github.com/ocaml/opam-repository/pull/20831

**Comment by dinosaure** [comment]
I think this issue can be closed when all packages are released without the `Lwt.catch` :+1:. Thanks!
