### ISSUE TITLE
app_info should expose more informations

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#1155]
It would be nice if the `app_info` device would contain more information, especially the target.

**Comment by hannesm** [comment]
I'm not sure what else should be expose in `app_info`. In my attempts to capture sufficient package information to reproduce binaries, I ended up generating an opam switch export with all that information -- which could be embedded into a unikernel (but the current package information is not really worth it for much tbh -- it is imprecise).

The configured target is available as `Key_gen.target ()`.

**Comment by hannesm** [comment]
Thanks for the issue, if there's something specific to include in `app_info`, please don't hesitate to open a PR.
