### ISSUE TITLE
mirage.io cert expired

### ISSUE THREAD

**Issue by chamilad** [mirage/mirage#1156]
> Sorry if this is a wrong channel. 

I'm coming across this when visiting the site.

![image](https://user-images.githubusercontent.com/505989/82102812-d38d5480-9764-11ea-9e40-4ec9d81694d4.png)

**Comment by avsm** [comment]
Thanks for the issue; the good news is that the site is now hosted using a DNS unikernel integrated with LetsEncrypt, as well as a unikernel-based website. So this won't happen again :-)
