### ISSUE TITLE
[RFC] building the solo5/MirageOS's runtime

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#1186]
This issue discuss the best way to organise and build the C code which forms the (C) runtime of MirageOS on solo5.

## Current Status: MirageOS 3

The C runtime for solo5/MirageOS 3.* is composed of 3 components:

- solo5 bindings (`solo5_<bindings>.o`) which live in [solo5/solo5](https://github.com/solo5/solo5)
- freestanding archives (openlibm.a and nolibc.a) which live in [mirage/ocaml-freestanding](https://github.com/mirage/ocaml-freestanding)
- the OCaml runtime (libasmrun.a) itself which is built in [ocaml-freestanding](https://github.com/mirage/ocaml-freestanding/blob/master/Makefile#L20-L21) but pull its source code directly from the [OCaml source tree](https://github.com/ocaml/ocaml/tree/trunk/runtime).

The other device packages just contain pure OCaml code or externals calling the solo5 runtime (e.g. all the `mirage-<device>-solo5` package) or the freestanding runtime (e.g. the `mirage-<device>-freestanding`). 

There are some extra packages defining new C code (for instance `gmp`) which need to be cross-compiled - it's a special-case in mirage3 : they are usually called (`<pkg>-freestanding`) and they contain custom build rules.

### Current build strategy

- solo5 bindings are packaged with `pkg-config`, every bindings has a `solo5-bindings-<bindings>.pc` file installed.
- solo5 bindings have conflicting opam packages - there is only one "current" bindings in a given switch
- freestanding queries the current solo5 bindings (with `pkg-config`) and use the result to set its C flags ; this means that there is only *one* freestanding package, compiled for the current solo5 bindings ; e.g. freestanding archves cannot be co-built (and co-installed) for different solo5 bindings.
- the OCaml runtime is built using the same flags as the freestanding archives and also includes to the local freestandings headers ; so there only one runtime can be built (and installed) at the same time, using the "current" solo5 bindings.
- freestanding archives and the OCaml runtime are also installed using `pkg-config`. Which means that C bindings can query these (like `gmp-freestanding`) but which also mean that these are built only using the "current" solo5 bindings too.

## Next: MirageOS 4.0

The goal is to allow the compilation (and co-installation) of multiple MirageOS runtime in the same build environment. It is not clear to me that the current split is the right one for MirageOS 4.0, but I am not sure what is the best way forward.

One possible (but maybe extreme) way to do this -- that I've prototyped the new dune integration -- is to create a new [ocaml-solo5](https://github.com/samoht/ocaml-solo5) repository where all the C runtime is vendored in one place and where all the C archives are built and installed for all the existing bindings. I'm now trying to split that prototype to submit upstream patches such as https://github.com/Solo5/solo5/pull/472 but the resulting PR are a bit noisy (as `dune` requires packages to list all of their installed files) and might get difficult to maintain.

So I'm wondering if it makes sense to keep a very simple (probably Makefile-based) build system in solo5, ocaml-freestanding and ocaml-runtime and just use ocaml-solo5 to store the (more complex) build runes which allow all of these packages to be co-installable and x-compiled.

I'm open to better/simpler ideas so please add your feedback :-)

**Comment by samoht** [comment]
Here is a new tentative: vendoring solo5 and the OCaml runtime in ocaml-freestanding: https://github.com/mirage/ocaml-freestanding/pull/84

**Comment by hannesm** [comment]
I am not sure I understand why "all the C runtime is vendored in one place" is necessary / a good way to go. Is it about compilation flags (include directories etc.)? If so, there's still gmp and zarith (and possibly other packages with C stubs) that need these flags being passed (at the moment pkg-config is used, but some packages based on Lucas' patches copy some ldflags / cflags files around).

From a development perspective, e.g. ocaml-freestanding and solo5 have different release cycles -- while freestanding eventually needs updates when OCaml is released, solo5 only gets new releases when there are new features or bugfixes.

From a co-installability point of view, maybe I'm missing something, but I'd propose to investigate:
- solo5 consists of (a) header (independent of specific bindings/targets) and an archive (solo5-bindings-yyyy.a)
- ocaml-freestanding depends only on the solo5 headers, and produces (a) nolibc.a (b) ocaml runtime (c) libm.a

Now, if ocaml-freestanding can be compiled independent of the concrete binding/target, we can coinstall all bindings (which share the headers), and mirage can pick the right binding archive at link time.

**Comment by samoht** [comment]
I'm closing this since @TheLortex is now tracking this on #1195
