### ISSUE TITLE
`mirage configure` fails in a git repository with no `origin` remote

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#1188]
Creating an `origin` remote pointed somewhere stupid fixes this.

**Comment by yomimono** [comment]
It looks like this is caused by some autodetection magic in Functoria's opam-related logic ( https://github.com/mirage/mirage/blob/master/lib/functoria/opam.ml#L34 ) and that if I had passed a value noting that I don't want `mirage` to do anything clever with my git repos, I could also have gotten around this.

The existing error message, `fatal: No such remote 'origin'`, at least tells me what I can do (if I'm sufficiently traumatized to immediately blame git), but directions to configuring Mirage properly would be appreciated.

**Comment by hannesm** [comment]
Thanks for your report. I was able to reproduce this locally, and opened #1201 with a fix. While reproducing I encountered a similar issue: execute mirage configure in a git repository with no commits (i.e. have your unikernel, and do a `git init` later); here dune fails (reported at https://github.com/ocaml/dune/issues/3979).

**Comment by hannesm** [comment]
this is fixed in the branch `3` (soon in the master branch as well), and will be part of the next release (this week).
