### ISSUE TITLE
[RFC] IPv6 and dual stack integration into MirageOS

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1190]
In recent weeks, I worked with the help from @MagnusS on reviving @nojb IPv6 stack into MirageOS. The result is a dual stack test unikernel at https://test.robur.coop (https://198.167.222.217 / https://2c0f:f930:0:4::217).

# Approach

The main goal for me was "a dual stack server". The client side of IPv6 is only moderately tested.

A subgoal was as well to be able to leverage the decision whether IPv4 and/or IPv6 is used to boot time (i.e. not have to recompile only because I do want to use v6 only). The cost is that, even if not used, the legacy v4 code (and ARP) is part of the unikernel.

The main interface used by IP consumers is the [mirage-stack](https://mirage.github.io/mirage-stack/mirage-stack/Mirage_stack/index.html), which is now extended / duplicated from `V4` to a `V6` and `V4V6` interface. So a unikernel developer can decide to program a V4 only, V6 only, or dual stack unikernel. NB: we should default to the dual stack `V4V6` interface.

Existing ibraries using Mirage_stack.V4 (such as DNS/DNS_client/conduit...) should be changed to use Mirage_stack.V4V6 instead for compatibility reasons. I don't think it is worth to generalize these implementations over a Mirage_stack.S (which I'm not sure about what is needed in there).

# Code and API changes

There are some breaking API changes:
- mirage-protocols needs some enhancements (passing through a src address etc.) -> mirage-protocols 5.0.0 on the horizon
- the `connect` API (shared interface between mirage (which generates the code) and mirage-tcpip) changed quite a bit
- boot arguments for the socket and direct stack are unified: a single `--ipv4` and/or `--ipv6` per stack is allowed (the subnet mask / prefix length is ignored by the socket stack)
- each dual stack exposes as well a `--ipv4-only` and `--ipv6-only` boot parameter, enabling you to run in a v6 (v4)-only network ~~(that unikernel may still send out some v4 (v6) packets, but won't process any that are received -- we can improve on that front and remove all `connect` code if the ip protocol version is disabled for this stack)~~

The IPv6 initialization code (connect) does duplicate address detection (DAD) for all configured IP addresses (if it fails -- receiving a neighbour solicitation with the same IP address, it exits at startup). The IPv6 stack can be configured to process router advertisements or not (for server scenarios where you configure IP and gateway statically, there's no need to process router advertisements).

The socket stack has been improved to actually bind all server and client sockets to the IP address(es) provided -- earlier it always listened on all IP addresses. The default IPv4 address is still 10.0.0.2/24, but the default gateway (10.0.0.1) has been removed.

# PRs

This is not yet merged, but there are three outstanding PRs (review / comments appreciated):
- https://github.com/mirage/mirage/pull/1187
- https://github.com/mirage/mirage-tcpip/pull/433
- https://github.com/mirage/mirage-protocols/pull/27

On the unikernel developer site, please take a look into this commit to see changes for mirage-skeleton: https://github.com/hannesm/mirage-skeleton/commit/8616199da9fbeb4e860fd99ae8202ac8379cfff0 -- it's mostly in config.ml s/generic_stackv4/generic_stackv4v6/ a/stackv4/stackv4v6/ and in unikernel.ml s/Mirage_stack.V4/Mirage_stack.V4V6/ and s/TCPV4/TCP/ s/UDPV4/UDP/ s/Ipaddr.V4./Ipaddr./

# Conclusion

I'm interested in your feedback, and how to migrate our networking to dual stack. From my perspective, using `Ipaddr.t` in user (unikernel / library) code is most sensible. There are certainly some further changes needed (as mentioned above, the DNS library should be using a V4V6 stack, and the default resolver (hardcoded in mirage) should be an Ipaddr.t).

The work above also attempts to unify the semantics of the socket and direct stack a bit more (by `bind` to the given IP address, etc.), which imho improves the intuition you may have over a unikernel (and its build/debug/test/deploy cycle). Please let me know if this breaks your use cases.

//cc @mirage/core

**Comment by hannesm** [comment]
clients using Mirage_stack.V4, adapted to V4V6:
- https://github.com/mirage/ocaml-dns/pull/239 (should add some more test cases)
- https://github.com/hannesm/logs-syslog/pull/14

**Comment by avsm** [comment]
Overall the approach looks good to me.

I'm mainly most concerned with dual-stack selection when resolving names to addresses.  Some protocols (e.g. SMTP) favour IPv4 as IPv6 source addresses from relays are apparently marked as spam by gmail. For the other use cases, defaulting to IPv6 makes sense.

**Comment by hannesm** [comment]
@avsm cool. The configuration options _for an operator_ are to pass `--ipv4-only` / `--ipv6-only` to the unikernel

the above patch series does not implement any "favour v6 over v4", indeed `conduit` resolves only IPv4 at the moment.

I suspect we need, in the dual stack world, a way to investigate whether IPv6 (IPv4) connectivity is up and working, to select which protocol to use for client connections -- and as you outline, there may be library / application developer knowledge that a certain protocol should prefer one protocol version over the other.

**Comment by hannesm** [comment]
With this proposal, the following will be true:
- use STACKV4V6 everywhere (instead of STACKV4)
- if you're keen to retain the old behaviour (IPv4 only), you can pass `--ipv4-only=true` to the unikernel (at configuration or runtime), otherwise IPv6 support will be enabled (and a link-local address being automatically configured)
- the STACKV4 / STACKV6 are kept around for a migration period (but usage is deprecated)

**Comment by dinosaure** [comment]
It's good to me too, I don't have IPv6 on my side so I can not test my unikernels on this new stack but I trust on your experiments.
