### ISSUE TITLE
Mirage 3.x -- next release(s)

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1200]
Hi,

since there's some congestion on the release road, please let me elaborate my plans:
- conduit3 is getting revised (see https://github.com/mirage/ocaml-conduit/pull/338 and https://github.com/mirage/ocaml-conduit/issues/339), at the same time I tried in #1196 to have mirage / functoria do something sensible with the new conduit interface with not too much success. the current revised plan is to not include conduit3 support into mirage - instead revise our example unikernels to use conduit directly until we find a good solution. TL;DR: no conduit3 mirage3 release
- IPv6 (and other network stack changes): here I plan a release rather sooner than later which enables usage of mirage-protocols 5.0.0 (paving the road for dual stack support). the required mirage-stack and mirage-protocols are released, the tcpip PR is in progress. Since devices (conduit / DNS client / ...) are still using Mirage_stack.V4, there'll be a smooth transition: get a mirage out which next to `stackv4` provides `stack` and `stackv6` (but where e.g. conduit still requires a stackv4) -- this enables unikernels to use dual stack support (I'll go through #1187 and ensure that mirage-skeleton will work with the new mirage without any changes, while allowing the v6-only and dual stack support (before that goes through, I'll cut a tcpip release with https://github.com/mirage/mirage-tcpip/pull/433 included)). #1199 will be included in that release.
- I'd like to solve the issues reported recently (e.g. #1188 #1198) in both the mirage3 and mirage4 series.

For MirageOS 4.0, which is coming along smoothly, we're looking to first get `opam monorepo` out in the wild, and will then merge PRs and cut releases quickly. I'm happy to help out here with both testing and PRs, and have some further changes on my list - such as removing mirage-device and other deprecated packages (mirage-fs, mirage-types, mirage-types-lwt come to mind).

Tentative plan is: mirage 3.10 (IPv6 enabled) by the end of Nov 2020, mirage 4.0 hopefully before end of 2020. Please comment if you have other goals / open issues. I will as well PR the changes of 3.x release to the master branch.

**Comment by TheLortex** [comment]
With regards to mirage 4, everything is advancing at good pace. My main issue right now is the `ocaml-freestanding` setup as a cross-compiler: I have a working branch here https://github.com/TheLortex/ocaml-freestanding but it's quite hacky. I would like to clean it up and add tests before opening a PR. 

Basically the problem is that the OCaml compiler does not offer first-class cross-compilation support. I'm experimenting to find out how hard would it be to upstream the cross-compilations changes, but for now ocaml-freestanding scripts are a bit more complex than before.

**Comment by hannesm** [comment]
3.10 is in https://github.com/ocaml/opam-repository/pull/17749
