### ISSUE TITLE
Fix upstream support for Sys.os_type = xen

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#123]
See mirage/mirage-platform#78

We need to file an upstream bug report to not `assert false` if there's an unknown os_type, as this happens if we just link Filename in

**Comment by samoht** [comment]
We still have that issue.

**Comment by yomimono** [comment]
We still still have that issue.

**Comment by avsm** [comment]
Patch proposed upstream in ocaml/ocaml#674

**Comment by avsm** [comment]
Fixed upstream, will be in OCaml 4.04

**Comment by yomimono** [comment]
Thanks @avsm!

**Comment by hannesm** [comment]
work here is done, closing... once we drop <=4.03 we can actually use it ;)
