### ISSUE TITLE
warn the user if mirage is used with opam<2.1

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#1239]
As `make depends` will not work as expected if opam-2.0 is used, we should make sure we tell the user if the wrong version of opam is used.

**Comment by hannesm** [comment]
as done in the beta releases, the `available: opam-version >= "2.1.0"` in the opam files is imho a nice solution for this issue. can we push that constraint here into the opam files!?

**Comment by samoht** [comment]
Yes that's a good idea, let's do this for 4.0.
