### ISSUE TITLE
MirageOS 4 experiments

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1254]
Hello,

I just followed the instructions on https://next.mirage.io/docs/mirage-4 to try out this shiny new mirage 4. This worked really really nicely on a FreeBSD-13 system with OCaml 4.13.1 and opam 2.1.1 (resulting in a `hello.hvt` which can be executed by a solo5-hvt tender).

I have three items to report:
- [ ] I started with a mirage-skeleton repository which was dirty (I did some previous builds with mirage3 in there), a `mirage clean` did not clean up the mirage3 generated files. IMHO this should be done for enhanced usability.
- [ ] the generated Makefile only works with GNU make. I suggest to name it GNUmakefile so that there are no surprises (GNU make will use GNUmakefile if present, BSD make will not use it). In mirage3 we generated a Makefile that was usable with both BSD and GNU make (I don't think we should do that, it easily becomes a nightmare to write/generate portable Makefiles)
- [x] warnings from the generated opam file (see below) -- I suggest to generate an opam file that opam is satisfied with (if easily possible).
- [ ] mirage build / make build returned a bunch of warnings and exited with 0. I'd suggest to (partially) implement #921, and upon success of `mirage build` (is it just a dune build?) output "error yyy" or "success, the generated image is dist/zzz"
- [x] the documentation of `--no-extra-repo` could be improved to re-state that by default, mirage/opam-overlays.git is used.
- [x] is `opam depext` still used, I thought some recent opam monorepo had a builtin depext command? If it is not used anymore, the documentation of `--no-depext` should be updated. :)

opam warnings:
```
==> Wrote lockfile with 45 entries to mirage/hello-hvt-monorepo.opam.locked. You can now run opam monorepo pull to fetch their sources.
 ↳ lockfile depexts
[WARNING] Failed checks on hello-hvt-monorepo package definition from source at
          file:///usr/home/hannes/devel/mirage/mirage-skeleton/tutorial/hello/mirage:
  warning 25: Missing field 'authors'
  warning 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
  warning 47: Synopsis (or description first line) should start with a capital and not end with a dot
removing overlay repository mirage-tmp
```

**Comment by hannesm** [comment]
oh, one more thing -- the flags passed to ocamlc, namely `safe-string` (default since 4.06.0) and the warnings "-w +A-4-41-42-44" I'd drop (and use the dune & ocamlc defaults).

**Comment by dinosaure** [comment]
I agree that we should delete "un bonne fois pour toute" these annoying warning :+1:.

**Comment by TheLortex** [comment]
Thank you for testing mirage 4 !
 

>     * [ ]  I started with a mirage-skeleton repository which was dirty (I did some previous builds with mirage3 in there), a `mirage clean` did not clean up the mirage3 generated files. IMHO this should be done for enhanced usability.

Indeed, I agree this should be fixed.

>     * [ ]  the generated Makefile only works with GNU make. I suggest to name it GNUmakefile so that there are no surprises (GNU make will use GNUmakefile if present, BSD make will not use it). In mirage3 we generated a Makefile that was usable with both BSD and GNU make (I don't think we should do that, it easily becomes a nightmare to write/generate portable Makefiles)

Do you know why the generated makefile doesn't work with BSD make ? If there's a simple change to make it compatible we could integrate that. Otherwise yes the renaming sounds fine.

>     * [ ]  warnings from the generated opam file (see below) -- I suggest to generate an opam file that opam is satisfied with (if easily possible).

The opam file warning is actually becase the lockfile generated by opam-monorepo is parsed as an opam file by opam to obtain the external dependencies. The PR https://github.com/mirage/mirage/pull/1252 fixes that issue by using the `opam-monorepo depext` command instead.

>     * [ ]  mirage build / make build returned a bunch of warnings and exited with 0. I'd suggest to (partially) implement [output "what to do next" #921](https://github.com/mirage/mirage/issues/921), and upon success of `mirage build` (is it just a dune build?) output "error yyy" or "success, the generated image is dist/zzz"

Yes it's just a dune build. I agree on adding a message.

>     * [ ]  is `opam depext` still used, I thought some recent opam monorepo had a builtin depext command? If it is not used anymore, the documentation of `--no-depext` should be updated. :)

As stated before, the opam monorepo depext command is used in https://github.com/mirage/mirage/pull/1252

**Comment by hannesm** [comment]
> Do you know why the generated makefile doesn't work with BSD make ? If there's a simple change to make it compatible we could integrate that. Otherwise yes the renaming sounds fine.

I don't know exactly - conditionals are different (not used here) and shell command syntax may be different. But really, since solo5 and OCaml already depend on GNU make, I don't think it is worth to make the Makefile portable to BSD make.

> #1252 

Then let's merge that :) And if not done in there, adapt the documentation in `mirage --help` about no-depext :)

**Comment by samoht** [comment]
> I started with a mirage-skeleton repository which was dirty (I did some previous builds with mirage3 in there), a mirage clean did not clean up the mirage3 generated files. IMHO this should be done for enhanced usability.

We can fix this by explaining how to clean things in the release announcement, we don't need to add complex code to fix this.

**Comment by hannesm** [comment]
Most tasks are done, there are separate issues for the remaining ones (maybe apart from the "mirage clean" not cleaning, but then there's `git clean -dfx`). Closing.
