### ISSUE TITLE
reduce opam complexity: mirage-protocols and mirage-stack

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1255]
in our last meeting (//cc @mirage/core) we discussed that the mirage ecosystem and packages are slightly complex, since the interface and implementation -- even if we only have a single one -- are disconnected in separate opam packages (and git repositories). one path is to move everything to a monorepo. another path is to move the signatures back to the implementations and cut major releases (this will of course make the monorepo approach still doable).

To start this off, I spend some time on mirage-protocols and mirage-stack -- moving them back to the respective repositories. This turned out pretty nicely, and touches only some packages (this meta-issue is meant to track the PRs with the goal to merge and release them):
- [x] https://github.com/mirage/ethernet/pull/8 moves Mirage_protocols.ETHERNET back into mirage/ethernet. https://github.com/ocaml/opam-repository/pull/20190
- [x] https://github.com/mirage/arp/pull/27 (depends on ethernet) https://github.com/ocaml/opam-repository/pull/20199
- [x] https://github.com/mirage/mirage-tcpip/pull/463 (depends on arp and ethernet) https://github.com/ocaml/opam-repository/pull/20201
- [x] https://github.com/mirage/charrua/pull/116 (depends on arp, ethernet, tcpip) https://github.com/ocaml/opam-repository/pull/20254
- [x] https://github.com/mirage/mirage-protocols/pull/30 https://github.com/ocaml/opam-repository/pull/20255
- [x] https://github.com/mirage/mirage-stack/pull/21 https://github.com/ocaml/opam-repository/pull/20257
- [x] https://github.com/mirage/mirage-nat/pull/46 https://github.com/ocaml/opam-repository/pull/20258
- [x] mirage https://github.com/mirage/mirage/pull/1259 (and https://github.com/mirage/mirage/pull/1260) https://github.com/ocaml/opam-repository/pull/20279
- [x] mirage-skeleton https://github.com/mirage/mirage-skeleton/pull/320 (and https://github.com/mirage/mirage-skeleton/pull/321)

**Comment by hannesm** [comment]
The plan for smooth handover is:
- get the code into place (remove dependencies on miage-protocols & mirage-stack in ethernet, arp, tcpip, charrua)
- release mirage-protocols and mirage-stack that are completely deprecated
- still keep the same module types around -- a unikernel that uses Mirage_stack.V4V6 should continue to work
- once we revise/break the API, conflict in tcpip (or other libraries) with mirage-protocols/mirage-stack

I'll continue to work on that and try to get the smooth migration done. This is also independent of MirageOS releases (and will work with both mirage3 and mirage4).

**Comment by hannesm** [comment]
ok, an update to compatibility:
- mirage-protocols and mirage-stack now depend on tcpip (and are deprecated), in https://github.com/mirage/mirage-stack/pull/21 and https://github.com/mirage/mirage-protocols/pull/30
- this allows mirage-skeleton to mostly work (including static_website_tls) out of the box
- `application/dhcp` (and `application/pin`) do not work since ethernet revised the interface (it is packed now, and Ethernet.Packet.sizeof_ethernet is the new name of Ethernet_wire.sizeof_ethernet) -- but the fix is straightforward
- there are some other API changes (such as Mirage_protocols.Keepalive.t is no longer defined, etc.) -- but I couldn't find a package that uses them.

The release plan would be:
- the above 4 packages (ethernet, arp, tcpip, charrua), and mirage-protocols and mirage-stack (where existing ethernet, arp, tcpip, charrua will get upper bounds for mirage-protocols and mirage-stack)
- we can smoothly update the unikernels with the newer packages
- at some point in the future (with mirage 4): there will be no mirage-protocols and mirage-stack around anymore.

Any objections? I could do the above package-by-package end of the upcoming week (dec 9 / 10).

For tcpip, eventually @dinosaure would like to cut a release before the changes above with the rst fixes?

**Comment by dinosaure** [comment]
I would like to fix an other bug on `mirage-tcpip` before a release, see mirage/mirage-tcpip#462 but we can integrate your change and the fix into the same release.

**Comment by hannesm** [comment]
everything is released (PRs for the main / 4 branch are pending) with mirage 3.10.8. I'm done here.
