### ISSUE TITLE
Schedule some posts over the coming days/weeks

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage#128]
Now that Mirage 1.0 is out, we need to put together a bunch of posts to describe the system and help people (and each-other) get to grips with it.

This will effectively form some of the documentation so it's more than just blog posts and wiki pages -- getting this content in written form is important and we can come back to each one to properly cross-reference. :)  

Below are some ideas for posts we think are needed and also some people who could write them.  If you're ok with the list as is, please say so in the comments.  The idea is that once we've agreed on *what* posts we need, we'll create a *separate* issue for each post, where we can discuss what the contents need to include.

I'd also like us to agree on a schedule of posts so that this doesn't slip and we can (1) keep the cadence up while (2) spreading the work.

#### Homepages

- [x] mirage-www (crunch) -- @avsm (12 Dec)
- [x] mirage-decks -- @mor1 (13 Dec)
- [x] Deployment on Amazon -- @djs55 and @avsm (16 Dec)
- [ ] Cowabloga -- @mor1 (18 Dec)
- [ ] Unix Raspberry Pi -- @amirmc (20 Dec)

#### Xen and the art of ~~motorcycle~~ *VM* Maintenence

- [ ] How boot works, MiniOS etc -- @avsm
- [x] Device drivers -- @djs55
- [x] Suspend/Resume -- @jonludlam
- [ ] Building a new backend/frontend driver pair (Randomfront/Randomback) -- @avsm
- [ ] Streaming unikernels directly to XenServer -- @djs55

#### Lwt

- [ ] Stuff on co-operative threading/Lwt -- @avsm
- [x] Xen Event system -- @djs55

#### New backend target (Javascript)

- [ ] Things to port (clock, console, platform) -- @avsm

#### Filesystems and middlebox stuff

- [x] crunch -- @avsm
- [ ] FUSE -- @dsheets
- [ ] FAT -- @djs55
- [ ] Xen-Disk -- @djs55

#### Networking

- [x] TCP/IP -- @balrajsingh and @avsm
- [x] unix-networking -- @avsm
- [ ] HTTP -- WHO?

#### Architecture/Types

- [ ] ctypes? -- @yallop

**Comment by samoht** [comment]
This is now out-of-date, closing. (and we have almost published everything!)
