### ISSUE TITLE
Missing mli in generated code

### ISSUE THREAD

**Issue by kit-ty-kate** [mirage/mirage#1285]
Using mirage 4.0:
```
$ mirage build
```
will always end with:
```
File "key_gen.ml", line 1:
Warning 70 [missing-mli]: Cannot find interface file.
File "main.ml", line 1:
Warning 70 [missing-mli]: Cannot find interface file.
```
These are generated code that I have no power over. It would be nice to provide mli files for them (even if empty (i suppose) in the case of `main.mli`)

**Comment by dinosaure** [comment]
Duplicate with #1244, thanks for reporting 👍
