### ISSUE TITLE
Rename `ocaml-freestanding` to `ocaml-solo5`

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage#1294]
This issue is to track a deep rename of `ocaml-freestanding` to `ocaml-solo5`. Indeed, it's related to the issue #1284 where `ocaml-freestanding` is inside a complex dependency graph. An installation of `mirage.4.0.0~beta3` and a compilation of an unikernel for Solo5 targets leads a recompilation of the whole user's ecosystem due to `mirage-no-solo5`/`mirage-no-xen`. These projects are not needed anymore and libraries should not depends on `mirage-*-{solo5,xen}`  in anyways.

The easiest solution to move forward is to rename `ocaml-freestanding` into `ocaml-solo5`. By this fact, `mirage-no-solo5`/`mirage-no-xen` will just be forgotten by any of us (and libraries) and we don't ask the user to recompile all _upstream_ dependencies )because `ocaml-freestanding` is an optional dependency of these libraries).

The second step will be, of course, a deletion of `freestanding` artifact but it's more related to: #1262. This solution take more times and it will be hard to synchronize everyone about that.

Finally, the name `ocaml-solo5` is mostly because `ocaml-freestanding` is currently slightly dependent to what Solo5 provide for Solo5 & Xen targets.

This issue want to track such move:
- [x] prepare the `mirage` tool to emit `ocaml-solo5` instead of `ocaml-freestanding`
- [x] clean `mirage-*-{solo5,xen}` if they need about the new dependency path
- [x] rename `ocaml-freestanding`
- [x] release all of them: `ocaml-solo5` -> `mirage` -> `mirage-*-{solo5,xen}`

**Comment by hannesm** [comment]
I had a look, and indeed ocaml-freestanding is only used by mirage (emitted as a build dependency in target/solo5.ml) -- the mirage-solo5/mirage-xen (and mirage-*-solo5 / mirage-*-xen) do not depend on it anymore (so task 2 above is already done).

**Comment by dinosaure** [comment]
The renaming can be done via:
- https://github.com/mirage/mirage-dev/pull/387 (which releases several packages)
- https://github.com/mirage/mirage/pull/1314 (which update the `mirage` tool)
- https://github.com/mirage/ocaml-freestanding/pull/114 (which rename the `freestanding` context into `solo5`)
