### ISSUE TITLE
Qubes target does not compile with MirageOS 4, also xen with network interface leads to assertion failure

### ISSUE THREAD

**Issue by palainp** [mirage/mirage#1299]
With mirage 4.0.0~beta3 and no pinned package I can't compile with qubes as target. Compiling mirage-skeleton/tutorial/hello with target xen and running in qubes 4.1 is fine but the qubes target is supposed to add qubes environment integration to unikernels not dedicated to qubes.

For example, I modified (I hope correctly) `mirage-skeleton/device-usage/network` to compiles with mirage 4.0.0~beta3:
```
$ git diff
diff --git a/device-usage/network/config.ml b/device-usage/network/config.ml
index c425edb..36d9d9a 100644
--- a/device-usage/network/config.ml
+++ b/device-usage/network/config.ml
@@ -4,9 +4,9 @@ let port =
   let doc = Key.Arg.info ~doc:"The TCP port on which to listen for incoming connections." ["port"] in
   Key.(create "port" Arg.(opt int 8080 doc))
 
-let main = foreign ~keys:[Key.abstract port] "Unikernel.Main" (stackv4 @-> job)
+let main = foreign ~keys:[Key.v port] "Unikernel.Main" (stackv4v6 @-> job)
 
-let stack = generic_stackv4 default_network
+let stack = generic_stackv4v6 default_network
 
 let () =
   register "network" [
diff --git a/device-usage/network/unikernel.ml b/device-usage/network/unikernel.ml
index eb4c40d..eeded88 100644
--- a/device-usage/network/unikernel.ml
+++ b/device-usage/network/unikernel.ml
@@ -1,19 +1,19 @@
 open Lwt.Infix
 
-module Main (S: Mirage_stack.V4) = struct
+module Main (S: Tcpip.Stack.V4V6) = struct
 
   let start s =
     let port = Key_gen.port () in
-    S.listen_tcpv4 s ~port (fun flow ->
-        let dst, dst_port = S.TCPV4.dst flow in
+    S.TCP.listen (S.tcp s) ~port (fun flow ->
+        let dst, dst_port = S.TCP.dst flow in
         Logs.info (fun f -> f "new tcp connection from IP %s on port %d"
-                  (Ipaddr.V4.to_string dst) dst_port);
-        S.TCPV4.read flow >>= function
+                  (Ipaddr.to_string dst) dst_port);
+        S.TCP.read flow >>= function
         | Ok `Eof -> Logs.info (fun f -> f "Closing connection!"); Lwt.return_unit
-        | Error e -> Logs.warn (fun f -> f "Error reading data from established connection: %a" S.TCPV4.pp_error e); Lwt.return_unit
+        | Error e -> Logs.warn (fun f -> f "Error reading data from established connection: %a" S.TCP.pp_error e); Lwt.return_unit
         | Ok (`Data b) ->
           Logs.debug (fun f -> f "read: %d bytes:\n%s" (Cstruct.length b) (Cstruct.to_string b));
-          S.TCPV4.close flow
+          S.TCP.close flow
       );
 
     S.listen s
```
And it fails to run with Qubes 4.1:
```
[2022-03-06 04:57:32] Logfile Opened
[2022-03-06 04:57:33] Solo5: Xen console: port 0x2, ring @0x00000000FEFFF000
[2022-03-06 04:57:33]             |      ___|
[2022-03-06 04:57:33]   __|  _ \  |  _ \ __ \
[2022-03-06 04:57:33] \__ \ (   | | (   |  ) |
[2022-03-06 04:57:33] ____/\___/ _|\___/____/
[2022-03-06 04:57:33] Solo5: Bindings version v0.7.0
[2022-03-06 04:57:33] Solo5: Memory map: 64 MB addressable:
[2022-03-06 04:57:33] Solo5:   reserved @ (0x0 - 0xfffff)
[2022-03-06 04:57:33] Solo5:       text @ (0x100000 - 0x2c5fff)
[2022-03-06 04:57:33] Solo5:     rodata @ (0x2c6000 - 0x320fff)
[2022-03-06 04:57:33] Solo5:       data @ (0x321000 - 0x488fff)
[2022-03-06 04:57:33] Solo5:       heap >= 0x489000 < stack < 0x4000000
[2022-03-06 04:57:33] 2022-03-06 09:57:33 -00:00: INF [net-xen frontend] connect 0
[2022-03-06 04:57:33] evtchn.c:278: Assertion `rc == 0' failed
[2022-03-06 04:57:33] Aborted
[2022-03-06 04:57:33] Solo5: solo5_abort() called
```

**Comment by palainp** [comment]
Oups, I forgot to give the most important information, with qubes as target, the compilation itself is ok, but it fails to link against solo5:
```
...
Successfully pulled 59/59 repositories
File "dune.build", line 7, characters 7-11:
7 |  (name main)
           ^^^^
/usr/bin/ld: cannot open linker script file solo5_qubes.lds: No such file or directory
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```

**Comment by ludovic-j** [comment]
The exact same issue appears with target xen and running on xen 4.11 and xen 4.16. The unikernel `tutorial/lwt/heads1` fails running and shows the same error at the line 278 of `evtchn.c` while `tutorial/hello` works fine. In this case, after testing, it seems that the presence of the module mirage_console creates the issue. Maybe it is the presence of some modules that breaks the running ?

**Comment by TheLortex** [comment]
Hi @palainp and @ludovic-j, thanks for testing MirageOS 4. 

For the dune build error, it looks like there is an issue in the Qubes backend as the link flag should be `-z solo5-abi=xen` instead of `-z solo5-abi=qubes`. https://github.com/mirage/mirage/blob/09d3e17125e782c58aae92c8bb2f849b41fd2037/lib/mirage/target/solo5.ml#L154

For the assertion failure, I don't know yet and maybe some Xen expert in the core team will have more insights.

**Comment by hannesm** [comment]
I find both -- the compilation issue for qubes target -- and the runtime issue with xen alarming. IMHO these are show toppers for the release and should be investigated and fixed -- esp. since the very same unikernel with MirageOS3 works fine.

**Comment by samoht** [comment]
@talex5 @djs55 do you understand what happens there? It seems that the same C code is working fine with MirageOS 3 but it's now broken with Mirage 4 (so probably an issue with the C flags that we are using to build the Xen object files). 

Do you think you could help? 

We'll fix the symbol issue to at least fix the compilation on Xen/qubes for 4.0 but would be nice to fix the runtime bits as well for our Xen users...

**Comment by palainp** [comment]
> ```
> [2022-03-06 04:57:33] evtchn.c:278: Assertion `rc == 0' failed
> ```
> 
> The line is wrong for Solo5 0.7.{0,1} but it seems related to a hypercall which returns an error but I really don't know which one.

It's from https://github.com/mirage/mirage-xen/blob/f57b9f1d430d7238a002d08aadc7c0c4e743e076/lib/bindings/evtchn.c#L278

**Comment by hannesm** [comment]
@palainp well spotted. Does https://github.com/mirage/mirage-xen/pull/46 fix that issue for you?

**Comment by palainp** [comment]
As for @ludovic-j it does not works for me, but it's a promising track. If I change `evtchn.c` to force the `__XEN_INTERFACE_VERSION__` before the includes, the unikernel runs fine with qubes 4.1 (xen 4.14).
```
#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
+#define __XEN_INTERFACE_VERSION__ 265472
#include "solo5.h"
#include "bindings.h"
#include "hypercall.h"
#include "xen/xen.h"
#include "xen/event_channel.h"
```
To me all is like the -D option is not given to the compiler, the exact compilation line for this file is:
```
ocamlfind -toolchain solo5 ocamlopt -cclib "-I ./include/  -O2 -std=c99 -Wall -Werror -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__"   -c -o evtchn.o evtchn.c
```

**Comment by hannesm** [comment]
Thanks, I just pushed to the same PR a commit that removes the quotes -- does this work better? ;)

**Comment by palainp** [comment]
I changed a bit your diff for (the quote must be present, or multiple ccopt seems to also works):
```
CFLAGS=-ccopt "-I ./include/ -O2 -std=c99 -Wall -Werror -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__"
```
cclib is only forwarded to the linker, whereas ccopt is for compiler and linker.
This works great for me, I hope it will be the same for @ludovic-j.

**Comment by hannesm** [comment]
great, could you PR that to mirage-xen? :)

**Comment by ludovic-j** [comment]
It works perfectly now ! Thank you ! :)

**Comment by palainp** [comment]
Many thanks to everyone !
