### ISSUE TITLE
Update the DNS performance tests page on the wiki

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#133]
The DNS performance test page on the Wiki is rather out of date, and being able to run these tests on the latest code would be useful (if only as a performance regression test, but also as a way to reproduce our ASPLOS 2013 results).
http://www.openmirage.org/wiki/performance

See comment: http://www.openmirage.org/wiki/performance#comment-1157202534

**Comment by yomimono** [comment]
The situation is a bit worse than needing to update the DNS performance numbers, as the bytecode backend (used to obtain those numbers IIRC) is long bitrotted?

There are some issues reflecting the need for performance testing/performance regression analysis at https://github.com/mirage/mirage-tcpip/issues/314 and https://github.com/mirage/mirage/issues/685 , which are stated in more modern terms and with more specific action steps.
