### ISSUE TITLE
Generated Makefile only support GNU make

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1330]
as reported in #1254

>    * [ ]  the generated Makefile only works with GNU make. I suggest to name it GNUmakefile so that there are no surprises (GNU make will use GNUmakefile if present, BSD make will not use it). In mirage3 we generated a Makefile that was usable with both BSD and GNU make (I don't think we should do that, it easily becomes a nightmare to write/generate portable Makefiles)

@TheLortex  asked:

> Do you know why the generated makefile doesn't work with BSD make ? If there's a simple change to make it compatible we could integrate that. Otherwise yes the renaming sounds fine.

Now I took a look again:
- (a) `--no-print-directory` is a GNU make extension
```
 depends depend::
-       @$(MAKE) --no-print-directory lock
-       @$(MAKE) --no-print-directory install-switch
-       @$(MAKE) --no-print-directory pull
+       @$(MAKE) lock
+       @$(MAKE) install-switch
+       @$(MAKE) pull
```

- (b) `$(shell ...)` is a GNU make extension (also `abspath` is GNU make only):
```
+OCAML_VERSION != ocamlc --version
+
 $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam.locked: $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam
        @$(MAKE) -s repo-add
        @echo " ↳ generate lockfile for monorepo dependencies"
-       @$(OPAM) monorepo lock --require-cross-compile --build-only $(UNIKERNEL_NAME) -l $@ --ocaml-version $(shell ocamlc --version); (ret=$$?; $(MAKE) -s repo-rm && exit $$ret)
+       @$(OPAM) monorepo lock --require-cross-compile --build-only $(UNIKERNEL_NAME) -l $@ --ocaml-version $(OCAML_VERSION); (ret=$$?; $(MAKE) -s repo-rm && exit $$ret)
...
+ABS_BUILD_DIR != realpath $(BUILD_DIR)
+
 pull:: $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam.locked
        @echo " ↳ fetch monorepo rependencies in the duniverse folder"
-       @$(OPAM) monorepo pull -l $< -r $(abspath $(BUILD_DIR))
+       @$(OPAM) monorepo pull -l $< -r $(ABS_BUILD_DIR)
```

- (c) `$<` is a GNU make extension:
```
 depext-lockfile: $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam.locked
        echo " ↳ install external dependencies for monorepo"
-       $(OPAM) monorepo depext -y -l $<
+       $(OPAM) monorepo depext -y -l $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam.locked
...
 pull:: $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam.locked
        @echo " ↳ fetch monorepo rependencies in the duniverse folder"
-       @$(OPAM) monorepo pull -l $< -r $(abspath $(BUILD_DIR))
+       @$(OPAM) monorepo pull -l $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam.locked -r $(abspath $(BUILD_DIR))
 
 install-switch:: $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam
        @echo " ↳ opam install switch dependencies"
-       @env OPAMVAR_switch="" $(OPAM) install $< --deps-only --yes
+       @env OPAMVAR_switch="" $(OPAM) install $(MIRAGE_DIR)/$(UNIKERNEL_NAME).opam --deps-only --yes
        @$(MAKE) -s depext-lockfile
```

I've no idea what "(ret=$$?; $(MAKE) -s repo-rm && exit $$ret)" should do and how to make it portable between make.

**Comment by dinosaure** [comment]
Do you prefer to generate `GNUmakefile` (and assume to use into *BSD GNU make) or improve the generated Makefile to work everywhere?

**Comment by hannesm** [comment]
@dinosaure good question, I'm undecided. I'm fine with GNU only Makefile, since that's what is tested in CI anyways.

**Comment by hannesm** [comment]
I'm closing this issue. It seems to be that there's not much interest, and an attempt to just rename the Makefile to GNUmakefile broke something in the toolchain that I don't want to dig into further.
