### ISSUE TITLE
mirage 4 regression: naming

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1345]
Previously (mirage 3), I had a unikernel with `register "nqsb.io"`, now with mirage4 this leads to a compilation error (shouldn't it be a configure error?):

```
] dune bu
File "dune-project", line 3, characters 6-17:
3 | (name nqsb.io-hvt)
          ^^^^^^^^^^^
Error: Invalid project name
```

**Comment by reynir** [comment]
The check done in dune seems to be that the string is non-empty and doesn't contain `.` or `/` FWIW.
https://github.com/ocaml/dune/blob/main/src/dune_engine/dune_project.ml#L66-L71

**Comment by hannesm** [comment]
FWIW, I don't really care. There's difference in mirage 3 and mirage 4 -- but at the same time, mirage 4 is out since > 1 year, and we've more interesting issues to fix. The amount of mirage 3 unikernels that stumble upon this issue is as well very minimal it seems.
