### ISSUE TITLE
mirage 4 question in respect to repository layout

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1346]
With mirage4 and the usage of the dune build system, it is no longer easy to have an opam package and example unikernels in the same git repository.

I'd like to know whether there is any story how to support it?

Take mirage-www as example, this avoids to define any public library, and then invokes mirage from the top of the repository. This doesn't scale to public opam repositories.

Take mirage-tcpip as example, here the unikernel (in example/unikernel) can be configured and built nicely, but uses tcpip from opam-repository (not the local build). In addition, once it is build in a checkout, a normal `dune build` fails:
```
Error: Too many opam files for package "tcpip":
- tcpip.opam
- examples/unikernel/duniverse/mirage-tcpip/tcpip.opam
```

I also tried with symlinks from vendor/<library> to ../, but then dune complains that it scanned the unikernel directory again. My wish would be (for tlstunnel, openvpn, mirage-tcpip, bob, ...) to have:
```
/<package.opam>
/src
/mirage/config.ml
/mirage/unikernel.ml
```

And an invocation of `mirage configure && mirage build `in the mirage subdirectory will use the sources from `../src`. Is there any way to make this possible?

**Comment by hannesm** [comment]
FWIW, some further discussion at https://github.com/roburio/tlstunnel/issues/6

It would be nice if there would be reasonable paths supporting such a workflow (//cc @TheLortex @dinosaure @samoht)

**Comment by TheLortex** [comment]
Hey, this workflow is supposed to work, as `opam-monorepo` is able to figure out that `tcpip.opam` is locally available.
However the tricky part is that you have to run `mirage configure -f mirage/config.ml` to correctly configure the root of the project, otherwise `opam-monorepo` won't be able to pickup the local instance of the package.
