### ISSUE TITLE
The `resolver` device (conduit) uses an outdated DNS resolver by default

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage#1360]
We probably should reset the default DNS resolver of the `resolver` device to be sure that if someone use it, he/she will not get a _timeout_ error in anyway. This is article about why the clear DNS resolver was turned off: https://blog.uncensoreddns.org/blog/40-cleartext-dns-turned-off/. Thanks to @reynir who sent an email about that on the mailing list.

**Comment by hannesm** [comment]
So, the easy solution it seems is to remove the hardcoded one from ocaml-conduit, and go with the default one in ocaml-dns (which uses uncensoreddns via TLS).

But I've no clue who uses the resolver device (and conduit) -- and maybe another path is to just remove it from mirage?

**Comment by hannesm** [comment]
fixed in #1362 (and conduit 6.0.0) thanks to @reynir
