### ISSUE TITLE
Delete `git_happy_eyeballs` at the next release

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage#1378]
This device is deprecated (and noted into the documentation as well). We advise users to use `mimic_happy_eyeballs` instead of. At the next release, we should delete this depreacated device.

**Comment by TaeminHa** [comment]
Hi! I'm a student taking a Virtualization course at the University of Texas at Austin.

I noticed that git_happy_eyeballs wasn't deleted and still remains in the latest release.
(It is included in the mirage.ml, mirage.mli, and mirage_impl_git.ml files)

Can I work on this issue?

**Comment by dinosaure** [comment]
Yes, for sure 🙂 , I will review your work then.

**Comment by TaeminHa** [comment]
I just completed the pull request ( #1388 ) and verified that it passes all tests.
 
I believe the issue should be fixed now, but please let me know if there's anything I can improve/work on additionally.

**Comment by hannesm** [comment]
Thanks for your PR, which was merged. I'll close this issue as it has been resolved.
