### ISSUE TITLE
merlin does not work when working on MirageOS 4 unikernels

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1384]
I've no clue why, but editing a unikernel.ml file does not lead to a merlin-friendly environment. There's, similar to MirageOS 3 days, still "Unbound module Lwt" etc. around.

I thought / hoped that MirageOS 4 with the new build system would solve this issue completely.

**Comment by TheLortex** [comment]
For which target have you configured the unikernel ?
- For unix it's surprising. The only requirement is that the unikernel has to be built. 
- For hvt, you need to add the `(merlin)` stanza in the generated `dune-workspace` file. 
```
(context (default
  (name solo5)
  (host default)
  (toolchain solo5)
  (disable_dynamically_linked_foreign_archives true)
  ))
```
=> 
```diff
 (context (default
   (name solo5)
   (host default)
   (toolchain solo5)
+  (merlin)
   (disable_dynamically_linked_foreign_archives true)
   ))
```

**Comment by hannesm** [comment]
Thanks for your reply, @TheLortex. So indeed I use `hvt` as target. Is there any reason to not emit the `(merlin)` in the generated `dune-workspace` file? I hesitate to modify generated files.

**Comment by TheLortex** [comment]
It must have been forgotten at some point. You're right, it should be emitted by the mirage tool.

**Comment by hannesm** [comment]
I opened #1385, would be great if you could review :) thanks a lot.
