### ISSUE TITLE
bounds on solo5 do not work

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1420]
I still don't understand, but using an opam file generated from mirage, which includes `"solo5" {build & >= "0.7.5" & < "0.8.0"}` leads to installing solo5 0.8.0 :/

I don't quite understand this opam file business anymore, and the main question I have is: why are there only "build" depedencies to mirage / solo5 / etc.? i.e. all dependencies are either `build` or `monorepo`? I thought that `build` would actually not be the right thing (since, if solo5 is updated, the unikernel should be rebuild, no?)

Maybe the underlying issue is that these opam files are not used (by anyone else apart from myself) for unikernel installations (but only for driving opam-monorepo, which purpose is to look into the dependencies tagged with `?monorepo`)?

Any help / insight would be appreciated /cc @dinosaure @TheLortex @samoht

**Comment by samoht** [comment]
Could you describe how you are using the generated opam files? Who/what tools is supposed to use those?

**Comment by samoht** [comment]
Is it supposed to install the dependencies in the local empty switch? That won't work as we need to get the sources in the dune-workspace to x-compile the unikernel. Or are you ok with also shipping the dependencies of the sources in your release tarball?

**Comment by hannesm** [comment]
> Is it supposed to install the dependencies in the local empty switch?

Not sure what "it" refers to, neither "the dependencies".

> shipping the dependencies of the sources in your release tarball

I'm also not sure what this means, usually my unikernels do not have release tags, but are just referred to by the main git branch.

How orb works:
- takes an opam file as input (generated by `mirage configure -t hvt`)
- strips environment variables to the bare minimum (PATH / HOME), also fiddles with SOURCE_DATE_EPOCH / OPAMSOLVERTIMEOUT / OPEMERRLOGLEN
- creates an empty opam switch (using a static directory)
- sets up opam repositories
- (in the opam-monorepo case) installs dependencies of the opam package into the switch (e.g. mirage, solo5, ocaml-solo5)
- (in the opam-monorepo case) downloads and extracsts sources (of the unikernel), executes the configure and pre-build commands, runs the build steps

An example opam file to use is https://git.robur.io/robur/unikernel-repo/src/branch/main/packages/mirage-unikernel-hello-hvt.0.0.2/opam

Does this make sense?

From the commit log, I can tell that 4.3.2 (with https://github.com/mirage/mirage/commit/a7aeac8a706340ec8c789ea2cd9703259f41e0cc) introduced the `solo5` dependency, and 4.3.3 (with https://github.com/mirage/mirage/commit/18f2672913250ecb0bebbffa7f487864d1c9b5cb) corrected it. So maybe I only suffer from some opam files generated by ancient mirage versions.

In any case, I don't quite understand the `build` directive on the dependencies that are installed into the switch, can't we use normal dependencies here? And leave the dependencies for the monorepo as `?monorepo`?

Why this issue is a thing: solo5 0.8.0 introduced an ABI change, and requires a different solo5-hvt than earlier (0.7.x) releases.

**Comment by hannesm** [comment]
I guess this issue is not an issue (cause were old opam packages). But there are still some questions, I'll open a separate issue about that.
