### ISSUE TITLE
app_info: quo vadis?

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1438]
Hey (esp. @samoht who seems to be eager to keep and improve app_info),

I used to be a fan of the `app_info` stuff in mirage, but I wonder whether it is just out of scope for mirage. My reasoning behind this is:
- what is its purpose? should a unikernel "know" (from the inside) what the building blocks thereof are?

Now, with reproducible binary builds available, I learned, there's more to capture:
- environment variables
- system packages (such as c compiler, linker, ..)
- opam packages _including_ build instructions, link to tarballs and checksums, for git repos the specific commit id (it is important to capture the hash of the tarball since there are so many things that may call themselves "cmdliner 1.0.2" -- so version identifiers are not unique)

--> this is achieved by [orb](https://github.com/roburio/orb), by leveraging opam's API (and using opam switch export --full --freeze), together with some of the information gathered by opam-monorepo.

But, app_info just doesn't cut it: there is lots of stuff missing that means it cannot serve as a recipe for reproducing the same binary. I'm all for providing reproducible builds and generating SBOM for a built unikernel, but with the above knowledge, I don't see any particular reason to integrate this into the mirage tool.

So, for me: I lookup the hash of the running binary in the reproducible build database, and can then figure out which opam packages in which versions are part of that unikernel. If some is erroneous or has a security issue, I can act.

Only using app_info won't bring me there, since e.g. if a bad C compiler has been used, I won't detect that.

So, for me the whole app_info stuff is dead code and can safely be removed since we have since some years a working alternative to produce and reproduce identical MirageOS unikernel images.

Running the mirage-skeleton/tutorial/app_info unikernel shows:
```
2023-06-21 23:41:52 +02:00: INF [application] name = app-info
libraries = [dune-build-info.3.8.2; fmt.0.9.0+dune; bytes.0.1.0; lwt.5.6.1;
             parse-argv.0.3.0; mirage-bootvar-unix.0.1.0; mirage-clock.4.2.0;
             unix.[distributed with OCaml]; mirage-clock-unix.4.2.0;
             logs.0.7.0+dune2; ptime.1.1.0+dune; mirage-logs.1.3.0;
             cmdliner.1.1.1; functoria-runtime.2a74e3e; macaddr.5.5.0;
             domain-name.0.4.0; ipaddr.5.5.0; mirage-runtime.2a74e3e;
             duration.0.2.1; bigarray.[distributed with OCaml];
             ocplib-endian.2a74e3e; ocplib-endian.bigstring.2a74e3e;
             threads.posix.[distributed with OCaml];
             threads.[distributed with OCaml]; lwt.unix.5.6.1;
             mirage-unix.5.0.1]
```

I struggle here with `ocplib-endian` - why is there a specific `2a74e3e` (which is the same as `mirage-runtime`? Why is there no ocaml version? And what does the 2a74e3e mean? I can't find a commit with that prefix.

Of course, if you think there's use for app_info, let's keep it. Just from my point of view, it does not make sense to have this inside of a MirageOS unikernel, and there's tooling for reproducibility outside of mirage.

**Comment by reynir** [comment]
I found the 2a74e3e prefix in https://github.com/mirage/mirage-skeleton/pull/362. I also found that the META file for ocplib-endian on my machine does not have a version field. I don't know if there's a correlation here. Thinking out loud: maybe mirage is not able to figure out the version and puts the git hash prefix of CWD as version.

**Comment by reynir** [comment]
Yes, it seems the version field from the META file is used otherwise. For example: `bigarray/META:version = "[distributed with Ocaml]"`

**Comment by reynir** [comment]
After digging in the mirage/functoria code base I discovered that dune-build-info is used https://dune.readthedocs.io/en/stable/dune-libs.html#dune-build-info-library

**Comment by samoht** [comment]
The initial idea was to easily expose an endpoint where people could see and inspect the sources/dependencies of a live uniknernel. `app_info` was not designed to be secure/spoof-proof, but just as an excellent way to demo the kind of things that were possible when you were building smaller VMs.

We now seem to have the necessary infrastructure to do this differently. Maybe we could compute this hash on startup and expose it somewhere to be used by the unikernel (for instance, to query the `orb` API to get a manifest). We could also have a different way to compute the manifest by querying `orb` at configuration time? Not sure how all this work together. But then do we always have to compile unikernels with orb?

Or could we replace this with a mechanism where unikernel could broadcast the hash of their binary to clients so that they can check what version of the software stack they are talking to? But maybe that's useless :p

**Comment by hannesm** [comment]
Thanks @reynir for your investigations.

@samoht:

> Maybe we could compute this hash on startup and expose it somewhere to be used by the unikernel

I don't see an easy way to do this -- certainly a solo5 tender could do that (since it has access to the full image) -- but then we've virtio/xen/muen support without tenders.

For deployments where you use albatross, albatross does actually compute and output the hash (via the info command). For other unikernels, you can use sha256 once you have access to the image. From inside a unikernel I guess it is rather tricky.  Of course you can come up with your custom linker and embed the build-info / SBOM data inside the unikernel image (in a special section).

> We could also have a different way to compute the manifest by querying orb at configuration time?

I've no idea what the goal is here.

> But then do we always have to compile unikernels with orb?

No, you can always compile your unikernel with mirage, as you do now. For a reproducible build setup, of course you can reinvent things or reuse existing tooling. Just all the tooling I could find (dune, opam, opam-monorepo\ didn't meet the needs.

> what version of the software stack they are talking to?

I see multiple layers of versioning, on the one hand it is protocols (i.e. TLS) that negotiate a protocol version. Now, as mentioned above, "computing the hash from inside" is rather tricky.

I still lack the concrete real-world use case for the paths that you propose. For me it works best if you'd describe the deployment you are doing and which operational needs you have.

It's as well fine to say "let's keep the app_info" -- what I intended to bring across that it is quite a bit of code (distributed around functoria-runtime, functoria, mirage), and I'm not sure how useful it is.

**Comment by samoht** [comment]
> I still lack the concrete real-world use case for the paths that you propose

As stated above, the concrete use case is the ability to demo it :-) We made a few demos where the list of packages is server over HTTP, and people could "see" the list change when you update a dependency. It's a very efficient way to make people understand what is happening.

**Comment by hannesm** [comment]
then let's keep it for your demos.
