### ISSUE TITLE
Docteur with relative paths look in _build/ directory

### ISSUE THREAD

**Issue by reynir** [mirage/mirage#1445]
I had an issue with the mirage-skeleton docteur example. It turned out it was due to my dns resolver not supporting dns over tcp, and dns-client-lwt only supports dns over tcp and dns over tls at the moment. I therefore thought to change the example to use the local git repository with the `relativize://` scheme. This has the benefit that the example will work without a (reliable) internet connection or when GitHub is down. However, `docteur.make` is run with cwd deep inside the `_build/` directory:

```
diff --git a/applications/docteur/config.ml b/applications/docteur/config.ml
index 5e3238c..a9659b4 100644
--- a/applications/docteur/config.ml
+++ b/applications/docteur/config.ml
@@ -4,9 +4,9 @@ let filename =
   let doc = Key.Arg.info ~doc:"The filename to print out." [ "filename" ] in
   Key.(create "filename" Arg.(required string doc))
 
 let unikernel = foreign "Unikernel.Make" ~keys:[ Key.v filename ] (kv_ro @-> job)
-let remote = "https://github.com/mirage/mirage"
+let remote = "relativize://../../.git"
 
 let () =
   register "static_kv_ro"
     [ unikernel $ docteur ~branch:"refs/heads/main" remote ]
```

```
File "applications/docteur/dune.build", line 21, characters 0-199:
21 | (rule
22 |  (targets disk)
23 |  (enabled_if (= %{context_name} "default"))
24 |  (deps (:make %{bin:docteur.make}) (source_tree ../../.git))
25 |  (action (run %{make} relativize://../../.git -b refs/heads/main disk)))
make: /home/reynir/workspace/mirage-skeleton/_build/default/applications/docteur/../../.git does not exists.
```

**Comment by dinosaure** [comment]
I agree with your change even if it seems that `dune` puts some trouble about the `Unix.getcwd ()` in `docteur.make`.

**Comment by reynir** [comment]
Yes. I wonder if it can be fixed with (chair ...). I will do some
experiments tomorrow :)

**Comment by reynir** [comment]
I found the following works **if** we provide `(dirs :standard .git)` in a dune file at the project root:
```dune
(rule
 (target disk)
 (enabled_if (= %{context_name} "default"))
 (deps (:make %{bin:docteur.make}) (source_tree %{project_root}/.git))
 (action (run %{make} relativize://%{project_root}/.git -b refs/heads/main %{target})))
```

Adding `(dirs :standard .git ../../.git)` or any combination thereof inside `device-usage/docteur/dune` does not work. It seems from my experiments that it's not possible to add to `dirs` elements that are not descendants of the containing directory.

To me it seems very hard if not impossible to use docteur.make on the enclosing git repository that works in general :/

**Comment by TheLortex** [comment]
By default `dune` ignores directories that start with a `.` or `_`: https://dune.readthedocs.io/en/stable/dune-files.html#dirs

**Comment by reynir** [comment]
Unfortunately this seems to be too difficult to solve with the current dune behavior :/
