### ISSUE TITLE
Muen and boot parameters

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1459]
Dear @Kensan and @reet-,

due to some cleanups and reducing the complexity and what mirage, the tool, should do, we would like to remove the "cross-stage" unikernel arguments -- i.e. passing things such as `--ipv4=127.0.0.2/24` will no longer be available at `mirage configure` time, but instead only at runtime / startup.

Now, in muen there's (as far as I remember) no support for boot arguments (or is there? on the solo5 layer, there's a call to `cons char *platform_cmdline(void)` -- but is this implemented on muen?)

Also, we were curious whether there could be support to store arguments on a block device, but there seems to be still no support for block devices for muen in solo5 (and supporting reading boot parameters from a block device would require some more changes to mirage, but we could do them).

So, the question is: is it feasible (for you?) to have an element in the muen policy that specifies boot parameters, which is then made available to the subject via the above mentioned `platform_cmdline` function? FWIW this only needs to be a string, not an argv (due to how other targets implement this) ;)

**Comment by Kensan** [comment]
> Now, in muen there's (as far as I remember) no support for boot arguments (or is there? on the solo5 layer, there's a call to `cons char *platform_cmdline(void)` -- but is this implemented on muen?)

There is support for [command line arguments on Muen](https://muen.sk/articles.html#running-unikernels). The boot parameters are mapped to the `<bootparams>` feature in Muen Component XML Specification and then processed by our Solo5 boot info generator tool, which runs at System Integration time.

> Also, we were curious whether there could be support to store arguments on a block device, but there seems to be still no support for block devices for muen in solo5 (and supporting reading boot parameters from a block device would require some more changes to mirage, but we could do them).

As you mentioned, we would need to implement a driver for the block device interface first. Some small code snippets exist, but they are far from a workable implementation at this point...

> So, the question is: is it feasible (for you?) to have an element in the muen policy that specifies boot parameters, which is then made available to the subject via the above mentioned `platform_cmdline` function? FWIW this only needs to be a string, not an argv (due to how other targets implement this) ;)

Yes, this should already be possible via the `--bootparams` argument of the [`tools/scripts/solo5-muen-gencspec.py`](https://git.codelabs.ch/?p=muen.git;a=blob;f=tools/scripts/solo5-muen-gencspec.py;h=92be1e5063471bae1650fac535e1187e2e4dc6ff;hb=3fba22d74de470d7aabbcc9a8c239e137a649435) script :)

**Comment by hannesm** [comment]
excellent, thanks for your quick reply. so, nothing to do here :)
