### ISSUE TITLE
Provide a boot parameter to delay startup by some seconds

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1468]
Tunrs out, some backends (e.g. muen) need some more time to setup the virtual network card. A configurable delay as boot parameter would be excellent in such a use case.

**Comment by palainp** [comment]
Thanks for the PR, but I wonder, as muen uses solo5 as tender (but maybe at some point this PR will be used for other targets, and my comment will be irrelevant :) ), wouldn't it be possible (hmm maybe it's harder or adds to much complexity :( ) to tackle this issue inside solo5 (e.g. `solo5/bindings/muen/start.c`)?

**Comment by hannesm** [comment]
The question is: what do we want to achieve? Of course, we can implement a lot in a specific target. But this makes the whole system differently behaving depending on the target.

In addition, implementing this in solo5 would mean that the boot arguments need to be passed to solo5 and decoded there.

So, I'm in favour of target-independent solutions -- and while there already happens a lot of stuff before the delay is conducted (such as memory setup, OCaml runtime startup, ...) -- the underlying issue (waiting for the network device to be ready) is handled by the PR provided. :)

**Comment by palainp** [comment]
That is perfectly fine for me, thank you!
