### ISSUE TITLE
request for input: should we remove --config-file / -c / --file argument?

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1471]
My gut feeling is there's quite some complexity since we're passing the configuration file name across the entire application for no really good reason (convince me if I'm wrong).

If we just hardcode "config.ml must be config.ml at the current working directory", we don't have to deal with `-f` specifying any relative or absolute directory. I'm not sure whether we loose anything by going down that path. Likely @samoht has an opinion since I remember he worked quite hard to support that option in MirageOS 4.

Since the next mirage release already collects some breaking changes, maybe now it is the time to decide on this? I went down the road trying to fix https://github.com/mirage/mirage/issues/1357 with no luck so far...

//cc @mirage/core

**Comment by samoht** [comment]
From a UX point-of-view I really quite like doing being able to configure all the unikernels in mirage-skeletons from the root directly, and then build all of them in one go.

I'm not sure how to do this if we remove the `-f` parameter. We will need a way to specify the root directly instead.

**Comment by hannesm** [comment]
So, apart from the mirage-skeleton use case -- do you have any other usecase in mind? I'd avoid code complexity since our "example repository" is special (also, what prevents us from `cd tutorial/hello ; mirage configure ; make ; cd ..` for all the unikernels?

**Comment by samoht** [comment]
That's valid for any multi-unikernel repository use-case.

**Comment by hannesm** [comment]
I'll close this issue, since I've lost interest.
