### ISSUE TITLE
Mirage-types: KV_RO `read` and `size` are inconsistent

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#149]
`size` returns an int64, and `read` only takes an `int` as the length. Why isn't this an int64?  Is the caller expected to chunk up a large size into smaller reads?

**Comment by yomimono** [comment]
https://github.com/mirage/mirage/pull/705 and the PRs linked there fix this inconsistency.

**Comment by hannesm** [comment]
..which is now merged, closing!
