### ISSUE TITLE
Documentation: don't refer to functoria documentation

### ISSUE THREAD

**Issue by reynir** [mirage/mirage#1512]
From time to time I look up documentation using either Merlin or ocp-browser, and a few values such as [`Mirage.package`](https://ocaml.org/p/mirage/latest/doc/Mirage/index.html#val-package) says e.g. "Same as [Functoria.Package.v](https://ocaml.org/p/functoria/4.4.2/doc/Functoria/Package/index.html#val-v)". This is rather annoying as in both Merlin and ocp-indent there are no hyperlinks to get to the actual documentation.

Another one is [`Mirage.impl`](https://ocaml.org/p/mirage/latest/doc/Mirage/index.html#val-impl) that defines itself as `of_device @@ Device.v` where `Mirage` doesn't even have a `Device` module.

Somewhat motivated by https://github.com/mirage/mirage-skeleton/pull/388.

**Comment by samoht** [comment]
Yea, that's a very good point. I'm trying to fix those when I see those references, but it would be nice to have a more systematic review of those references.

**Comment by hannesm** [comment]
I addressed the observed issues in #1537, happy to get a review.
