### ISSUE TITLE
`Mirage.Runtime_arg.create` undocumented

### ISSUE THREAD

**Issue by reynir** [mirage/mirage#1532]
The function `Mirage.Runtime_arg.create` (which actually lives in `Functoria.Runtime_arg.create`) is not documented.
https://github.com/mirage/mirage/blob/dceedf18f72304d025c249377e1b603a0368036f/lib/functoria/runtime_arg.mli#L22-L27

In particular it's unclear to me what the `?name` argument is used for.

**Comment by samoht** [comment]
This is a leftover from the previous implementation - `name` was now only used for internal names, so I agree it's a bit confusing to still export it. I've created #1541 to remove it completely.
