### ISSUE TITLE
Update README.md for mirage-bootvar-{unix,solo5,xen}

### ISSUE THREAD

**Issue by palainp** [mirage/mirage#1561]
Hello,
the repositories `mirage-bootvar-{unix,solo5,xen}` were merged into `mirage-bootvar` in earlier this year. Please, is it possible to update the README.md files of those repositories to point to the new one?
Thanks in advance,
Best,
/cc @reynir @hannesm

**Comment by hannesm** [comment]
Thanks, I did this in the specified repositories. and archived them gain.
