### ISSUE TITLE
Syntax ERR

### ISSUE THREAD

**Issue by SundosDBL** [mirage/mirage#1562]
Whenever I attempt to load games on my Ti-84+ with MirageOS it gives me a syntax error - something may be installed wrong, but I am pretty certain everything is proper.

**Comment by palainp** [comment]
Hello, I think you may have confused two projects with the same name but different goals & usages:
- MirageOS (`A programming framework for building type-safe, modular systems`, see https://mirage.io/),
- MirageOS (`A Flash Application for the TI-83 Plus and TI-84 Plus that functions as a shell to manage and execute Z80 Assembly and TI-BASIC programs`, see http://www.detachedsolutions.com/mirageos/).

This is a place dedicated to the first one, sorry I can't help :(
