### ISSUE TITLE
opam file: An extra `/` in the beginning of the path of http(s) URIs

### ISSUE THREAD

**Issue by reynir** [mirage/mirage#1563]
This introduces an extra `/` in the beginning of the path of http(s) URIs. I'll see if I can come up with a fix.

_Originally posted by @reynir in https://github.com/mirage/mirage/issues/1268#issuecomment-2385578051_

**Comment by reynir** [comment]
It's unclear how this should be fixed. As I understand a `ssh://host/path` uri is *always* an absolute path while the `user@host:path` is a relative path.

**Comment by hannesm** [comment]
oh, so I guess there's some magic involved here... and `git@github.com:` is replaced with `git+https`... may I ask what your `git remote show -n origin | grep URL` looks like? I use `git@github.com:mirage/mirage.git`...

**Comment by reynir** [comment]
Mine is the following:

```
* remote origin
  Fetch URL: https://github.com/robur-coop/qubes-miragevpn.git
  Push  URL: git@github.com:robur-coop/qubes-miragevpn.git
  HEAD branch: (not queried)
  Remote branches: (status not queried)
    ci
    dns
    fix
    main
    mirage.4.7
  Local branches configured for 'git pull':
    main       merges with remote main
    mirage.4.7 merges with remote mirage.4.7
  Local ref configured for 'git push' (status not queried):
    (matching) pushes to (matching)
```
Now how I have separate fetch and push URLs. The fetch URL (https://...) is picked in my case. I have not tested with a ssh only remote.

**Comment by hannesm** [comment]
Ah, interesting. Yes, so we should then revise the code (and make sure it works fine for both fetch & push url) -- I have the same url (with git@github.com) for both fetch & push
