### ISSUE TITLE
RFC: runtime arguments issues, next iteration

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1572]
Hey,

since 4.5.0 (released half a year ago), we had the big split between configuration time and runtime arguments. This is pretty nice.

There's still an issue, though -- let's take our hello world example. Namely how the `hello` key is introduced.

In config.ml:
```OCaml
let runtime_args = [ runtime_arg ~pos:__POS__ "Unikernel.hello" ]
let main = main ~runtime_args ~packages "Unikernel.Hello" (time @-> job)
```

in unikernel.ml:
```OCaml
let hello =
  let doc = Arg.info ~doc:"How to say hello." [ "hello" ] in
  Arg.(value & opt string "Hello World!" doc)

module Hello (Time : Mirage_time.S) = struct
  let start _time hello =
 ...
end
```

Now, when I presented this at the FunOCaml MirageOS workshop to people not exposed to MirageOS, they found it strange that the argument has to be mentioned in config.ml -- and I agree, we should have a way (maybe we already have) to only have the boot parameter in unikernel.ml.

From what I see what is generated (in main.ml):
```OCaml
let unikernel_hello__key = Mirage_runtime.register @@
# 4 "config.ml"
  Unikernel.hello
;;

...
  let _unikernel_hello = (unikernel_hello__key ()) in
  (Unikernel_hello__10.start _solo5_os_time__9 _unikernel_hello : unit io)
...
```

And I can tell that the following diff would work. Should we move the mirage-skeleton repository into such a shape (and remove the `runtime_args` argument from `Mirage.main`?

```diff
diff --git a/tutorial/hello-key/config.ml b/tutorial/hello-key/config.ml
index 78db26f..404343d 100644
--- a/tutorial/hello-key/config.ml
+++ b/tutorial/hello-key/config.ml
@@ -1,7 +1,6 @@
 (* mirage >= 4.5.0 & < 4.8.0 *)
 open Mirage
 
-let runtime_args = [ runtime_arg ~pos:__POS__ "Unikernel.hello" ]
 let packages = [ package "duration" ]
-let main = main ~runtime_args ~packages "Unikernel.Hello" (time @-> job)
+let main = main ~packages "Unikernel.Hello" (time @-> job)
 let () = register "hello-key" [ main $ default_time ]
diff --git a/tutorial/hello-key/unikernel.ml b/tutorial/hello-key/unikernel.ml
index 1722e61..cce4ff3 100644
--- a/tutorial/hello-key/unikernel.ml
+++ b/tutorial/hello-key/unikernel.ml
@@ -3,14 +3,14 @@ open Cmdliner
 
 let hello =
   let doc = Arg.info ~doc:"How to say hello." [ "hello" ] in
-  Arg.(value & opt string "Hello World!" doc)
+  Mirage_runtime.register Arg.(value & opt string "Hello World!" doc)
 
 module Hello (Time : Mirage_time.S) = struct
-  let start _time hello =
+  let start _time =
     let rec loop = function
       | 0 -> Lwt.return_unit
       | n ->
-          Logs.info (fun f -> f "%s" hello);
+          Logs.info (fun f -> f "%s" (hello ()));
           Time.sleep_ns (Duration.of_sec 1) >>= fun () -> loop (n - 1)
     in
     loop 4
```

**Comment by hannesm** [comment]
The issue I can see is that `Mirage_runtime.register` (shouldn't it be named `add_boot_param` or something?) needs to be called before `start` -- since otherwise the boot parameter won't get evaluated. I suspect we can improve the error message.

When moving it to:
```OCaml
          Logs.info (fun f -> f "%s" ((Mirage_runtime.register hello) ()));
```

Our error message is currently:
```
Fatal error: exception Invalid_argument("Functoria_runtime.Arg..get: Called too early. Please delay this call after cmdliner's evaluation.")
Raised at Lwt.Miscellaneous.poll in file "duniverse/lwt/src/core/lwt.ml", line 3123, characters 20-29
Called from Solo5_os__Main.run.aux in file "duniverse/mirage-solo5/lib/main.ml", line 46, characters 10-20
Called from Dune__exe__Main.run in file "mirage/main.ml" (inlined), line 4, characters 12-31
Called from Dune__exe__Main in file "mirage/main.ml", line 206, characters 2-7
Solo5: solo5_exit(2) called
```

**Comment by reynir** [comment]
I think I like this. It's possible to "use it wrong" but so is it with the current state (if not more so).

**Comment by hannesm** [comment]
Another observation - from the "generate less code" department: We could & should move the GC / Hashbtl / backtrace stuff away from the code generation into mirage-runtime directly. This would make the `main.ml` smaller in size. Of course there'd need to be calls to adjust the OCaml runtime once the keys are evaluated, but I think this is easily possible in mirage-runtime code (and doesn't need to be generated).
