### ISSUE TITLE
Get cohttp+vchan working across two domains

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#183]
Notes from @jonludlam on this:

> You'll need trunk ocaml-rpc, ocaml-xenstore-clients, and the 2 pull requests I've made for ocaml-vchan and for ocaml-xen-lowlevel-libs. Possibly more [...]
> To make the kernel: make/make install in xen-testvm, then mirari
> configure --xen ... etc in server
> To make the CLI: opam switch mirage-unix, make clean, make, ./setup.bin -configure --enable-cli; make

**Comment by yomimono** [comment]
@avsm please reopen if you think it's appropriate.
