### ISSUE TITLE
Port Baardskeerder to KV_RO

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#185]
The Baardskeerder API looks very straightforward to port and run under Xen.  Some notes from @cgreenhalgh on this are:

> I've got baardskeerder running in Xen/mirage over blkif.
> https://github.com/cgreenhalgh/baardskeerder/
> https://github.com/cgreenhalgh/baardskeerder/blob/master/xen_test/README.md
> I've run the bsmgr benchmark(s) to run on it, but my dev set-up is in a virtual box vm and I was using xen blktap for the vdisk
> https://github.com/cgreenhalgh/baardskeerder/blob/master/benchmark-out.txt
> I added page cacheing to the baardskeerder store over blkif but performance is still ~10 slower then direct lwt on unix, and my xen setup is currently about twice as slow again (hopefully down to the blktap disk - I couldn't get xen-disk to compile and I haven't got lvm set up at the mo).

**Comment by yomimono** [comment]
Closing this as we have a few other, more active b-trees to target.
