### ISSUE TITLE
mirage-block-unix extends the underlying block device when out of bounds

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#191]
In mirage-skeleton/basic_block, a couple of the expected failures become successes on Unix:

```
./mir-basic_block
sectors = 2048
read_write=true
sector_size=512
writing 1 sectors at 0
writing 1 sectors at 2047
writing 2 sectors at 0
writing 2 sectors at 2046
writing 12 sectors at 0
writing 12 sectors at 2036
writing 1 sectors at 2048
-- expected failure; got success
writing 12 sectors at 2037
-- expected failure; got success
reading 1 sectors at 2048
-- expected failure; got success
reading 12 sectors at 2037
-- expected failure; got success
Test sequence finished
Total tests started: 10
Total tests passed:  6
Total tests failed:  4
```

The reason is that the Unix block device extends the underlying file image if something is written out of bounds, which is probably not the behaviour we want.  It would be best to have an explicit block resize operation to match Xen and minimise surprise.

**Comment by talex5** [comment]
It looks like this was fixed: https://github.com/mirage/mirage-block-unix/releases/tag/v2.1.0

If not, a new issue should be opened on that repository.
