### ISSUE TITLE
Experiment: Raspberry Pi backend

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#192]
See: https://github.com/mrvn/raspbootin/

for a bootloader for the rPi which works well with a serial cable.

**Comment by ericbmerritt** [comment]
@avsm I am more than a bit interested in this. I wonder if you guys have made any progress? I have not been able to find much information aside from 'its coming soon'.

**Comment by samoht** [comment]
See https://github.com/dbuenzli/rpi-boot-ocaml

**Comment by yomimono** [comment]
https://mirage.io/wiki/arm64 closes this, I think.
