### ISSUE TITLE
V2 improvements:

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#203]
Keeping a list of improvements to module types in V2:

- [ ] Remove use of float in time-related operations, and switch to int64 instead.  This will make the kFreeBSD port easier and generally remove the dependency on floating point.

- [ ] Turn the stats gathering (e.g. in NETWORK) into an module type that can be included for every device.  Possible link to the RRD stats gathering daemon  (/cc @djs55)

- [ ] Checked error types (TODO: add mailing thread ref about this).

- [x] CONSOLE should satisfy FLOW (as well as log_*)

- [ ] Change non-polymorphic variant error in KV_RO into a polymorphic variant

- [ ] move error types outside of the the signatures and add 'with sexp' to every error type - add an error monad (@samoht)

- [ ] improve FS / add an Irmin module type

**Comment by yomimono** [comment]
A number of these items are being carried forward to Mirage 3.0. Closing this in favor of that issue, which is tracked at #571.
