### ISSUE TITLE
Create a `mirage-homepage` binary

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#214]
This should take a directory of static files (e.g. a Jekyll output) and output an EC2-bootable kernel (i.e. backend Xen, network DHCP and a pvgrub block device).

@djs55 notes:

> For code that can create a grub-bootable image, see
> https://github.com/jonludlam/xen-testvm/pull/7
> in particular
> https://github.com/djs55/xen-testvm/commit/1fa304b721d496597b800d41a604de692b344398

**Comment by samoht** [comment]
See https://github.com/samoht/mirage-seal (still WIP)

**Comment by samoht** [comment]
`mirage-seal` is now released. It's only for static pages, though, not for Jekyll output.

**Comment by hannesm** [comment]
we also have https://github.com/Engil/Canopy now, closing.. please reopen if there is still something missing (with a more precise description)
