### ISSUE TITLE
Hello Mirage World on Ubuntu (12.04) 32bit

### ISSUE THREAD

**Issue by buzzheavyyear** [mirage/mirage#222]
Hi
I installed and ran the unix version without problems using http://openmirage.org/wiki/hello-world, but when compiling for Xen I got the following errors - looks like X86_64 opam libraries instead of X86_32, but I'm not too sure where to find help on how to fix this.

(Also, on http://openmirage.org/community, the link for  'Mirage issue tracker' should be 'https://github.com/mirage/mirage/issues')

Best regards
Nick

                       -------- |nick@fasolt:~/mirage/mirage-skeleton/console$ make
ocamlbuild -classic-display -use-ocamlfind -pkgs lwt.syntax,mirage-console-xen,mirage-types.lwt -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -cflag -g -lflags -g,-linkpkg,-dontlink,unix main.native.o
ocamlfind ocamldep -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -modules main.ml > main.ml.depends
ocamlfind ocamldep -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -modules unikernel.ml > unikernel.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o unikernel.cmo unikernel.ml
ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o main.cmo main.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o unikernel.cmx unikernel.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o main.cmx main.ml
ocamlfind ocamlopt -g -linkpkg -dontlink unix -output-obj -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o unikernel.cmx main.cmx -o main.native.o
ld -d -nostdlib -m elf_x86_64 -T /home/nick/.opam/system/lib/mirage-xen/mirage-x86_64.lds /home/nick/.opam/system/lib/mirage-xen/x86_64.o \
	  _build/main.native.o /home/nick/.opam/system/lib/mirage-xen/libocaml.a /home/nick/.opam/system/lib/mirage-xen/libxen.a \
	  /home/nick/.opam/system/lib/mirage-xen/libxencaml.a /home/nick/.opam/system/lib/mirage-xen/libdiet.a /home/nick/.opam/system/lib/mirage-xen/libm.a /home/nick/.opam/system/lib/mirage-xen/longjmp.o -o mir-console.xen
ld: i386 architecture of input file `_build/main.native.o' is incompatible with i386:x86-64 output
_build/main.native.o: In function `caml_curry9_1_app':
(.text+0x32b): undefined reference to `caml_extra_params'
_build/main.native.o: In function `caml_curry9_1_app':
(.text+0x334): undefined reference to `caml_extra_params'
_build/main.native.o: In function `caml_curry9_1_app':
(.text+0x33d): undefined reference to `caml_extra_params'
_build/main.native.o: In function `caml_curry9_1_app':
(.text+0x36b): undefined reference to `caml_extra_params'
_build/main.native.o: In function `caml_curry9_1_app':
(.text+0x375): undefined reference to `caml_extra_params'
_build/main.native.o:(.text+0x37f): more undefined references to `caml_extra_params' follow
make: *** [build] Error 1

**Comment by samoht** [comment]
We now directly use the upstream compiler, so this issue should not be a problem anymore.
