### ISSUE TITLE
publish binary vagrant images

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#224]
See @mor1's mirage/mirage-vagrant-vms repo.

In particular, we need to review the OPAM-in-a-box image and possibly rebase off that and combine the vewee stuff.

See ocaml/opam#1035 for the opam-in-a-box repo

**Comment by samoht** [comment]
https://github.com/mattgray/mirage-xen-virtualbox works very well and should be advertised a bit more prominently.

**Comment by mor1** [comment]
agree. also https://github.com/jonludlam/packer-xenserver i believe. 

i'll spend some time today/tomorrow building the different options as i (still) need to rebuild my vbox setup anyway. what's the best place to coalesce things? there seem to be several related repos here:

+ <https://github.com/mattgray/mirage-xen-virtualbox>
+ <https://github.com/jonludlam/packer-xenserver>
+ <https://github.com/mirage/mirage-vagrant-vms>
+ <https://github.com/avsm/vagrant-opam>

**Comment by samoht** [comment]
Could create a wiki page on openmirage.org (seems to be up today, at least within the lab network)

**Comment by mor1** [comment]
happy to do that once i know what the preferred solution is (ie., which, if any, of those repos is the one to point to for all this setup-vms-possibly-on-vbox stuff)... :)

**Comment by yomimono** [comment]
Was this intended to provide development environments for producing unikernels? If so, I believe we now have sufficient Dockerfiles and Hub images to close this issue.

**Comment by avsm** [comment]
Agreed.
