### ISSUE TITLE
Use static boot config params to acquire IP address, net mask and GW for xen unikernel

### ISSUE THREAD

**Issue by julianchesterfield** [mirage/mirage#228]
Following discussion during project meeting, we need a way to bootstrap a unikernel with a static assigned IP address from the xen config. There are some parameters that may be usable:

ip=x.x.x.x
netmask=255.x.x.x
gateway=x.x.x.x

also the vif=[] parameter allows assignment of IP address in the form:

vif=['bridge=br0,vifname=974f799d,mac=DE:AD:BE:EF:02:12,ip=10.200.2.12']

Longterm we should consider supporting Cloudinit to bootstrap VM info including passwords and ssh keys etc..

With the parameters provided above the cmdline variable in xenstore is populated as:

[root@192.168.1.20 tmp]# xenstore-read /vm/73f7b83b-61df-a521-0891-9b948acc5812/image/cmdline
ip=10.200.2.10:127.0.255.255:10.200.2.254:255.255.255.0::eth0:off

First approach to get things working is to grab the xenstore key at the start point and extract IP info if it is provided.

**Comment by samoht** [comment]
Should be improved by https://github.com/mirage/mirage/pull/360 (once completed)

**Comment by samoht** [comment]
This is now done.
