### ISSUE TITLE
Xen: bind kernel cmdline to OS.Env

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#229]
We need to expose the kernel command-line from the start_info page into the OS.Env module so that libraries can use it.

Necessary to fix #228

**Comment by samoht** [comment]
See https://github.com/MagnusS/mirage-bootvar which tries to solve that problem.

**Comment by samoht** [comment]
The feature is implemented (a bit differently) in the next release of the mirage command-line tool. This is done by creating `cmdliner`-like terms used both at configure and runtime.
