### ISSUE TITLE
mirage unikernel: can crash dom0 kernel

### ISSUE THREAD

**Issue by edwintorok** [mirage/mirage#234]
I [just reported a bug on xen-devel](http://lists.xen.org/archives/html/xen-devel/2014-03/msg01719.html) about a dom0 kernel panic triggered by a simple OpenMirage unikernel:
[   87.779435] vif vif-2-0 vif2.0: Cross page boundary, txp->offset: b68, size: 1460
[   87.780570] vif vif-2-0 vif2.0: fatal error; disabling device
[   87.781403] BUG: scheduling while atomic: swapper/0/0/0x00000100
[   87.782417] bad: scheduling from the idle thread!
[...]
[   87.848080] BUG: unable to handle kernel NULL pointer dereference at   (null)

This seems to be similar to this dom0/domU bug (which is marked as fixed):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=701744#88

The testcase is based on mirage-skeleton/network:
http://www.etorok.net/xendom0bug/network.tar.gz

**Comment by samoht** [comment]
Closing as mirage/mirage-net-xen#9 has been merged
