### ISSUE TITLE
Create a library trove on the website

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#236]
We ought to maintain a list of libraries and locations on the website, since they are scattered around several organizations right now (such as mirage, xapi-project, and xen-org). Let's assemble the list on this ticket, and then I can create the webpage in one go.

Organizing by organization:

[mirage/mirage-block-volume]: Linux LVM volume reader
[mirage/mirage-block-xen]: blkfront, blkback
[mirage/mirage-block-unix]: 
[mirage/mirage-net-xen]: netfront, netback
[mirage/mirage-net-unix]:
[mirage/mirage-vchan]: vchan
[mirage/shared-memory-ring]: rings for block, net, console, xenstore
[mirage/mirage-console]:
[mirage/ocaml-fat]: FAT filesystem implementation
[mirage/xen-disk]: command-line tool for userspace blkback (thin shim over mirage-block-xen)
[mirage/ocaml-pcap]
[mirage/ocaml-cohttp]
[mirage/cowabloga]
[mirage/ocaml-uri]
[mirage/mirage-skeleton]
[mirage/mirage-www]
[mirage/mirage-decks]
[mirage/ocaml-crunch]
[mirage/ocaml-tuntap]
[mirage/mirage-platform]
[mirage/ocaml-dns]
[mirage/mirage-tcpip]
[mirage/mirage]
[mirage/ocaml-cstruct]
[mirage/io-page]
[mirage/mirage-vagrant-vms]
[mirage/ocaml-ipaddr]
[mirage/mirage-http]
[mirage/ocaml-cow]
[mirage/ocaml-xenstore]
[mirage/dyntype]
[mirage/mirage-clock]

[xapi-project/ocaml-gnt]: userspace grant table bindings
[xapi-project/ocaml-evtchn]: userspace event channel bindings
[djs55/ocaml-xenstore]: xenstore client bindings
[djs55/ocaml-mbr]: regular partition tables
[xapi-project/nbd]: simple NBD protocol implementation
[xapi-project/rrd-transport]: simple shared memory protocol for stats counters
[djs55/ocaml-tar]: parse and print .tar format data
[djs55/ocaml-vnc]: VNC protocol implementation (for consoles)
[djs55/ocaml-pcf]: parse X11 bitmap fonts

[ocamllabs/ocaml-ctypes]
[pw374/omd]

[dsheets/profuse]

**Comment by samoht** [comment]
See https://github.com/mirage/mirage-www/blob/master/TROVE
