### ISSUE TITLE
DHCPv4: what do we do with Interface_mtu

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#238]
If a DHCP server returns an `Interface_MTU` option, we currently ignore it.  If I remember correctly, Netfront doesn't really care about the MTU setting, but this may affect the backend physical device (which obviously does have a real MTU).

**Comment by yomimono** [comment]
It's possible in Mirage 3 to handle this now that the stack establishment has been reworked and @djs55 has added initial support for MTU setting at `Ethernet.connect` time.

**Comment by dinosaure** [comment]
Not sure that we should keep this issue open. It seems really old and, as far as I can tell, `charrua` handles `Interface_MTU` according to [this line](https://github.com/mirage/charrua/blob/a9501d6df2f0965f31ed9ad15329621426732b43/server/dhcp_server.ml#L528). Should we close this issue?

**Comment by hannesm** [comment]
We have over the years seen some improvements on the MTU side, but AFAICT the dhcp client does not set the interface MTU of the network stack (atm the netif has a `val mtu : t -> int`, but no way to set this value) -- and this should be addressed.

**Comment by dinosaure** [comment]
Ok, so the issue becomes more: how to set the MTU of a given device?

**Comment by haesbaert** [comment]
Virtually every system ignores a MTU offered by DHCP. I think you should drop this.

**Comment by hannesm** [comment]
@haesbaert ok, well then close this and see if there's some complaint.

**Comment by yomimono** [comment]
I think the original complaint was mine and I definitely don't care.
