### ISSUE TITLE
Tasks for getting OCaml-TLS working on Xen

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#242]
Can create subissues as appropriate. We need at least:

- [ ] get a good entropy source (dom0 /dev/random) and create frontend driver. See virtio-rng as example of interface.
- [ ] mirage-http needs DNS resolution and client implemented
- [ ] C bindings for the lightweight libgmp in mirage-platform
- [ ] C bindings for block / stream ciphers and hash algorithms
- [ ] server constructor in https://github.com/mirleft/ocaml-tls/blob/mirage/mirage/mirage_sig.ml (and associated `FLOW` module type support)

**Comment by samoht** [comment]
This seem quite outdated. Where is the issue tracking the integration of TLS on Xen?

**Comment by amirmc** [comment]
Look back at the mirage call notes. I've likely linked to it from there. mirage-dev, maybe?

Best wishes,
Amir

--
sent via mobile

**Comment by talex5** [comment]
This mirage-dev PR tracks the patches I needed to make it work: https://github.com/mirage/mirage-dev/pull/52

**Comment by hannesm** [comment]
this is done now... closing

**Comment by amirmc** [comment]
:100:
