### ISSUE TITLE
RRD logging support

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#244]
Possibly better in Irmin, but the http://github.com/xapi-project/rrd-transport provides a nice way to log streaming stats without a lot of allocation.  Possibly good for TCP stack to expose, among others.

**Comment by samoht** [comment]
we currently use RRDs to expose the GC stats on the MirageOS website: https://mirage.io/stats/gc

**Comment by hannesm** [comment]
My current take on this:
- logging: mirage uses buenzli's `logs` library.  thanks to mirage-logs, we report via the console device. additionally, logs-syslog allows for exfiltration via syslog
- monitoring: i'd appreciate snmp (udp transport, there's also snmp over tls if we want to set values).  also, there are tools available to monitor snmp in the form of rrd, prometheus, ...

moving forward:
- we need a snmp interface and implementation as a library with few dependencies
- we need to port all our libraries to use this snmp interface (exposing internal counters)
- we can then write up a monitoring unikernels story

any takers? :)

**Comment by hannesm** [comment]
added as pioneer project to http://canopy.mirage.io/Projects/snmp

**Comment by hannesm** [comment]
With https://github.com/mirage/metrics released and used, I'll close this issue. If there's demand for RRD in metrics, please open an issue there. Thanks.
