### ISSUE TITLE
mirage configure --xen && make fails on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ronys** [mirage/mirage#258]
$ mirage configure --xen && make
MIRAGE      Using the scanned config file: config.ml
MIRAGE      Compiling and dynlinking /home/ronys/git/mirage-skeleton/console/config.ml
MIRAGE      + Executing: rm -rf /home/ronys/git/mirage-skeleton/console/_build/config.*
MIRAGE      + Executing: cd /home/ronys/git/mirage-skeleton/console && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
console     CONFIGURE: /home/ronys/git/mirage-skeleton/console/config.ml
console     1 job [Unikernel.Main]
console     Installing OPAM packages.
console     + Executing: opam install --verbose --yes mirage-console-xen mirage-xen
console     + Executing: ocamlfind printconf path
console     Generating main.ml
ocamlbuild -classic-display -use-ocamlfind -pkgs lwt.syntax,mirage-console-xen,mirage-types.lwt -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -cflag -g -lflags -g,-linkpkg,-dontlink,unix main.native.o
ocamlfind ocamldep -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -modules main.ml > main.ml.depends
ocamlfind ocamldep -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -modules unikernel.ml > unikernel.ml.depends
ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o unikernel.cmo unikernel.ml
ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o main.cmo main.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o unikernel.cmx unikernel.ml
ocamlfind ocamlopt -c -g -annot -bin-annot -principal -strict-sequence -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o -o main.cmx main.ml
ocamlfind ocamlopt -g -linkpkg -dontlink unix -output-obj -package mirage-types.lwt -package mirage-console-xen -package lwt.syntax -syntax camlp4o unikernel.cmx main.cmx -o main.native.o
ld -d -nostdlib -m elf_x86_64 -T /home/ronys/.opam/system/lib/mirage-xen/mirage-x86_64.lds /home/ronys/.opam/system/lib/mirage-xen/x86_64.o \
          _build/main.native.o /home/ronys/.opam/system/lib/mirage-xen/libocaml.a /home/ronys/.opam/system/lib/mirage-xen/libxen.a \
          /home/ronys/.opam/system/lib/mirage-xen/libxencaml.a /home/ronys/.opam/system/lib/mirage-xen/libdiet.a /home/ronys/.opam/system/lib/mirage-xen/libm.a /home/ronys/.opam/system/lib/mirage-xen/longjmp.o -o mir-console.xen
**ld: error in _build/main.native.o(.eh_frame); no .eh_frame_hdr table will be created.**
Or is this to be expected?

**Comment by heidi-ann** [comment]
I got this error on cubieboard2 and it still works fine

**Comment by samoht** [comment]
Closing as even if the warning message is a bit scary, it's not an actual error.
