### ISSUE TITLE
Generate a main.ml that compiles without warnings

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#266]
Currently we get e.g.

    let t1 () =
      console1 () >>= function
      | `Error e -> fail (Failure "console1")
      | `Ok console1 ->
      stackv41 () >>= function
      | `Error e -> fail (Failure "stackv41")
      | `Ok stackv41 ->
      M1.start console1 stackv41

When compiling with warnings on, this warns about the unused `e` variables.

Ideally, it should actually report the error back to the user rather than ignoring it, though.

**Comment by hannesm** [comment]
I think this is actually done, please reopen if you find warnings..
