### ISSUE TITLE
Add flag to rebuild and run on file change

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage#269]
When I'm checking that mirage-www builds locally, and proof-reading blog posts, I constantly run the following command:
```
$ mirage clean && mirage configure --unix && mirage build && sudo mirage run
```
(and also the `ifconfig` in another terminal window).

I'm somewhat spoiled by `$ jekyll serve --watch` so it would be convenient to have something similar for unikernels.

**Comment by samoht** [comment]
I think that's not really a feature that the mirage tool should provide. It would be nice to document ways to get it though, as it is quite a useful feature when you develop a website. I've added a `doc` tag to the issue to reflect that.

**Comment by amirmc** [comment]
I agree and given my use-case, this actually belongs in Tower, the static-site generator lib.

There may well be other use-cases where a 'rebuild-on-change' might be valuable but no-one's come forward with any.  As such, I'm happy for this to be closed here.

Best wishes,
Amir

--
sent via mobile
