### ISSUE TITLE
Include cstruct.syntax by default in the generated unikernel

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#271]
Cstruct.syntax is very useful and could just be included by default in the CLI tool without breaking backwards compatibility.

**Comment by samoht** [comment]
I think we should stop using camlp4 in MirageOS, so we first need a ppx version of cstruct.syntax. See https://github.com/mirage/ocaml-cstruct/pull/59

**Comment by samoht** [comment]
Never :p
