### ISSUE TITLE
make depend does not pull down fat-filesystem

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage#275]
I just updated my travis script to include the `make depend` step but it didn't pull down `fat-filesystem`

The relevant part of the script is:
```
# run the commands to build from here
FS=fat mirage configure --$MIRAGE_BACKEND
make depend
mirage build
```
The error can be seen on my [travis log](https://travis-ci.org/amirmc/amirmc.github.com/jobs/30509271#L407) (line 407).

Explicitly adding `fat-filesystem` to the initial `opam install` step solved the problem (cf [build logs](https://travis-ci.org/amirmc/amirmc.github.com/builds/30536778)).

**Comment by samoht** [comment]
This is now fixed.
