### ISSUE TITLE
`make` should display the list of available targets (and advertise `make depend`)

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#276]
Received in my inbox:

> The hello work example is broken, I had to iterate `opam install ...` a lot of time to make it compile
> would be nice to have a big button on the website to report such trivial bugs

Seems that we are missing a `make depend` somewhere in the docs.

**Comment by hannesm** [comment]
`mirage configure` indeed calls out to opam, and `make build` is around and working, closing
