### ISSUE TITLE
Comments on Mirage website posts

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#278]
Instead of supporting Disqus, I think we should port the Real World OCaml-style comments by using Irmin as the backend this time.  This issue tracks support for this.

Limitation of no comments noted by @samoht

**Comment by yomimono** [comment]
I would like to counterpropose that we continue having no comments, and therefore no need to moderate comments, on the Mirage website.

**Comment by hannesm** [comment]
as MirageOS community, we're using discuss.ocaml.org for discussion (see https://github.com/mirage/mirage-www/pull/594).  I agree that we don't want to have on-site discussions (and moderation). closing.  if you think this is wrong, maybe submit a pioneer project to canopy :)
