### ISSUE TITLE
Async support in Mirage/Xen

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#282]
Here's a thread from the mailing list that lays out some of the steps to support Async in Mirage/Xen mode. 

> We've been making steady progress on porting Async to the Xen backend, but it's still going to > take some time to complete.  Here's the steps:
> - Lwt splits out the logical threading core (the Lwt module) and the Unix-specific execution portions (Lwt_unix).  Async needs to be restructured along similar lines, which has already begun: there is a Core_kernel that is Unix-independent and is used by our Irmin db.  There is also an Async_kernel.
> - An Async_xen needs to be written which implements the subset of Async_unix functionality necessary to drive traffic.  Async_unix is much bigger than Lwt_unix, so finding a viable subset is important (for instance, Async_unix.Reader and Async_xen.Reader need to have a similar module type, but cannot be exactly the same).
> - Frenetic needs to use Async_kernel in the OS-independent portions, instead of using Async (which packs in both Async_kernel and Async_unix).

**Comment by hannesm** [comment]
I suspect eio will happen before we manage to get async supported.
