### ISSUE TITLE
Mapping in foreign grants fails on ARM

### ISSUE THREAD

**Issue by djs55** [mirage/mirage#296]
We currently have grant mapping functions in the xen/runtime/xencaml/gnttab_stubs.c which don't work on ARM. Looking at the new mini-os, it seems to be growing APIs which look a lot like the Linux userspace versions. We should:
- [x] Add a simple loopback grant mapping test case (easier to use than a loopback disk or vif)
- [x] Modify the mirage-xen stubs to call the mini-os functions instead of the inline versions
- [x] Add an on-demand allocator to the mini-os arch/arm/mm.c

Current work-in-progress repos:

```
opam pin mirage-xen git://github.com/djs55/mirage-platform#minios-gntmap
opam pin xen-gnt git://github.com/djs55/ocaml-gnt#minios-gntmap
```

With these pinned, the new mirage-skeleton/xen/grant test passes on x86. Without these pins, it fails. It should fail with a BUG on arm:

```
unsigned long allocate_ondemand(unsigned long n, unsigned long alignment)
{
    // FIXME
    BUG();
}
```

-- this is worth checking next.

**Comment by samoht** [comment]
@djs55 ping. Do you have any plan to replace your "hacky prototype"? Seems to work fine so far :p

**Comment by djs55** [comment]
Replacing the "hacky prototype" is not on my short-term to-do list :(

Without the proper fix, we can't run blkback or netback in a VM on ARM,
since the current hack leaks all the mappings. This is probably not our
biggest problem right now :)

On Tue, Mar 17, 2015 at 12:57 AM, Thomas Gazagnaire <
notifications@github.com> wrote:

> @djs55 <https://github.com/djs55> ping. Do you have any plan to replace
> your "hacky prototype"? Seems to work fine so far :p
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/issues/296#issuecomment-82009895>.
>



-- 
Dave Scott
