### ISSUE TITLE
Add HTTP client generators to Mirage

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#331]
Right now the `mirage.mli` definitions only cover an HTTP server, but we also support HTTP clients.  See mirage/mirage-skeleton#58 for an example of what this should look like.  An extract follows:

```
module Client (C:CONSOLE) (RES:Resolver_lwt.S) (CON:Conduit_mirage.S) = struct

  module HTTP = HTTP.Make(CON)

  let http_fetch c resolver ctx =
    C.log_s c (sprintf "Fetching %s with Cohttp:" (Uri.to_string uri)) >>= fun () ->
    let ctx = { HTTP.Net_IO.resolver; ctx } in
    HTTP.Client.get ~ctx uri >>= fun (response, body) ->
    Cohttp_lwt_body.to_string body >>= fun body ->
    C.log_s c (Sexplib.Sexp.to_string_hum (Cohttp.Response.sexp_of_t response)) >>= fun () ->
    C.log_s c (sprintf "Received body length: %d" (String.length body)) >>= fun () ->
```

The HTTP client requires a Conduit and a Resolver_lwt, which were constructed via this `config.ml` fragment:

```
  let sv4 = stack default_console in
  let res_dns = resolver_dns sv4 in
  let conduit = conduit_direct sv4 in
```

**Comment by yomimono** [comment]
I think this is probably worth doing, and I don't think it would be horrifically complicated. I'll mark it as bitesize for now; if someone is interested in tackling it and wants some guidance, please feel free to contact me for that.

**Comment by haileymothershead** [comment]
Hi! My name is Hailey Mothershead and I'm a student at UT Austin. I'm currently in a virtualization class for which we have to work on an open source project. Could I get some more information on this issue?

**Comment by avsm** [comment]
Hi there @haileymothershead! The first step here is to get familiar with how to _manually_ perform a fetch of a HTTP endpoint via a unikernel.  The code is present in the Mirage skeleton example in https://github.com/mirage/mirage-skeleton/blob/master/device-usage/http-fetch/unikernel.ml

Once you get the `http-fetch` example running under Xen, the next step is to abstract it using functoria.  But as a first step, try to get the mirage-skeleton http-fetch example running on your own VM infrastructure and fetching a webpage of your choice.  Feel free to ask questions here or on discuss.ocaml.org about getting the example working, as there are quite a few moving parts involving VM and networking setup (which is good to document for your course, I would imagine!)
