### ISSUE TITLE
Fix or remove “mirage run”

### ISSUE THREAD

**Issue by Chris00** [mirage/mirage#348]
`mirage run` [does not completely work](https://github.com/mirage/mirage-www/pull/256#issuecomment-70887186).  This should be fixed or `mirage run` be removed since it is as easy to run the binaries directly.

**Comment by avsm** [comment]
I'd be inclined to remove it, as the Makefile generates the xen files too.  Opinions, @talex5 @djs55 @mor1 @samoht ?

**Comment by talex5** [comment]
Yes, remove it. I don't think it adds anything. It just makes the process appear more complicated than it is. I never use it anyway.

**Comment by samoht** [comment]
got for it

**Comment by talex5** [comment]
(what would be useful, however, would be including `Makefile.user` or similar so users can add their own rules without them being overwritten each time `mirage` is run).

**Comment by mor1** [comment]
absolutely (could've sworn i said the same thing before at some point in another venue -- perhaps it was the email list). kill it with fire by all means :)

(i agree with @talex5 suggestion for including `Makefile.user` or somesuch. fwiw when i use oasis generated `Makefile`s, i tend to find the first thing i do is edit outside the auto-gen piece to add an `-include Makefile.config` preamble and `-include Makefile.local` postamble. having similar in Mirage would be nice, as would making the rules in the generated `Makefile` extensible, ie., use `::` i believe.)

**Comment by Chris00** [comment]
>  including Makefile.user or somesuch

Another solution is to delimit the line-range where mirage writes by special comments (as, say, OASIS does).  That way, the user may add code before and/or after.  Also, if not already done, some targets like `clean` should end with double colons to be able to extend them.

**Comment by samoht** [comment]
This is now done on `master` and `mirage-www` is already online with no more mentions or `mirage run`.
