### ISSUE TITLE
remove need to pass "xvda1" to block_of_file for xen backends

### ISSUE THREAD

**Issue by heidi-ann** [mirage/mirage#349]
issue discussed at https://github.com/mirage/mirage-skeleton/pull/69#issuecomment-71226567 and https://github.com/mirage/xen-arm-builder/issues/47

**Comment by talex5** [comment]
It's not clear to me what you could do about this. The Unix file and the Xen block device genuinely have different names, so you need to give both.

The only options I can think of are:

1. Name the Unix file `xvda1` so it just happens to match. This would work for the examples (except that there's currently a bug in `mirage` preventing it - if the file exists, it converts to an absolute path, even if it's being used as a Xen device name).

2. Make a convenience function that handles both. e.g. `block ~xen:"xvda1" ~unix:"disk.img" ()`.

**Comment by samoht** [comment]
I think that has been fixed by @djs55
