### ISSUE TITLE
ARM error on boot - error: panic:  failed to mmap domU pages

### ISSUE THREAD

**Issue by heidi-ann** [mirage/mirage#354]
I seeing this issue increasingly on the cubieboard2 (ARM) and I've not sure what to do about it, normally fixed by mirage cleaning and starting again or starting again in a new directory but I can't see to get rid of it this time

```
$ sudo xl create unikernel.xl -c 
Parsing config from unikernel.xl
libxl: notice: libxl_numa.c:494:libxl__get_numa_candidate: NUMA placement failed, performance might be affected
xc: error: panic: xc_dom_boot.c:191: xc_dom_boot_domU_map: failed to mmap domU pages 0x88000+0x1 [mmap, errno=14 (Bad address)]: Internal error
libxl: error: libxl_dom.c:427:libxl__build_pv: xc_dom_build_image failed: Bad address
libxl: error: libxl_create.c:1022:domcreate_rebuild_done: cannot (re-)build domain: -3
```

**Comment by talex5** [comment]
Sounds more like a Xen problem (looks like it doesn't get as far as booting because it can't allocate the RAM for the new domain). Does `xl list` show anything still running?

(as a test, you could try booting a Linux guest and see if that works)

This looks similar:

http://lists.xen.org/archives/html/xen-devel/2014-03/msg01504.html

**Comment by heidi-ann** [comment]
sorry if this is the wrong issue tracker then

for example in one case I've already got: 
```
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0   512     2     r-----      50.5
unikernel1                                   1   256     1     -b----       0.5
```
and I want to run another unikernel, I've configured the xl to give it the new one less than 256 so its not using all the mem

**Comment by heidi-ann** [comment]
but destroying unikernel1 will let run the new unikernel

**Comment by avsm** [comment]
You're out of memory.  Drop the size of the unikernel1 to 128 or less and you should have room.

**Comment by heidi-ann** [comment]
Fixed, It seems that the cubieboard2 has about 300 mem that's unusable hence the problem :)

**Comment by talex5** [comment]
I think there's some issue with the memory needing to be contiguous or something, so it might not all be usable. Unikernels shouldn't need much anyway (16MB or so is usually fine).

**Comment by djs55** [comment]
The memory used by Xen itself is hidden from "xl list". Also things like
crash kernels are hidden (although I doubt we've got one of those). Have a
look at "xl info", in particular:

```
total_memory           : 8182
free_memory            : 11
```



On Thu, Jan 29, 2015 at 10:44 AM, Heidi-ann <notifications@github.com>
wrote:

> Fixed, It seems that the cubieboard2 has about 300 mem that's unusable
> hence the problem :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/issues/354#issuecomment-72004659>.
>



-- 
Dave Scott
