### ISSUE TITLE
Crash on startup with latest mirage-www

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#357]
Since the switch to mirage-xen-2.2.1, the Mirage-www build has been crashing on Xen 4.1.  I can't quite pin this down to a local repro case, so could anyone with a Xen box handy try to boot this kernel:

https://github.com/mirage/mirage-www-deployment/tree/master/xen/bf43f36e2f0a9428263439c627566878a1c811d2

If it crashes or succeeds on boot, it would be useful to know. 
```
Unsupported function lseek called in Mini-OS kernel
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(TMPDIR) -> null
getenv(TEMP) -> null
Page fault at linear address 28, rip 1dce4e, regs 000000000088fd38, sp 88fde0, our_sp 000000000088fce8, code 0
Page fault in pagetable walk (access to invalid memory?).
```

This doesn't happen for me on Xen 4.4

**Comment by talex5** [comment]
Crashes for me on Xen 4.4 (under VirtualBox):

    Page fault at linear address 28, rip 1dce4e, regs 000000000088fd38, sp 88fde0, our_sp 000000000088fce8, code 0
    Page fault in pagetable walk (access to invalid memory?).

**Comment by yomimono** [comment]
Xen 4.4 (specifically, 4.4.1-0ubuntu0.14.04.3):

```
Page fault at linear address 28, rip 1dce4e, regs 000000000088fd38, sp 88fde0, our_sp 000000000088fce8, code 0
Page fault in pagetable walk (access to invalid memory?).
```

**Comment by avsm** [comment]
It seems to be fixed by deletes some of the crunch files.  I wonder if we've forgotten a linker script somewhere

**Comment by avsm** [comment]
Works on 

```
getenv(PATH) -> null
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(TMPDIR) -> null
getenv(TEMP) -> null
Netif: add resume hook
getenv(DEBUG) -> null
getenv(OMD_DEBUG) -> null
getenv(OMD_FIX) -> null
Netif.connect 0
Netfront.create: id=0 domid=0
MAC: c0:ff:ee:c0:ff:ee
Manager: connect
Attempt to open(/dev/urandom)!
Manager: configuring
DHCP: start discovery
```

(XEN) Xen version 4.4.1 (Ubuntu 4.4.1-0ubuntu0.14.04.2)

**Comment by talex5** [comment]
I suspect this may be the cause of the "pagetable walk" error (in Mini-OS traps.c):

    void dump_regs(struct pt_regs *regs)
    {
        printk("Thread: %s\n", current->name);

Maybe try with `if (current != NULL)` in there?

**Comment by avsm** [comment]
I can only get it to crash on a deployment server that can't rebuild it, annoyingly :) If you have a crashing box with a dev environment and can trace it down, that would be most helpful...

**Comment by djs55** [comment]
It crashes for me on Xen-4.4.

On Fri, Jan 30, 2015 at 10:35 AM, Anil Madhavapeddy <
notifications@github.com> wrote:

> I can only get it to crash on a deployment server that can't rebuild it,
> annoyingly :) If you have a crashing box with a dev environment and can
> trace it down, that would be most helpful...
>
> > On 30 Jan 2015, at 10:33, Thomas Leonard <notifications@github.com>
> wrote:
> >
> > I suspect this may be the cause of the "pagetable walk" error (in
> Mini-OS traps.c):
> >
> > void dump_regs(struct pt_regs *regs)
> > {
> > printk("Thread: %s\n", current->name);
> > Maybe try with if (current != NULL) in there?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/mirage/mirage/issues/357#issuecomment-72182226>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/issues/357#issuecomment-72182416>.
>



-- 
Dave Scott

**Comment by avsm** [comment]
A delicious bar of chocolate to the person who finds the bug...

**Comment by talex5** [comment]
When I build it myself, it doesn't crash. However, I've pushed the error reporting fix to Mini-OS here, so you should be able to build one that gives a register and stack dump at least: https://github.com/talex5/xen/commits/devel

**Comment by koleini** [comment]
netif-forward in mirage-skeleton also crashes since switching to mirage-xen-2.2.1.

It doesn't crash if instead of 2 vifs in xen config, 3 vifs are defined, and the name of the first vif has to be alphanumeric (I was using numeric names before!)

**Comment by mor1** [comment]
@koleini that looks like it might be a separate error so worth creating a separate issue, with as much context as you have (pointer to test code, details of setup, xen console output, etc).

re this issue -- fwiw, hit the same error when trying to start the tutorial or decks unikernel for deployment on punk.

```
mir-tutoriald@punk:~/mirage-tutorial-deployment/xen/663ac0c425b97036de9beca5c0737ef81fdd44d5$ sudo xm create -pc xm.conf
Using config file "./xm.conf".
Started domain mir-tutorial (id=89)
Xen Minimal OS!
  start_info: 00000000006c3000(VA)
    nr_pages: 0x10000
  shared_inf: 0xd5f7a000(MA)
     pt_base: 00000000006c6000(VA)
nr_pt_frames: 0x7
    mfn_list: 0000000000643000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line:
       stack: 0000000000622b80-0000000000642b80
MM: Init
      _text: 0000000000000000(VA)
     _etext: 00000000001ca31f(VA)
   _erodata: 0000000000219000(VA)
     _edata: 00000000005ccb00(VA)
stack start: 0000000000622b80(VA)
       _end: 0000000000642b80(VA)
  start_pfn: 6d0
    max_pfn: 10000
Mapping memory range 0x800000 - 0x10000000
setting 0000000000000000-0000000000219000 readonly
skipped 1000
MM: Initialise page allocator for 74c000(74c000)-10000000(10000000)
MM: done
Demand map pfns at 10001000-0000002010001000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0000000010001000.
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(PATH) -> null
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(TMPDIR) -> null
getenv(TEMP) -> null
Page fault at linear address 7f0adc895728, rip 1a6d33, regs 000000000063fd78, sp 63fe20, our_sp 000000000063fd28, code 0
Page fault in pagetable walk (access to invalid memory?).
```

and 

```
mir-decksd@punk:~/mirage-decks-deployment/xen/223466f6ed9243253d5671c2922cc7f11a98a7e9$ sudo xm create -pc xm.conf
Using config file "./xm.conf".
Started domain mir-decks (id=91)
Xen Minimal OS!
  start_info: 00000000014a7000(VA)
    nr_pages: 0x10000
  shared_inf: 0x80c4c000(MA)
     pt_base: 00000000014aa000(VA)
nr_pt_frames: 0xf
    mfn_list: 0000000001427000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line:
       stack: 0000000001406dc0-0000000001426dc0
MM: Init
      _text: 0000000000000000(VA)
     _etext: 00000000002363cf(VA)
   _erodata: 0000000000287000(VA)
     _edata: 00000000013a6f20(VA)
stack start: 0000000001406dc0(VA)
       _end: 0000000001426dc0(VA)
  start_pfn: 14bc
    max_pfn: 10000
Mapping memory range 0x1800000 - 0x10000000
setting 0000000000000000-0000000000287000 readonly
skipped 1000
MM: Initialise page allocator for 1530000(1530000)-10000000(10000000)
MM: done
Demand map pfns at 10001000-0000002010001000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0000000010001000.
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(PATH) -> null
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
Unsupported function lseek called in Mini-OS kernel
getenv(OCAMLRUNPARAM) -> null
getenv(CAMLRUNPARAM) -> null
getenv(TMPDIR) -> null
getenv(TEMP) -> null
Page fault at linear address 7fc7f77c5728, rip 212de3, regs 000000000141fd78, sp 141fe20, our_sp 000000000141fd28, code 0
Page fault in pagetable walk (access to invalid memory?).
```

**Comment by talex5** [comment]
The bad version (compiled in an Ubuntu 12.04 docker container with the Travis script) looks like this:

    00000000001c8aab <caml_format_int>:
      1c8aab:	53                   	push   %rbx
      1c8aac:	48 83 ec 30          	sub    $0x30,%rsp
      1c8ab0:	48 89 f3             	mov    %rsi,%rbx
      1c8ab3:	64 48 8b 04 25 28 00 	mov    %fs:0x28,%rax		; <<<< stack protector?
      1c8aba:	00 00 
      1c8abc:	48 89 44 24 28       	mov    %rax,0x28(%rsp)
      1c8ac1:	31 c0                	xor    %eax,%eax
      1c8ac3:	48 89 e2             	mov    %rsp,%rdx
      1c8ac6:	be db 6d 1f 00       	mov    $0x1f6ddb,%esi
      1c8acb:	e8 b4 fe ff ff       	callq  1c8984 <parse_format>

The good version (compiled on my Arch Linux system natively) looks like this:

    00000000001e20f3 <caml_format_int>:
      1e20f3:	55                   	push   %rbp
      1e20f4:	53                   	push   %rbx
      1e20f5:	48 83 ec 58          	sub    $0x58,%rsp
      1e20f9:	48 89 f5             	mov    %rsi,%rbp
      1e20fc:	4c 8d 44 24 0f       	lea    0xf(%rsp),%r8
      1e2101:	48 8d 4c 24 10       	lea    0x10(%rsp),%rcx
      1e2106:	48 8d 54 24 30       	lea    0x30(%rsp),%rdx
      1e210b:	be eb 36 21 00       	mov    $0x2136eb,%esi
      1e2110:	e8 71 fd ff ff       	callq  1e1e86 <parse_format>

**Comment by talex5** [comment]
Here's the problem:

    # This extra flag only needed for gcc 4.8+
    GCC_MVER2=`gcc -dumpversion | cut -f2 -d.`
    if [ $GCC_MVER2 -ge 8 ]; then
      EXTRA_CFLAGS="-fno-tree-loop-distribute-patterns -fno-stack-protector"
    else
      echo $GCC_MVER2
      exit 1
    fi

But on Ubuntu 12.04 (used by Travis), gcc is only 4.6:

    # gcc --version
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

`-fno-stack-protector` should be used on older versions too.

**Comment by avsm** [comment]
Confirmed at https://wiki.ubuntu.com/Security/Features.  We could also just put in the stack smash stub (which I thought we already had), but restoring a non-crashing version first would be good.

**Comment by talex5** [comment]
This should fix it:

    opam pin add mirage-xen-minios 'https://github.com/talex5/mirage-xen-minios.git#b0.6'

**Comment by avsm** [comment]
That doesnt work out of the box since a mirage-xen-minios pin needs the tarballs included in the distfile as well, annoyingly...

**Comment by talex5** [comment]
Doesn't it download them automatically if they're missing?

**Comment by avsm** [comment]
dont believe the opam package does

**Comment by talex5** [comment]
The one on opam-repository doesn't, but the opam file in the Git repo does, and Travis is using opam 1.2 so it should use that.

**Comment by avsm** [comment]
thats useful!

**Comment by avsm** [comment]
Released in opam, and website updating again.  Thanks all!
