### ISSUE TITLE
Create a mirage-flow package

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#368]
Would be nice to have flow transformers available in mirage (with bits of to `Lwt_io` in it) in a separate `mirage-flow` package.

Exemple of code related to this:
- https://github.com/mirage/ocaml-vchan/blob/master/lwt/vchan_lwt_unix.ml#L126 tranforms a `FLOW.flow` into a `Lwt_io.channel`. Could be made available under an `mirage-flow.unix` package.
- Some unreleased code that I'm writing for `ocaml-git` is implementing something similar to `Lwt_io.make`. This will be in a functor parametrised by a  `FLOW`.

**Comment by avsm** [comment]
Absolutely.

**Comment by samoht** [comment]
See https://github.com/mirage/mirage-flow

Can create flows from and to strings and cstruct buffers. Plan is to add `Lwt_io.channel` convert function from Dave as well in a sub `lwt` library as well.

**Comment by samoht** [comment]
Closing as mirage-flow 1.0 is soon to be released: https://github.com/ocaml/opam-repository/pull/3622

Improvements are still very welcome.

**Comment by avsm** [comment]
dont forget to add to mirage-www TROVE file when released..

**Comment by samoht** [comment]
https://github.com/mirage/mirage-www/pull/291
