### ISSUE TITLE
Move website to a proper hosting provider

### ISSUE THREAD

**Issue by haf** [mirage/mirage#371]
http://openmirage.org/

**Comment by amirmc** [comment]
Thanks for the report!

@avsm @mor1 is this known? I merged my PRs yesterday eve and CI passed.  

Best wishes,
Amir

--
sent via mobile

**Comment by avsm** [comment]
The site is on a rather unreliable Cambridge Computer Lab host right now. I've edited the title to leave this open until we migrate it to a proper host.

**Comment by samoht** [comment]
The website is down again

**Comment by amirmc** [comment]
Is it just the host or are we actually seeing a different issue here?  Also, is @avsm the only one who has access to it?

**Comment by mor1** [comment]
I've no access that I know of. @avsm is the only one afaik.

Is there a reason not to simply host this on punk along with `decks` and `tutorial`?

**Comment by avsm** [comment]
It's restarted on cron now, but I'm more concerned with why it's going down.  Running httperf against mir-www to ensure we dont have a subtle leak would be useful.

**Comment by amirmc** [comment]
> ... but I'm more concerned with why it's going down. 

Indeed. As we've discussed before, the website is the canary for the end-to-end/complete-system stuff. If it's going down unexpectedly, we should look into it. 

> Running httperf against mir-www to ensure we dont have a subtle leak would be useful.

Is this something @yomimono can help with?

Best wishes,
Amir

--
sent via mobile

**Comment by samoht** [comment]
down again. @avsm can we have a console output, and `xl list` to see what state the VM is in? Would be helpful to help debugging the issue.

**Comment by yomimono** [comment]
I've discovered a resource leak in the channel code provided by mirage-tcpip (used by mirage-http for interfacing with cohttp).  Without the fixes in https://github.com/yomimono/mirage-tcpip/tree/test_channel , a unikernel serving mir-www with 64MB of memory will crash reliably after a couple thousand sequential reads; when built with the fixes there, it'll stay up for at least ~1.5M requests.  A PR for mirage-tcpip is forthcoming once I have a cleaner fix.

**Comment by avsm** [comment]
awesome!  The fixes look very good to me.  In the medium term, I'd like to rewrite Channel using `Rresult` so that we have nice combinators instead of exceptions for the low-level errors.

**Comment by haf** [comment]
Your site is down again.

**Comment by avsm** [comment]
It's back -- finally tracked down the issue in #396!

**Comment by samoht** [comment]
The website is not hosted at the computer lab anymore, so closing.
