### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#381]
See http://lists.xenproject.org/archives/html/mirageos-devel/2015-01/msg00143.html

Tasks:

- [ ] add `val pp_error: Format.formatter -> error -> unit` in both `V1.FLOW` and `V1.DEVICE`
- [ ] mirage-console
- [ ] mirage-entropy-unix
- [ ] mirage-net-macosx
- [ ] mirage-net-unix
- [ ] vchan

**Comment by hannesm** [comment]
`pp_error` should return a `string` (as described [here](https://github.com/mirage/mirage-www/pull/274/files#diff-abb8c0c60c75065f86ff29942a483ec4R254))!?

**Comment by samoht** [comment]
You want to use it with `Format.printf "error is %a" pp_error e` so the should be `unit` (there's a typo on the page)

**Comment by hannesm** [comment]
yes, discovered, thought, and deleted my comment..

**Comment by Drup** [comment]
Bumping that one, it would make the connect code nicer and I would prefer to do it while I'm shuffling everything.

**Comment by talex5** [comment]
Some related fixes for the error reporting are tracked in https://github.com/mirage/mirage-dev/pull/107

**Comment by hannesm** [comment]
for connect we have nicer errors now (and code even got simpler!!!) -- for normal operations i suspect we still could use some normal result types and pretty printers...

**Comment by hannesm** [comment]
#615 is in, more to come... closing this outdated issue
