### ISSUE TITLE
Deprecate libraries

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#384]
- [ ] https://github.com/mirage/mirage-http-xen (https://github.com/mirage/mirage-http-xen/issues/3)
- [ ] https://github.com/mirage/io-page (https://github.com/mirage/io-page/issues/19)
- [ ] https://github.com/mirage/mirage-types
- [x] https://github.com/mirage/mirari

**Comment by hannesm** [comment]
`mirage/mirage-types` and `mirage/mirari` are certainly superseeded (and could well life in another organisation)..

**Comment by amirmc** [comment]
Yup, we have https://github.com/ocaml-attic for that … though I'd forgotten about it and also recently got mirage-attic too.

**Comment by samoht** [comment]
I moved mirari to ocaml-attic and then I saw that they are a lot of very lively projects in that organisation so I'm not sure anymore.

@avsm what do you think?

**Comment by amirmc** [comment]
I don't see what's lively in there.  There appear to be some forks of repos from the Mirage org but even those haven't been updated in almost a year (the upstream repos are still active).

**Comment by samoht** [comment]
Having fork of active repos in there is weird.

**Comment by dbuenzli** [comment]
Yes.

**Comment by avsm** [comment]
> Having fork of active repos in there is weird.

They can be deleted if you want.  They're there because we did the 3-way repo transfer to get the fork roots correct, but are no longer needed.

**Comment by amirmc** [comment]
I agree and I wonder if it's an artefact of how we/GitHub used to transfer repos (make a fork and then kinda switch the pointers around).  I don't see much harm in leaving them there nor in getting rid of them (all the history should be on the other repo anyway).  Nobody has any reason to be looking at ocaml-attic.

**Comment by hannesm** [comment]
could someone with sufficient permissions move the inactive mirage-http-xen and mirage-types repository from the mirage organisation to ocaml-attic, please?  I guess we leave io-page as is for now.

**Comment by avsm** [comment]
Both mirage-http-xen and mirage-types have now been moved to the ocaml-attic org. Redirects are in place so the old urls work.

**Comment by hannesm** [comment]
closing. remaining library is io-page, which has its own issue about that and different opinions whether it should be integrated into cstruct or not.
