### ISSUE TITLE
Add package version constraints

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#392]
Now that we only support opam `1.2`, we can use the syntax `<package><relop><version>` (where relop is `=`, `<=`, `>=`, ...) on the command-line to express package version constraints. We should start using it in the tool, to ensure that the right version are present at configuration time. Not sure we can have `&&` constraints, need to check with @AltGr.

Note: I think we want to keep the up-constraint opened so that we don't have to release a new version of the tool for each library release. So we would update the version constraints only when we have incompatible API changes in the library.  Which should be fine if we always have the latest version of the tool installed and running. So we might need to add additional checks in the mirage tool to check that it is up-to-date (by calling `opam list mirage`?).

**Comment by hannesm** [comment]
related to #499

**Comment by AltGr** [comment]
You can't have such constraints, but e.g. `opam install 'foo>=3' 'foo<4' would work.
For more complex constraints, you'll need to pin+edit a package with the appropriate `depends:` field, or use `switch import`.

**Comment by Drup** [comment]
IIRC, this is already supported on the functoria side, in the `package` field, so it just needs to update `mirage.ml`.

**Comment by samoht** [comment]
On a related note, @Drup do you think adding a `val pkg: ?opam:string -> ?ocamfind:string -> unit` combinator would make sense?

**Comment by Drup** [comment]
Hum, that would be an incompatible change, isn't it ? It clearly makes more sense, but ultimately, it wouldn't change much. In most cases, the opam and ocamlfind information should be bundled inside the configurable that needs them.

**Comment by hannesm** [comment]
I do appreciat this issue, and solved it in https://github.com/mirage/functoria/pull/82.  I will close this issue, and hope discussion will happen over in the actual PR.
