### ISSUE TITLE
Cryptic tun/tap network error message 

### ISSUE THREAD

**Issue by robertream** [mirage/mirage#395]
When I managed to get one of the network samples building, for example "ping", I couldn't get the unikernel running locally with a tun/tap device I created. Even though I use tapctl to create a tap0 device owned by my user account, just like the tutorial advises, when I go to execute the unikernel I still get this error:

Fatal error: exception Failure("net_tap0")
Raised at file "src/core/lwt.ml", line 788, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 47, characters 2-28

It turned out I needed to run with elevated privileges, but the error message could be far less cryptic, and/or the documentation for tun/tap could at least warn about possibly needing elevated privileges.

**Comment by talex5** [comment]
It seems that you no longer need privileges, as long as the device is up. e.g.

    sudo ip tuntap add dev tap0 mode tap user $USER
    sudo ip link set dev tap0 up
    ./mir-network

(better error reporting would certainly be nice though - see #381)

**Comment by talex5** [comment]
Improved error reporting is now tracked here https://github.com/mirage/mirage-dev/pull/107

(see http://canopy.mirage.io/Posts/Errors for details)

**Comment by hannesm** [comment]
closing this issue, error handling has now improved on git master, a release will be soon there.
