### ISSUE TITLE
Improve the Channel API

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#399]
- [x] create a separate project to host `mirage-tcpip/channel`
- [ ] remove API inconsistencies (see https://github.com/mirage/mirage-dev/pull/69#issuecomment-99161560)

> from @talex5: I wonder if we should track these problems in case they indicate a bad API. In the channel API's read_until it seems that there are three outcomes:
> 
> The character is found and the string up to there is returned (true, result)
> The character is not found yet, but there will be more input later, so check again (false, nonempty_buf)
> The character will never be found, so give up (false, empty_buf)
> Perhaps we should represent this with three variants? (e.g. Found of buffer | Cont of buffer | End_of_file) Although that does introduce an "impossible" result of (Cont empty_buffer).

**Comment by samoht** [comment]
I've ticked the first box: https://github.com/mirage/mirage-channel I'm preparing a release.

**Comment by hannesm** [comment]
hmm, wouldn't you want to preserve its history? (by using `git filter-branch --subdirectory-filter channel` for import?)

**Comment by samoht** [comment]
yea, I was lazy. This is now fixed: https://github.com/mirage/mirage-channel/commits/master

**Comment by avsm** [comment]
There appear to be no consumers of Channel.read_until, so I am removing it in an ongoing PR

**Comment by avsm** [comment]
No external consumers.... but Channel.read_line uses it.

**Comment by hannesm** [comment]
this is done now, isn't it? @avsm

**Comment by hannesm** [comment]
fixed in #702 AFAICS
