### ISSUE TITLE
nocrypto.lwt module not found. Hint: reinstall nocrypto

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#404]
My Travis build keeps giving this error on `mirage configure`. `nocrypto.lwt` is already installed according to `ocamlfind list`.

Output log:

https://travis-ci.org/talex5/cuekeeper/builds/63296241

Extract:

    +ocamlfind list
    [...]
    nocrypto            (version: 0.4.0)
    nocrypto.lwt        (version: 0.4.0)
    [...]
    (cd server && mirage configure --no-depext && make)
    Mirage      Using scanned config file: config.ml
    Mirage      Compiling for target: Unix
    Mirage      Processing: /home/travis/build/talex5/cuekeeper/server/config.ml
    Mirage      => rm -rf /home/travis/build/talex5/cuekeeper/server/_build/config.*
    Mirage      => cd /home/travis/build/talex5/cuekeeper/server && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
    cuekeeper   Using configuration: /home/travis/build/talex5/cuekeeper/server/config.ml
    cuekeeper   1 job [Unikernel.Main]
    cuekeeper   Installing OPAM packages.
    cuekeeper   => opam --version
    cuekeeper   => opam install --yes crunch cstruct io-page irmin lwt mirage-clock-unix mirage-console mirage-http mirage-types mirage-unix nocrypto>=0.4 tcpip tls
    [NOTE] Package crunch is already installed (current version is 1.4.0).
    [NOTE] Package cstruct is already installed (current version is 1.6.0).
    [NOTE] Package io-page is already installed (current version is 1.5.1).
    [NOTE] Package irmin is already installed (current version is 0.9.4).
    [NOTE] Package lwt is already installed (current version is 2.4.8).
    [NOTE] Package mirage-types is already installed (current version is 2.3.0).
    [NOTE] Package nocrypto is already installed (current version is 0.4.0).
    cuekeeper   => ocamlfind query -format '%p'  -recursive cstruct io-page io-page.unix irmin.mem lwt mirage-clock-unix mirage-console.unix mirage-http mirage-types mirage-types.lwt tcpip.stack-socket tls.mirage
    cuekeeper   Generating: main.mlocamlfind: Package `nocrypto.lwt' not found
    [ERROR]      nocrypto.lwt module not found. Hint: reinstall nocrypto.

**Comment by samoht** [comment]
Hum this is not supposed to happen... @pqwy any idea?

**Comment by talex5** [comment]
Testing in a container locally, I see that `nocrypto` got downgraded to 0.3.1 at some point. But `mirage` reported `Package nocrypto is already installed (current version is 0.4.0).` just before the error. Could it have silently downgraded nocrypto between that message and the error??

It's especially odd given that my `config.ml` contains an explicit:
`~packages:[...; "nocrypto>=0.4"]`

**Comment by samoht** [comment]
which opam version do you have?

**Comment by samoht** [comment]
but that's maybe a matter of marking `mirage 2.5.0` in conflict with older version of nocrypto.

**Comment by talex5** [comment]
Travis is using opam 1.2.2 (via 0install).

**Comment by talex5** [comment]
Hmm... I see there's a new file in my source directory called `=0.4` which contains:

    =-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [irmin: git] Command started
    [irmin: git] Command started
    [irmin: git] Command started
    [irmin: git] Command started
    [irmin] https://github.com/talex5/irmin.git#hack-slice already up-to-date
    The following actions will be performed:
      - install   asn1-combinators   0.1.2                          [required by x509]
      - install   xenstore           1.2.5                          [required by mirage-console]
      - downgrade nocrypto           0.4.0 to 0.3.1
      - install   mirage-profile     0.4                            [required by mirage-unix, tcpip]
      - install   mirage-types-lwt   2.3.0                          [required by mirage-http, mirage-console, tls]
      - install   tuntap             1.0.0                          [required by mirage-net-unix]
      - install   mirage-clock-unix  1.0.0
      - install   xenstore_transport 0.9.4                          [required by mirage-console]
      - install   x509               0.3.1                          [required by tls]
      - install   shared-memory-ring 1.1.1                          [required by mirage-console, mirage-unix]
      - install   mirage-net-unix    2.2.0                          [required by tcpip]
      - install   vchan              2.0.2                          [required by mirage-conduit]
      - install   tls                0.4.0
      - install   mirage-unix        2.3.1
      - install   mirage-console     2.1.3
      - install   tcpip              2.4.3
      - install   dns                0.15.0                         [required by mirage-dns]
      - install   mirage-dns         2.0.0                          [required by mirage-conduit]
      - recompile conduit            0.8.2                          [uses tls]
      - install   mirage-conduit     2.1.0                          [required by mirage-http]
      - recompile cohttp             0.17.1                         [uses conduit]
      - install   mirage-http        2.2.0
      - recompile irmin              0.9.4*
      - recompile my-package         dev*                           [uses irmin]
    ===== 19 to install | 4 to recompile | 1 to downgrade =====

Why doesn't opam give a reason with `downgrade` lines?

**Comment by talex5** [comment]
Ah, looks like conduit 0.8.2 conflicts with the new tls and 0.8.3 isn't in opam yet.

**Comment by samoht** [comment]
Should be fixed now
