### ISSUE TITLE
Avoid calling camlp4 as much as possible.

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#405]
This make ARM builds very slow and should be avoided as much as possible. Currently we only avoid compiling static files with it, but the current mechanism is unreliable and too limited. We should extend that.

**Comment by Drup** [comment]
Is camlp4 needed at all ? It doesn't seem very beneficial in `config.ml` scripts.

**Comment by samoht** [comment]
we use to support the lwt syntax extension by default but not anymore. I think it's fine to just remove the camlp4 support completely.

**Comment by Drup** [comment]
Pretty sure the lwt syntax is still loaded at the moment: https://github.com/mirage/mirage/blob/master/lib/mirage.ml#L2347

But if we can drop it, fine by me. :)

**Comment by samoht** [comment]
> by default but not anymore

what I meant is that we do not advertise the lwt syntax in the docs anymore so it should be fine to drop it. Would check that `mirage-skeleton` still compiles fine without it, but I'm in favour of dropping the support.

**Comment by samoht** [comment]
I think we should fix that one before the release.

**Comment by samoht** [comment]
Fixed by #510
