### ISSUE TITLE
mirage tool initialises network stack multiple times

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#414]
If you ask for e.g. a conduit and a resolver on top of a single stackv4 in your `config.ml` then mirage generates a `main.ml` that runs two stacks on the same interface (which causes problems, since they're both fighting over the incoming packets). Example:

https://github.com/lcoviedo/mirage-http-fetch/blob/bff1eccbfd05279976ebd4cf265e24f2dccab951/config.ml

http://lists.xenproject.org/archives/html/mirageos-devel/2015-06/msg00009.html

**Comment by samoht** [comment]
The new version of conduit should avoid this specific error, but the problem still remains in the general case: we don't have (yet) a good way to express sharing between components in the mirage DSL.

**Comment by samoht** [comment]
I think this is now solved (/cc @Drup)
