### ISSUE TITLE
Add an option to not generate the fat file

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#423]
Sometimes you already know what device you want to mount and you don't need to generate a `make-fat*-image.sh`.

**Comment by juliahoang** [comment]
hi @samoht , I'm a student from UT Austin. I am taking a virtualization class that requires us to work on an open source project, so I was wondering if you are still looking for people to contribute to this. If so, can I get more information on this issue? Thank you very much!

**Comment by hannesm** [comment]
Closing since #1353 just removes that fat magic.
