### ISSUE TITLE
mirage should not uninstall itself after calling opam

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#438]
The tool should specify `mirage.<current-version>` in the package to install. Could make pinning a bit more difficult if not done correctly.

**Comment by avsm** [comment]
I'm not sure I like this idea.  It would be nicer if OPAM itself had a concept of roots, rather than the tool force installing itself...

**Comment by dbuenzli** [comment]
> It would be nicer if OPAM itself had a concept of roots,

What do you mean by that ? if you mean a root is something that was explicitely installed rather than installed resulting from a dependency resolution then I think `opam` already has the concept. Do an `opam list` and watch out for these underlined packages.

**Comment by dbuenzli** [comment]
Or an `opam list --installed-roots`.

**Comment by avsm** [comment]
Right -- I'm wondering why this issue arose in the first place.  In the normal course of events it should never happen, so presumably it's because of a failed source build causing the user to ctrl-c and preventing the mirage package from being recompiled correctly.

**Comment by samoht** [comment]
The solver sometimes decide that the mirage tool needs to be updated or downgraded (solvers have their own reasons than humans do not know).

**Comment by Drup** [comment]
Does it even happen with non-internal solvers in practice ?

**Comment by avsm** [comment]
Mirage is recompiled if the depopts for Lwt change, for example.

**Comment by Drup** [comment]
I know, I meant the change of version.

**Comment by Drup** [comment]
(Note: mirage doesn't depend on lwt anymore, the code generated by mirage does)

**Comment by avsm** [comment]
I've not seen the change of version happen in practise since the solver argument tweaks in OPAM 1.2.2

**Comment by Drup** [comment]
I think we can close then. The new version depends on `mirage` explicitely, without version bound, but that should be enough.

**Comment by samoht** [comment]
If we can put the version number in there that'd be extra cool. I think not having a version number is ok too, though (it's better than having nothing :p)
