### ISSUE TITLE
Improve the Xen deployment model

### ISSUE THREAD

**Issue by djs55** [mirage/mirage#443]
Following on from this thread: http://lists.xenproject.org/archives/html/mirageos-devel/2015-08/msg00046.html we should
- [ ] start checking in the .xl skeleton files to deployment repos as part of the build
- [ ] modify the deployment scripts to replace the `@VARIABLES@` in the .xl skeleton files to point to local resources (e.g. network bridge names)

At this point it will be easy to do things like build an HVM-bootable kernel without having to change the deployment scripts to match.
- [ ] start checking in the data as binary blobs to deployment repos as part of the build
- [ ] modify the deployment scripts to replace the `@DISK@` in the .xl skeleton file to point to the local binary blob

At this point we could reduce the amount of RAM assigned to each deployed unikernel as it won't have to pre-load all data files into memory. It's still the case that the data is stored inefficiently, only now rather than being inside the kernel image it's in a second file.
- [ ] start checking in the data as a sub-tree within the deployment repo's filesystem
- [ ] write a `mirage-deploy-xl` script which knows how to build a `tar`-format binary blob given a tree of files in the git repo, and substitute the variables in the .xl skeleton file to match
- [ ] modify the deployment scripts to use `mirage-deploy-xl`

At this point the commits to the deployment repo should be deduped (the data files anyway) and we can do more stuff afterwards, such as switch to `git clone` or use NFS/9p, either at unikernel startup time or at `mirage-deploy-xl`-time.

**Comment by yomimono** [comment]
These items are very specific to Xen.  Are they still relevant, and if so how should we update them?

**Comment by hannesm** [comment]
Since this has seen years of inactivity, I'll close it. The deployment model of MirageOS on Xen (esp. qubes-firewall) has improved quite a lot. On hvt and spt, we have e.g. systemd scripts and albatross.
