### ISSUE TITLE
`get_extra_ld_flags` filter argument is unused

### ISSUE THREAD

**Issue by Drup** [mirage/mirage#445]
See [here](https://github.com/mirage/mirage/blob/8f441498c61188720765a5bf5c7a7516c60a6b2a/lib/mirage.ml#L2400-L2414). The argument is unused in the function but is called [here](https://github.com/mirage/mirage/blob/8f441498c61188720765a5bf5c7a7516c60a6b2a/lib/mirage.ml#L2480-L2484).

What should it do ? 

#HeyIEnabledTheWarnings

**Comment by talex5** [comment]
Good idea turning the warnings on :-)

We used to include all C stubs, with a hack to remove some we didn't need. Now, we only include stubs that the package explicitly says are compiled for Xen. So, filter can be removed now.
