### ISSUE TITLE
Extract mirage scripts in independent libraries

### ISSUE THREAD

**Issue by Drup** [mirage/mirage#446]
This is to track the two points raised in #441. 

It would be very nice to extract those scripts:
- [ ] script to create fat blocks
- [ ] scripts to produce the xen files

**Comment by samoht** [comment]
@djs55 apparently you are assigned to that task :p

**Comment by djs55** [comment]
Yup .. I haven't forgotten! Making a lib to generate and parse .xl is on my
to-do list ;) (same for fat stuff)

**Comment by hannesm** [comment]
I'll close since they're in separate modules now, and may one day just vanish.
