### ISSUE TITLE
Functoria release aka Mirage 2.7.0

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#447]
Release list [no owner for the items yet]:

- [x] decide if we keep support for `--xen` and `--unix` or not
- [x] new release of cmdliner with environment variables
- [x] make a PR with draft of the blog post and gather comments https://github.com/mirage/mirage-www/pull/396
- [x] re-add [platform auto-detection](https://github.com/mirage/mirage/blob/master/lib/main.ml#L60-L75) to distinguish between unix and osx
- [x] review functoria, clean-up documentation and make a release
- [x] merge PR to update mirage: https://github.com/mirage/mirage/pull/441 (superceded by #450)
- [x] release functoria from [mirage-dev](https://github.com/mirage/mirage-dev/tree/master/packages/functoria/functoria.dev) to opam-repo
- [x] release mirage from [mirage-dev](https://github.com/mirage/mirage-dev/tree/master/packages/mirage/mirage.2.7.0) to opam-repo
- [x] merge mirage-www updates https://github.com/mirage/mirage-www/pull/389
- [x] merge mirage-www updates https://github.com/mirage/mirage-www/pull/410
- [x] merge mirage-skeleton updates https://github.com/mirage/mirage-skeleton/pull/104
- [x] update and merge API breaking change on mirage-www: https://github.com/mirage/mirage-www/pull/390
- [x] merge edits to blog on @Drup's fork: https://github.com/Drup/mirage-www/pull/3
- [x] merge blog post new functoria on mirage-www: https://github.com/mirage/mirage-www/pull/396
- [x] send a message on `mirage-devel@` to announce the release

**Comment by samoht** [comment]
@avsm @djs55 @mor1 @talex5 (and others). Any opinion on the API breaking change about `--xen` and `--unix` which become `-t xen` and `-t unix`?

**Comment by amirmc** [comment]
Would be good to keep if possible. It's in many examples and probably scattered around the web. 

Best wishes,
Amir

--
Sent via mobile

**Comment by talex5** [comment]
Yeah, will cause lots of confusion if that breaks. Just special-casing `argv = [| _; "--xen" | "--unix" |]` to show a note about the new format would be OK, though.

**Comment by mor1** [comment]
:+1:

personally i'm happy to change over to `-t xen|unix` only, and lose support
for `--xen` and `--unix` but only if there's a warning as THomas suggests

On 2 October 2015 at 19:08, Thomas Leonard <notifications@github.com> wrote:

> Yeah, will cause lots of confusion if that breaks. Just special-casing argv
> = [| _; "--xen" | "--unix" |] to show a note about the new format would
> be OK, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/issues/447#issuecomment-145109369>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by samoht** [comment]
Updated the list with link to blog post PR, comments about the auto-detection code and need of cmdliner release.

**Comment by samoht** [comment]
I've updated the task list, the current unticked box is what I am working on right now. Once this is done, the rest will be much faster, thanks to @Drup hard work this summer.

**Comment by samoht** [comment]
Functoria is now almost ready to release. Waiting for final ack from @Drup and eventual review from @yallop. Need to update the blog post with a small intro for the release (@amirmc can you coordinate that with @yallop) and replace the TODO with exemple on how to use `app_info` (@Drup can you look at that?). Thanks!

And sorry for taking so long to review functoria...

**Comment by amirmc** [comment]
Hooray!  @Drup @yallop Let me know when I should look at the post again.

**Comment by yallop** [comment]
> Functoria is now almost ready to release.

Are you planning to wait for the release of fmt? (/cc @dbuenzli)

> Waiting for ... eventual review from @yallop.

I'm planning to look at this early next week, probably Monday.

**Comment by Drup** [comment]
fmt has been released.

**Comment by yallop** [comment]
Ah, so it has.  I was going by the description on the [GitHub page](https://github.com/dbuenzli/fmt): 

>  OCaml Format pretty-printer combinators (unreleased)

**Comment by dbuenzli** [comment]
@yallop Thanks. Corrected.

**Comment by dbuenzli** [comment]
btw. in general my website is the authoritative source of information, github is just there for people to interact with the project

**Comment by samoht** [comment]
@yallop #460, #464 and #467 needs investigation. Also https://github.com/mirage/mirage-www/pull/410 and the suspicious repetitions of messages on https://github.com/mirage/mirage-www/issues/404

**Comment by Drup** [comment]
@samoht All of those are now fixed.

**Comment by amirmc** [comment]
@yallop Can you update the set of checkboxes at the top here? It's not clear what still needs to be done before the 2.7 release.

**Comment by Drup** [comment]
For mirage-www, the PR to merge is probably [this one](https://github.com/mirage/mirage-www/pull/410). https://github.com/mirage/mirage-www/pull/389 is more involved (and probably need a bit of testing, I'm not sure it works well with decks and all that).

**Comment by yallop** [comment]
@amirmc: yes, I'll update as I go.

**Comment by amirmc** [comment]
Just saw your comment Jeremy :)
I'm reviewing the latest version of the blog post now and noticed a few typos. Will submit edits in a PR to @Drup's fork.

**Comment by yallop** [comment]
There are mostly just a few mirage-www merges remaining:
* merge mirage-www updates mirage/mirage-www#389
* update and merge API breaking change on mirage-www: mirage/mirage-www#390
* merge blog post new functoria on mirage-www: mirage/mirage-www#396
* https://github.com/mirage/mirage-www/pull/410

I'm not sure what the last one's about. @samoht, can you please clarify (or, even better, merge it, if you're happy)?

**Comment by Drup** [comment]
Can we at least just merge the blog/wiki parts ?

**Comment by Drup** [comment]
@yallop We may have to fix mirage's version in mirage-www's scripts while we wait for the functoria compatibility fix (which is supposed to be mirage/mirage-www#410, iirc).

**Comment by samoht** [comment]
@yallop I'll look at the last PR, I really like to remove https://github.com/mirage/mirage-www/blob/master/.travis.yml#L17 ...

**Comment by samoht** [comment]
I've ticked one more box.

**Comment by samoht** [comment]
https://github.com/mirage/mirage-www/pull/434 is a blocker currently, I had to rollback to the last version of the website before the merge. I'll debug that later this afternoon or tomorrow. I might simply remove the [loopback hacks](https://github.com/mirage/mirage-www-deployment/blob/master/scripts/deploy-tls.sh#L43-L44) and use the new `.in` features that @djs55 introduced in 2.6.0

**Comment by samoht** [comment]
the deployment is fixed by https://github.com/mirage/mirage-www-deployment/pull/18 and https://github.com/mirage/mirage-www/pull/389 is live, I've ticked one more box. I found a (non-blocking) bug while fixing this (#500).

I think we are ok to publish the blog post and do the announcement on Monday, yay!

**Comment by Drup** [comment]
Everything is done, :confetti_ball: 

I'm closing!
