### ISSUE TITLE
There should be somewhere to put bounds checks for BLOCK reads/writes

### ISSUE THREAD

**Issue by djs55** [mirage/mirage#448]
If an app violates the contract of a V1 interface, for example by writing an out-of-bounds sector to a `BLOCK` device, who should detect the problem? We have multiple `BLOCK` implementations already:

- the raw Xen device driver
- the raw Unix device driver
- the `BLOCK` implementation from [mirage/ocaml-mbr]
- the `BLOCK` implementation from [xapi-project/ocaml-vhd]

Requiring each implementation to contain the bounds checks seems tedious and error-prone. Perhaps we should have a wrapper functor which checks the arguments, and passes the calls through to the underlying implementations? We could then instantiate the wrapper from the Mirage autogen code (or not, if bounds checks are requested to be disabled)?

See the discussion on [mirage/mirage-block-unix#32]

**Comment by yallop** [comment]
> Perhaps we should have a wrapper functor which checks the arguments, and passes the calls through to the underlying implementations?

That's a good idea.  It'd be worth having different names for the checked and unchecked versions -- `read` vs `unsafe_read`, and so on -- which show up in the type of the functor that adds checking.

**Comment by djs55** [comment]
And alignment constraints, see [mirage/ocaml-cstruct#87] for something related.
