### ISSUE TITLE
Fails to set exit status on error

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#459]
Mirage should report a non-zero exit status if there are errors in the configuration. e.g. we currently have:

    $  mirage configure --unix --no-depext && echo All is well
    [ERROR] lwt.tracing module not found. Hint:
    opam pin add lwt 'https://github.com/mirage/lwt.git#tracing'
    All is well

I think the functoria merge broke this... /cc @Drup

**Comment by samoht** [comment]
This should be fixed now.
