### ISSUE TITLE
Tracing doesn't work since functoria merge

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#460]
Test-case (mirage-console + tracing):

    open Mirage

    let main =
      foreign "Unikernel.Main" (console @-> job)

    let () =
      let tracing = mprof_trace ~size:1000000 () in
      register "console" ~tracing [main $ default_console]

Gives:

    File "main.ml", line 43, characters 2-12:
    Error: This expression has type unit but an expression was expected of type
             'a Lwt.t

Also, the code seems to be emitted in the wrong order (tracing should be initialised before everything else, so you can trace the boot sequence and it sees the labels for the initial threads).

**Comment by talex5** [comment]
Also, I don't understand the new tracing API:

    val tracing : int -> job impl
    (** Tracking implementation. *)

    val mprof_trace : size:int -> unit -> int
    (** Use mirage-profile to trace the unikernel.
        On Unix, this creates and mmaps a file called "trace.ctf".
        On Xen, it shares the trace buffer with dom0.

        Deprecated. Is the identity over size.
    *)

    val register :
      ?tracing:int ->
      ?keys:Key.t list ->
      ?libraries:string list ->
      ?packages:string list -> string -> job impl list -> unit
    (** [register name jobs] registers the application named by [name]
        which will executes the given [jobs].
        @param libraries The ocamlfind libraries needed by this module.
        @param packages The opam packages needed by this module.
        @param keys The keys related to this module.

        @param tracing Enable tracing and give a default depth.
    *)

Why is `mprof_trace` deprecated? Are we sure we'll never want a different tracing framework, or new parameters for the existing one?

Why is the ring buffer size now called `depth`? (and `Mirage_key` now refers to it as the `tracing level`)

**Comment by Drup** [comment]
Hum, I remember testing it at the beginning of the dev, but not recently.

Do you prefer it to be abstract ? It's strictly the identity over int ...

> Also, the code seems to be emitted in the wrong order (tracing should be initialised before everything else, so you can trace the boot sequence and it sees the labels for the initial threads).

That's going to be tricky. Maybe by modifying the prelude dynamically ?

**Comment by talex5** [comment]
Yes, the type of `~tracing` should be abstract. Otherwise, people will do `register ~tracing:1000000 ...` and then next time we add an optional argument or a new tracer, their `config.ml` will break.

**Comment by Drup** [comment]
Ok. As a side point, could you move all the boilerplate that is currently in mirage and expose two simple functions, `MProf_foo.connect` with foo = unix or xen ?

**Comment by talex5** [comment]
Moving the boilerplate out isn't very easy:

1. Things like the trace file name and whether to start immediately are simply things that the mirage API doesn't yet let you configure. They shouldn't be hard-coded in the library, even if they are currently hard-coded in mirage.

2. The mprof library must have very few dependencies, because everything else depends on it. Moving the code would create circular dependencies (possibly mprof should be split into multiple opam packages to avoid this).

**Comment by Drup** [comment]
I don't see how your points prevent you to do that: 

```ocaml
let connect ~size s = 
  let buffer = mmap_buffer ~size s in
  let trace_config = MProf.Trace.Control.make buffer timestamper in
  MProf.Trace.Control.start trace_config ;
```

**Comment by talex5** [comment]
Yeah, could save a line in the Unix one.

**Comment by Drup** [comment]
It's not about saving a line, it's about putting as much of the plumbing as possible in control of the library, instead of putting it in mirage.

**Comment by mor1** [comment]
Reopening issue to note that the fix applied in #466 violates assumptions made in functoria so, although it works for now, it might become broken in future.

The suggestion (by @drup) is that the prelude should be made parametric to fix this properly.

**Comment by yallop** [comment]
> although it works for now, it might become broken in future.

It's broken now, since https://github.com/mirage/functoria/pull/44, as @Drup [notes](https://github.com/mirage/functoria/pull/44#issue-120573786).

**Comment by yallop** [comment]
The problem, as @Drup points out [elsewhere](https://github.com/mirage/mirage/pull/466#issuecomment-156078829), is that the [tracing `connect` method](https://github.com/mirage/mirage/blob/91e05fdee55fc04d7b0a0b2392c1f41a0e29dc4b/lib/mirage.ml#L960-L962) generates code like this

```ocaml
  return (`Ok ())
let () =
  let buffer = MProf_unix.mmap_buffer ~size:(Key_gen.tracing_size ()) "trace.ctf" in
  let trace_config = MProf.Trace.Control.make buffer MProf_unix.timestamper in
  MProf.Trace.Control.start trace_config
```

which is expected to appear in a specific context, whereas functoria assumes (but does not currently enforce) that `connect` returns an expression. Until recently that assumption wasn't used, but the [resolution](https://github.com/mirage/functoria/pull/44) of the [multiple-connect problem](https://github.com/mirage/mirage/issues/476) changed functoria's code generation to wrap a `lazy` round the return value of `connect`, which leads to a syntax error when applied to the code above.

I can see a few possible solutions here, but I'd like to understand the constraints better.  For example, one possibility is to jiggle the order of the generated code so that it sets up tracing before `return`ing `Ok`:

```ocaml
  let buffer = MProf_unix.mmap_buffer ~size:(Key_gen.tracing_size ()) "trace.ctf" in
  let trace_config = MProf.Trace.Control.make buffer MProf_unix.timestamper in
  let () = MProf.Trace.Control.start trace_config in 
  return (`Ok ())
```

Presumably, though, if this were an acceptable approach then the code would have done this originally.  @talex, @Drup: is it essential that the calls to `MProf_unix` occur at the top level rather than within the `lazy`?  If so, perhaps something based on [let insertion](http://okmij.org/ftp/meta-programming/#let-insert) might be more suitable.

**Comment by yallop** [comment]
Ah, I've just noticed this:

> Also, the code seems to be emitted in the wrong order (tracing should be initialised before everything else, so you can trace the boot sequence and it sees the labels for the initial threads).

so it sounds like something based on let insertion might be a more reasonable approach.

**Comment by yallop** [comment]
@Drup suggests another approach [here](https://github.com/mirage/functoria/issues/45).

**Comment by Drup** [comment]
Hum, I forgot to push that commit to mirage. This is done now.

You summarized the situation very well. If I understand this let-insertion scheme correctly, it's about marking placeholders in the syntax tree that can receive let bindings and then try to insert the let bindings in those place holders. 
Oleg's version is marking the placeholder with some delimcc magic, but we can clearly do without that.

One thing I like about the other approach is that it would make the key initialization less magic.

**Comment by yallop** [comment]
@talex5, can this be closed now?  The code in the original report now compiles, at least, and the tracing API is [restored](https://github.com/mirage/mirage/commit/385df0ffb3d18d4f8278e434371aa0799d703494).

**Comment by Drup** [comment]
@yallop I think this can be closed, we have another ticket in functoria to track the underlying issue.
