### ISSUE TITLE
Errors in config.ml result in unhelpful error message

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#461]
If `config.ml` doesn't compile then you get an error about unknown options instead. e.g.

    $ cat config.ml 
    foo

    $ mirage configure --unix
    mirage: unknown option `--unix'.
    Usage: mirage configure [OPTION]... 
    Try `mirage configure --help' or `mirage --help' for more information.

Running without arguments shows the real error:

    $ mirage configure
    [ERROR]
      
    ocamlfind ocamldep -package mirage -modules config.ml > config.ml.depends
    ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
    + ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
    File "config.ml", line 1, characters 0-3:
    Error: Unbound value foo
    Command exited with code 2.

**Comment by Drup** [comment]
Duplicated of https://github.com/mirage/functoria/issues/37

**Comment by mmaker** [comment]
yo, this is not yet fixed. With mirage 2.7.0 and functoria  1.0.0: 
```
$ cat config.ml 
foo
$ mirage configure --unix
mirage: unknown option `--unix'.
Usage: mirage configure [OPTION]... 
Try `mirage configure --help' or `mirage --help' for more information.
$ mirage configure 
[ERROR]
  
ocamlfind ocamldep -package mirage -modules config.ml > config.ml.depends
ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
+ ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
File "config.ml", line 1, characters 0-3:
Error: Unbound value foo
Command exited with code 2.
```


The error message from the first command is definitely unhelpful.

**Comment by Drup** [comment]
Dammit. I was convinced this one was solved.

@yallop Do you have an idea ? I think it is related to this line: https://github.com/mirage/functoria/blob/master/app/functoria_app.ml#L630

**Comment by yallop** [comment]
I think it'd be good to start thinking how to remove `base_context`.

**Comment by Drup** [comment]
@yallop That means droping `get_mode`. I don't disagree, but it seems quite early.

**Comment by samoht** [comment]
I'm fine with it as long it is documented

**Comment by yomimono** [comment]
Does it still seem quite early?  I'd really like to solve this for 3.0, and that's an excellent time to drop legacy stuff.

**Comment by samoht** [comment]
@yomimono yes, 3.0 seems like a good target to remove that hack :-)
