### ISSUE TITLE
Add native ARM64/Xen support

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#463]
@baozich has got a MiniOS ARM64 working at https://github.com/baozich/mini-os

See: http://lists.xenproject.org/archives/html/minios-devel/2015-11/msg00005.html

OCaml 4.02.3 should have quite robust native code generation support for this (once ocaml/ocaml#61) is applied, so we could get an ARM64 unikernel up and running without too much pain.  Need to make sure that the 32-bit/64-bit negotiation of the various net/blkfronts are all clean.

**Comment by yomimono** [comment]
@avsm it might be worth updating this issue with a quick summary of ongoing work - do you know who's best to tag for that?

**Comment by hannesm** [comment]
just as a note: Solo5 now has KVM/Linux/ARM64 support (I lack hardware to test this), but it looks like OCaml also works on arm64! :)  so, the remaining task is (after we found some Xen/ARM64 hardware) to get MirageOS-xen-arm64 up and running.

**Comment by mato** [comment]
#1159 tracks work on the new, PVH-only Xen stack. Once that is complete it will be fairly easy to port to aarch64 should someone be interested in doing the work.

I'm going to close this for now, as the existing Mini-OS based Xen stack will not get any further development.
