### ISSUE TITLE
config files in subdirectories no longer work since functoria merge

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#464]
From a `mirage-skeleton` master and `mirage` master pinned:

```
mirage configure console/config.ml --unix 
[ERROR] No configuration file config.ml found.
Please precise the configuration file using -f.
make: *** [console-configure] Error 1
flick:mirage-skeleton avsm$ 
```

If I switch into the subdirectory:

```
$ mirage configure config.ml --unix
mirage: too many arguments, don't know what to do with `config.ml'
Usage: mirage configure [OPTION]... 
Try `mirage configure --help' or `mirage --help' for more information.
```

So it looks like support for a custom `config.ml` has been dropped from the `mirage` frontend tool.

**Comment by Drup** [comment]
@avsm It isn't, See [the breaking changes](https://github.com/mirage/mirage-www/pull/390/files?short_path=bf20ed1#diff-bf20ed1a00d5115393dd7dc8645fe254).

**Comment by avsm** [comment]
Got it, thanks @drup!  Those changes really need to be listed in the `CHANGES.md` for `mirage/mirage`, as that's the authoritative source inside the repository.  Any chance of a PR that does that?

**Comment by Drup** [comment]
Oh, yes. I can do that.

**Comment by Drup** [comment]
This is solved.
