### ISSUE TITLE
get_mode () returns Unix with --xen (functoria)

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#470]
I have this in my `config.ml`:

    let main =
      let libraries =
        match get_mode () with
        | `Xen -> print_endline "Xen"; ["vchan.xen"]
        | `Unix -> print_endline "Unix"; ["vchan.lwt"] in
      foreign
        ~libraries
        ~packages:["vchan"]
        "Unikernel.Main" (console @-> job)

When I try to compile for Xen, it still uses the Unix flags:

    $ mirage configure --xen
    Unix

**Comment by Drup** [comment]
Thanks, it's solved. You should still avoid `get_mode`, Once the PR is merged, you will be able to write:

```ocaml
let main = Mirage.impl @@ object
    inherit [_] foreign
        ~packages:["vchan"]
        "Unikernel.Main" (console @-> job)
    method libraries = Key.(if_ is_xen) ["vchan.xen"] ["vchan.lwt"]
  end
```

(The version with `base_configurable ` is barely a few lines longer)

**Comment by talex5** [comment]
Does `get_mode` still give the wrong value?

**Comment by Drup** [comment]
No, that's fixed.

**Comment by talex5** [comment]
Yep - works for me now - thanks!
