### ISSUE TITLE
--version and --help require a config.ml file

### ISSUE THREAD

**Issue by yallop** [mirage/mirage#472]
In previous versions of mirage, `--version` and `--help` would work regardless of whether there was a `config.ml` file in the current directory:

```
$ mirage --version
2.6.1
$ mirage --help
MIRAGE(1)                        Mirage Manual                       MIRAGE(1)
[...]
```

With the current HEAD, the `mirage` command ignores its arguments when it can't find `config.ml`: 

```
$ mirage --version
[ERROR] No configuration file config.ml found.
Please precise the configuration file using -f.
```

**Comment by Drup** [comment]
I know, and I don't know how to solve it, if someone understands cmdliner enough to be capable to untangle the pile of spagetti that is functoria_tool, I would be grateful.

**Comment by yallop** [comment]
I'll take a look at it.
