### ISSUE TITLE
~deps:[abstract nocrypto] suggestion emitted for unikernels that don't use nocrypto

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#478]
Trying to get [the conduit_server_manual example in mirage-skeleton](https://github.com/mirage/mirage-skeleton/tree/master/conduit_server_manual) to build for Xen with the latest mirage, the tool instructed me to add `~deps:[abstract nocrypto]` to the call to `foreign`:

```
let handler = foreign "Unikernel.Main" ~deps:[abstract nocrypto] (console @-> stackv4 @-> job)
```

But after doing so, the generated `main.ml` adds an extra argument to the invocation of the start function, and the result is rejected by the compiler:

```
  Unikernel1.start _console_xen_01 _stackv4_ip1 _nocrypto1                      
```

**Comment by talex5** [comment]
As a work-around, you could add a `()` argument. However, the error is wrong, since the example doesn't need nocrypto.

**Comment by yomimono** [comment]
Looking at CHANGES.md it appears this is actually the intended behavior, so I'll just submit a PR for mirage-skeleton instead to add the extra argument in unikernel.ml .

**Comment by yomimono** [comment]
The message about nocrypto is emitted because tls is an installed depopt of ocaml-conduit, which is itself a dependency of mirage-http, which is included in the list presented to `add_to_opam_packages`.  It's true that the example uses no TLS, though.  @drup, is there new functionality in the Functoria rewrite of mirage that we could use to get around this?

**Comment by Drup** [comment]
@yomimono Ah yes, I know about that one. See https://github.com/mirage/mirage/pull/458

Basically, until conduit is correctly packaged, no. nocrypto *is* a link dependency of conduit if tls is installed, If there is a way to magically guess that it's actually not needed, I don't know it.
