### ISSUE TITLE
[meta] Upstream the Mirage/Rumprun port

### ISSUE THREAD

**Issue by mato** [mirage/mirage#479]
The purpose of this issue is twofold. First, to document the work done on the Mirage/Rumprun port so far, second, to serve as a meta-issue to track all of the pieces needed to fully upstream the Mirage/Rumprun port.

The Mirage/Rumprun port consists of:

1. A fork of the mirage tool which adds support for the `rumprun` target.  ([mato/mirage#rumprun](/mato/mirage/tree/rumprun))
2. An OPAM repository which contains the Ocaml/Rumprun cross toolchain and a subset of packages whose build systems have been patched to allow for cross compiling. ([mato/opam-rumprun](/mato/opam-rumprun))

## Rumprun target for the Mirage tool

Upstreaming should be fairly straightforward, as the `rumprun` target is mostly a copy-paste of the existing `unix` target. However, until OPAM gains support for cross-compiled packages, Mirage/Rumprun packages and their dependencies will need to continue using the "alternative namespace" of `-rumprun`.

## Ocaml/Rumprun cross toolchain

This is based on the work done by Peter Zotov (@whitequark) on the Ocaml/Android toolchain, and as such depends on patches specific to Ocaml 4.02.1. Upstreaming will require coordination with Daniel Bünzli (@dbuenzli) and the rest of the Ocaml team.

In addition to the compiler patches to support cross compilation, the `ocaml-rumprun` package also contains the following of note:

* The `build.sh`, `install.sh` and `remove.sh` scripts which in addition to building the Ocaml cross compiler set up the OPAM variables and ocamlfind `toolchain.conf` file so that the information about the cross toolchain is propagated to all packages built under the OPAM switch in which `ocaml-rumprun` is installed.

  This is necessary because, unlike the Android toolchain, the Ocaml/Rumprun toolchain is retargetable to different autoconf targets depending on which rumprun platform it is built for.

  See also the related upstream discussion at ocaml/opam#2247.

* The `ocaml-rumprun-hostpackage` tool used for installing a verbatim copy of a host package, or part thereof into the _cross_ toolchain. This is used primarily by packages that contain syntax/language extensions.

## Changes made to individual packages for cross-compiling

Apart from the changes needed to support the "alternative namespace" of `-rumprun` which affect all packages in the `opam-rumprun` repository, changes to individual packages fall under the following general groups.

Note that some packages may be in more than one group and packages where extra work was needed instead of/in addition to any of these general groups are noted further below.

1. Packages whose generated OASIS `setup.ml` files needed to be patched not to look for shared libraries as these are not built on rumprun.

   Needs to be fixed upstream in OASIS and `setup.ml` regenerated in the relevant packages.

   (`mirage-block-unix`, `io-page`, `lwt`, `nocrypto`, `ctypes`, `cstruct`, `mirage-profile`)

2. Packages which (unless noted elsewhere) required no changes other than specifying the cross toolchain to be used for the build/install/remove steps in the OPAM file with `env OCAMLFIND_TOOLCHAIN=rumprun`.

   (`asn1-combinators`, `base64`, `cmdliner`, `cohttp`, `conduit`, `cstruct`, `dns`, `io-page`, `ipaddr`, `magic-mime`, `mirage-block-unix`, `mirage-conduit`, `mirage-console`, `mirage-dns`, `mirage-http`, `mirage-profile`, `mirage-types`, `mirage-unix`, `ocplib-endian`, `re`, `stringext`, `tls`, `x509`)

3. Packages which, in addition to specifying the `OCAMLFIND_TOOLCHAIN` in the OPAM file, need to build a _host_ version of the `myocamlbuild` plugin used by their build system.
   
   (`fieldslib`, `lwt`, `nocrypto`, `sexplib`, `uri`)

4. Purely virtual packages. These contain only language/syntax extensions and are thus copied from the _host_ package into the _cross_ toolchain using the `ocaml-rumprun-hostpackage` tool.

   (`camlp4`, `type_conv`)

## Packages of special note

The following packages required extra work, generally due to use of a custom build system. Unless otherwise noted, modifications are shipped as patches in `opam-rumprun`.

These changes need to be reviewed individually to check if they will work for both native and cross builds and if so they can be upstreamed.

**conduit**

Uses a custom build system which needed manual patching to disable building of shared libraries. Changes are at [mato/ocaml-conduit#rumprun](/mato/ocaml-conduit/tree/rumprun).

**conf-gmp**

This package serves to provide a copy of libgmp. Required modification to OPAM file to cross compile.

**ctypes**

Uses a custom build system, needed patching to disable building of shared libraries, plus a small change to get `posix_types_stubs.c` to build on NetBSD (and thus rumprun).

**lwt**

Custom build system. I abused `--enable-android-target` to get cross compliation to work. Also uses `ocaml-rumprun-hostpackage` to install syntax extensions.  Requires OASIS files to be patched (group 1 above).

**mirage-clock-unix**

Custom build system. Manually patched to disable build of shared libraries.  Changes at [mato/mirage-clock#rumprun](/mato/mirage-clock/tree/rumprun).

**mirage-unix**

Semi-custom build system. Essentially group 3 above, but also required manual patching to disable shared libraries. Changes at [mato/mirage-platform#rumprun](/mato/mirage-platform/tree/rumprun).

**nocrypto**

Due to use of code generation (`nocrypto_bindgen`) which needs to run on the _host_ during the build process, cross compilation is hard. See the comments in `nocrypto-rumprun.0.4.0/opam`.

**sexplib**

Group 3 above, additionally use `ocaml-rumprun-hostpackage` to install extensions.

**tcpip**

The `direct` stack needed to be removed from the build as this does not have support for NetBSD/Rumprun. Changes at [mato/mirage-tcpip#rumprun](/mato/mirage-tcpip/tree/rumprun).

**zarith**

Custom build sustem, required manual patching for cross compilation and disabling shared libraries.

**Comment by whitequark** [comment]
Note that OCaml 4.02.3 requires no patches, only provided configuration files. (There's an ocamldoc-related patch in my ocaml-android tree, but it's inessential.)

**Comment by hannesm** [comment]
I suspect we can close this as it will not happen (and we now have solo5)?

**Comment by mato** [comment]
Yes, closing. If we do revive this work in the future it won't be in it's current form.
