### ISSUE TITLE
netif-forward broken with current trunk mirage

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#481]
Attempting to build netif-forward (a unikernel with two network devices) with `mirage configure --unix` succeeds, but when attempting to run it a failure is always encountered on initializing the second interface.  Building with mirage 2.6.1 succeeds on the same machine.  Hacking in some debug output, it looks like mirage is trying to initialize the same interface twice in the Functoria version, leading to an error from the underlying tuntap:

```
$ sudo ./mir-network
Netif: plugging into 0 with mac c2:9d:56:19:d7:2c
Netif: connect 0
Fatal error: exception Failure("Failure(\"tun[TUNSETIFF]: Device or resource busy\")")
Raised at file "src/core/lwt.ml", line 789, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 71, characters 5-10
```

From the main.ml generated by mirage, this looks a bit suspicious:

```
let net11 = lazy (                                                              
  Netif.connect (Key_gen.network ())                                            
  )                                                                             
                                                                                
let net12 = lazy (                                                              
  Netif.connect (Key_gen.network ())                                            
  )      
```

If Netif.connect is called with "0" and "1" in net11 and net12 respectively, we meet with success instead of failure.

**Comment by yomimono** [comment]
This issue was reported in #mirage by @jgjl (thanks!)

**Comment by Drup** [comment]
Ah, yes, because they use the same key names by default...
I think the best is to not generate keys by default. It's going to be the same issues for the stack and kv_ro, unfortunately.

**Comment by Drup** [comment]
Of course, you can "solve" it by doing this: 

```ocaml
  register "network" [
    main $ default_console $ (netif "1") $ (netif ~group:"other" "2")
  ]
```

and then the code @yomimono posted become this:

```ocaml
let net11 = lazy (
  Netif.connect (Key_gen.network ())
  )

let net12 = lazy (
  Netif.connect (Key_gen.other_network ())
  )
```

**Comment by hannesm** [comment]
fixed and merged in mirage-skeleton (https://github.com/mirage/mirage-skeleton/pull/143), closing
