### ISSUE TITLE
FS examples? 

### ISSUE THREAD

**Issue by wiredsister** [mirage/mirage#487]
Any more in depth examples of working with the file system? I just see the disk image example in `/lib_test/fat`...
Something with `FS.create` and `FS.mkdir` to generate some directories and dummy files would be wildly useful. 

Other questions: 
I'm trying to build something that generates a static site source directory with templates and user configuration files (like Jekyll). So reading, parsing, and writing files is going to be important. 

I'm confused whether or not I should be using the regular `Unix` module or `Lwt_unix` -- the `V1_LWT` or just `V1`?

Exact build steps/ invocation would also be needed.
Thanks!

EDIT: 
Thought I'd paste what I'm trying here (this is quite literally copy pasted from the fat example):

`handler.ml` --> 

```ocaml
open Lwt

module Main (C: V1_LWT.CONSOLE) (F: V1_LWT.FS) = struct

  let start c fs =
    F.mkdir fs "TESTDIR" >>= function
    | `Ok _ -> C.log_s c "success"
    | `Error e ->
      match e with
(** sorry for grotesque prints everywhere *)
      | `Block_device err -> C.log_s c "block device err"
      | `Directory_not_empty err -> C.log_s c (err ^ " dir not empty")
      | `File_already_exists err -> C.log_s c (err ^ " file already exists")
      | `Format_not_recognised err -> C.log_s c (err ^ " format not recognized")
      | `Is_a_directory err -> C.log_s c (err ^ "is a directory")
      | `No_directory_entry (err1, err2) -> C.log_s c ("no dir at " ^ err1 ^ ": " ^ err2)
      | `No_space -> C.log_s c "no space"
      | `Not_a_directory err -> C.log_s c (err ^ " not a dir")
      | `Unknown_error err -> C.log_s c (err ^ " unknown")
end

```

and here is `config.ml` --> 

```ocaml 

open Mirage

let main = foreign "Handler.Main" (console @-> fs @-> job)

let test = fat_of_files ~regexp:"*.*" ()

let () =
  register "fat" [
    main $ default_console $ test
  ]

```

After I've done `mirage configure --unix` and then `make` I run `./mir-fat` and get `"success"` printed out... so it's matching on the \`Ok but the directory `TESTDIR` was not created.

**Comment by yomimono** [comment]
Using `Unix` or `Lwt_unix` will result in your application not being usable with the Xen backend (i.e., as a unikernel).  If you only intend to build your applications with `mirage configure --unix`, this may not be a problem for you.

Re: `V1_LWT` vs `V1` -- most modules only have fully concrete definitons in `V1_LWT`; the definitions in V1 have an abstract `io` type which `V1_LWT` defines as `Lwt.t`.  In a few cases there is no `io` type, so `V1` can be used (the CLOCK module type is an example), but the filesystem isn't one of them, so you'll likely want `V1_LWT`.

I built a unikernel with the example code you provided, and it does seem to make a directory in the test filesystem.  When setting things up, `mirage configure --unix` wlil generate an image file in the current directory called `fat1.img`, then use that as the filesystem on which directories, files, etc will be manipulated.  By mounting `fat1.img` after running `mir-handle`, you can see the contents of the filesystem added by the original configuration (the line `fat_of_files ~regexp:"*.*" ()` in `config.ml`) and the new directory added by the unikernel (`TESTDIR`).  Some output may be clearer:

```
$ mirage configure --unix
Mirage      Using scanned config file: config.ml
Mirage      Processing: /home/user/mirage-skeleton/fat/config.ml
Mirage      => rm -rf /home/user/mirage-skeleton/fat/_build/config.*
Mirage      => cd /home/user/mirage-skeleton/fat && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
fat         Using configuration: /home/user/mirage-skeleton/fat/config.ml
fat         Configuring for target: Unix
fat         1 job [Handler.Main]
fat         Installing OPAM packages.
fat         => opam --version
fat         opam depext is installed.
fat         => opam depext fat-filesystem io-page mirage-block-unix mirage-console mirage-unix
# Detecting depexts using flags: x86_64 linux fedora
# The following system packages are needed:
#  - m4
Name        : m4
Version     : 1.4.17
Release     : 6.fc21
Architecture: x86_64
Install Date: Sun 31 Jan 2016 03:18:59 PM GMT
Group       : Applications/Text
Size        : 534915
License     : GPLv3+
Signature   : RSA/SHA256, Sun 17 Aug 2014 05:07:38 PM BST, Key ID 89ad4e8795a43f54
Source RPM  : m4-1.4.17-6.fc21.src.rpm
Build Date  : Sun 17 Aug 2014 05:05:39 PM BST
Build Host  : buildvm-06.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.gnu.org/software/m4/
Summary     : The GNU macro processor
Description :
A GNU implementation of the traditional UNIX macro processor.  M4 is
useful for writing text files which can be logically parsed, and is used
by many programs as part of their build process.  M4 has built-in
functions for including files, running shell commands, doing arithmetic,
etc.  The autoconf program needs m4 for generating configure scripts, but
not for running configure scripts.

Install m4 if you need a macro processor.
# All required OS packages found.
fat         => opam install --yes fat-filesystem io-page mirage-block-unix mirage-console mirage-unix
[NOTE] Package fat-filesystem is already installed (current version is 0.10.3).
[NOTE] Package io-page is already installed (current version is 1.5.1).
[NOTE] Package mirage-block-unix is already installed (current version is
       2.1.0).
[NOTE] Package mirage-console is already installed (current version is 2.1.3).
[NOTE] Package mirage-unix is already installed (current version is 2.3.1).
fat         => ocamlfind query -format '%p'  -recursive fat-filesystem io-page io-page.unix mirage-block-unix mirage-console.unix mirage-types.lwt
fat         Generating: main.ml
fat         => ./make-fat1-image.sh
[qubes-mirage-firewall] (master) user@mirageos:~/mirage-skeleton/fat$ make
ocamlbuild -use-ocamlfind -pkgs lwt.syntax,fat-filesystem,io-page,io-page.unix,mirage-block-unix,mirage-console.unix,mirage-types.lwt -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -tag-line "<static*.*>: -syntax(camlp4o)" -cflag -g -lflags -g,-linkpkg main.native
Finished, 7 targets (0 cached) in 00:00:00.
ln -nfs _build/main.native mir-fat
[qubes-mirage-firewall] (master) user@mirageos:~/mirage-skeleton/fat$ ./mir-fat success
[qubes-mirage-firewall] (master) user@mirageos:~/mirage-skeleton/fat$ sudo mount -o loop fat1.img  /mnt
[qubes-mirage-firewall] (master) user@mirageos:~/mirage-skeleton/fat$ ls /mnt
config.ml  fat1.img  TESTDIR
```

Does this clarify things at all?

**Comment by wiredsister** [comment]
Yes, thank you for your thorough explanation! I was able to get this to work. 

I'll close this issue and paste back here for any questions. Any other resources for beginners I should be looking at? I saw you have an example-unikernels repo and I've already gone through the examples and installation tutorial provided by mirage.

**Comment by amirmc** [comment]
Tagging @dsheets since he's the first person I think of when someone mentions file systems (sorry, dude!).

He's also relevant since you mention Jekyll and there's still a related Pioneer Project to build an [Blog and OPAM-aware static website generator](https://github.com/mirage/mirage-www/wiki/Pioneer-Projects#blog-and-opam-aware-static-website-generator) — which we're both mentors for.  The work on this was happening over in the [Tower repo](https://github.com/dsheets/tower), in case you'd like to get involved :)

**Comment by dsheets** [comment]
@hannesm and @yomimono are the right people for the current Mirage FS interface, I think.

**Comment by hannesm** [comment]
I haven't used files much.. sorry
