### ISSUE TITLE
Feedback on key usage

### ISSUE THREAD

**Issue by Drup** [mirage/mirage#491]
This issue is here to track user-feedback on predefined keys in devices. My initial version, which is the [current dev version](https://github.com/mirage/mirage/tree/66f5fd9184c52bb3e0b02af32d80038b1d6bf137), was to put keys in devices rather liberally. I'm not sure it's good or bad and, more importantly, I fear it's a bit surprising for users.

Right now, those devices have keys:
- kv_ro generic (fat | archive | direct)
- network (interface)
- ip (address, netmask, gateway)
- udp socket (ip address)
- tcp socket (ip address)
- stack direct (dhcp | ip + ip keys)
- stack socket (interfaces)
- stack generic (socket | direct)
- tracing ("tracing_size")

And the default key : target

**Comment by amirmc** [comment]
I think it’s worth send an email to the list pointing at this issue.  I’ve pointed a few people at functoria but not sure if they’re watching this repo (so may not notice this request for feedback).

**Comment by yomimono** [comment]
Judging by the lack of angry comments and my own experience with keys, you did a fine job! I'm going to close this out; anyone who's discovered that they dislike the keys in the current mirage is welcome to open a separate issue or PR for their specific complaint.
