### ISSUE TITLE
depexts and sudo

### ISSUE THREAD

**Issue by mor1** [mirage/mirage#494]
It seems that the tool generally attempts to run `apt-get` as `sudo` to install depexts on Linux.
In some cases, the user might not have `sudo` powers, but equally, might not require them.
In others, the user might be required to run an alternative command to obtain `sudo` powers (e.g., here in the Computer Lab, in some cases `cl-asuser sudo` is required).

Would it be reasonable to either augment the existing command so it's invoked as `apt-get install ... || sudo apt-get install ...`; or simply to pass in an appropriate form of `sudo` as an environment variable or similar?

If so, I'll send a PR.

**Comment by samoht** [comment]
I think that's fine, as long as the `depext` query/install time don't become too long. It seems to be a big perf bottleneck.

**Comment by Drup** [comment]
Shouldn't that be solved in depext instead ?

**Comment by avsm** [comment]
Yes this should be an issue against depext

**Comment by mor1** [comment]
Ok-- which repo is depext then?

**Comment by dsheets** [comment]
https://github.com/ocaml/opam-depext

**Comment by yomimono** [comment]
I'm closing this issue, but please feel free to reopen it if you think we need to take some additional action in mirage.
