### ISSUE TITLE
Release mirage 2.7.0

### ISSUE THREAD

**Issue by yallop** [mirage/mirage#498]
I'm planning to tag and release mirage 2.7.0 shortly.

@avsm, @djs55, @samoht, @yomimono, @talex5, @Drup, @mor1, others:
Is there anything that's absolutely essential to fix before I do?

**Comment by Drup** [comment]
https://github.com/mirage/mirage/issues/493 needs a change in bootvar for a proper fix, so it will have to wait. Once the fix in bootvar has landed, it can be fixed locally inside `config.ml`, so I don't consider it blocking.

**Comment by amirmc** [comment]
There's a tracking issue at https://github.com/mirage/mirage/issues/447 and there are a number of open issues there.  I notice that #493 isn't listed.  IIRC Mirage 2.7.0 is basically the Functoria release so could we keep this activity in one place?

@yallop Could you look though the first comment on #447 and update it to reflect reality?

**Comment by hannesm** [comment]
@Drup should #497 be merged, or is an appropriate fix for that issue (#493) solely in bootvar?

**Comment by Drup** [comment]
@hannesm It's very crude, and I think we should try to find a better fix.

**Comment by yallop** [comment]
@amirmc: #493 isn't a blocking issue, so I'm leaving it off the list at #447.

**Comment by yallop** [comment]
I've tagged the release ([v2.7.0](https://github.com/mirage/mirage/tree/v2.7.0)) and submitted a PR (https://github.com/ocaml/opam-repository/pull/5798) to opam-repository.

**Comment by yallop** [comment]
It's [merged](https://github.com/ocaml/opam-repository/tree/b8b51c8aa72ca39ee84a5131989b4659a31061dc/packages/mirage/mirage.2.7.0).
