### ISSUE TITLE
No way to specify package versions/pins in config.ml

### ISSUE THREAD

**Issue by sgrove** [mirage/mirage#499]
As noted [here](http://lists.xenproject.org/archives/html/mirageos-devel/2016-02/msg00080.html), I need to pin a bunch of packages (e.g. https://github.com/mirage/mirage-bootvar-xen/issues/15) to get the unikernel booting appropriately, but there's no way to express this in config.ml. Someone else trying out the project will run into issues due to incorrect package versions, so working in a team on this is very difficult.

**Comment by hannesm** [comment]
as far as I understood in the 2016-06-29 call @talex5 mentioned that `<` and `>` get interpreted by some shell, and we'd like to be able to specify package versions inside of `config.ml` (to generate a proper `opam` file)... seems to be a 3.0 feature high on the list

**Comment by hannesm** [comment]
see also #392

**Comment by hannesm** [comment]
i worked only on the bits with version numbers, but I don't think we really need the ability to pin sth from inside config.ml: if you're bleeding edge, define your own opam repo, and do versioning (of pins) there!?

**Comment by samoht** [comment]
with opam2, the generated opam file will contain the url anyway. So pretty easy to add a `?url` argument to the `Package.t` later.
