### ISSUE TITLE
Functoria: block device names get turned into Unix paths, even on Xen

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#504]
e.g. my generated `.xl` file contains:

```
disk = [ 'format=raw, vdev=xvdb, access=rw, target=/home/user/work/cubieboard/skeleton/block/xvda1' ]
```

Looks like the unwanted expansion is coming from here:

https://github.com/mirage/mirage/blob/f5f6ca98d5d7f2339146af6b15cb95ea04a2d6b3/lib/mirage.ml#L1092

Note that the expansion is also done a second time (but, correctly, only for non-Xen targets) here:

https://github.com/mirage/mirage/blob/f5f6ca98d5d7f2339146af6b15cb95ea04a2d6b3/lib/mirage.ml#L210

**Comment by djs55** [comment]
Which aspect is unwanted? The fact it's a path at all, or the choice of
specific path?

Regarding use of a path at all: it should cause `xl` to set up a `loop`
device for you.

From [xl-disk-configuration](
http://xenbits.xen.org/docs/4.6-testing/misc/xl-disk-configuration.txt)

> =====================
> POSITIONAL PARAMETERS
> =====================
>
> target
> ------
>
> Description:           Block device or image file path.  When this is
>                        used as a path, /dev will be prepended
>                        if the path doesn't start with a '/'.

For example

  `format=raw, vdev=hdc, access=ro, devtype=cdrom, target=/root/image.iso`

Regarding the specific path: the idea was to simplify the Mirage beginner
case where code is built in and then run from dom0, i.e. the paths are the
same on the development box and deployment box. Advanced users (e.g. those
running Qubes? ;-) could still use the `.xl.in` file and a `sed` script of
their own devising to remap the paths if they are different on the
deployment host.



On Sat, Mar 5, 2016 at 11:41 AM, Thomas Leonard <notifications@github.com>
wrote:

> e.g. my generated .xl file contains:
>
> disk = [ 'format=raw, vdev=xvdb, access=rw, target=/home/user/work/cubieboard/skeleton/block/xvda1' ]
>
> Looks like the unwanted expansion is coming from here:
>
>
> https://github.com/mirage/mirage/blob/f5f6ca98d5d7f2339146af6b15cb95ea04a2d6b3/lib/mirage.ml#L1092
>
> Note that the expansion is also done a second time (but, correctly, only
> for non-Xen targets) here:
>
>
> https://github.com/mirage/mirage/blob/f5f6ca98d5d7f2339146af6b15cb95ea04a2d6b3/lib/mirage.ml#L210
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage/issues/504>.
>



-- 
Dave Scott

**Comment by talex5** [comment]
Ah, I see. I guess the problem is that we're using magic strings to guess what the user means. `disk.img` means to use loopback on a file called `disk.img`, but `xvda` (probably) doesn't mean a file called `xvda`. So the `.xl` file should ask the user to insert a value here manually, I suppose, in this case.

Could we offer an alternative to `block_of_file` that takes device names? e.g. `block_of_device_name`?

**Comment by djs55** [comment]
I think having `block_of_device_name` sounds like a useful addition.

**Comment by yomimono** [comment]
`block_of_xenstore_id` in #879 does exactly this, but with a (more? less?) confusing name.

**Comment by talex5** [comment]
Ah, great :-) This can be closed then.
