### ISSUE TITLE
Generated example .xl file should contain kernel arguments

### ISSUE THREAD

**Issue by djs55** [mirage/mirage#517]
The generated .xl file for mirage-skeleton/ping looks like this:

```
# Generated by ping (Tue, 15 Mar 2016 20:51:45 GMT).

name = 'ping'
kernel = '/src/mirage-skeleton/ping/mir-ping.xen'
builder = 'linux'
memory = 256
on_crash = 'preserve'

disk = [  ]

# if your system uses openvswitch then either edit /etc/xen/xl.conf and set
#     vif.default.script="vif-openvswitch"
# or add "script=vif-openvswitch," before the "bridge=" below:
vif = [ 'bridge=br0' ]
```

The `vif` section was created based on the detected configuration of the host where `mirage configure --xen` was run, so that a basic developer workflow would just be:
- install developer tools in dom0
- `mirage configure --xen`
- `make`
- `xl create foo.xl`

Unfortunately now this fails to work with an error message like this:

```
Netif.connect tap0: could not find device
Fatal error: exception Failure("net11")
Raised at file "src/core/lwt.ml" line 789...
```

The fix is to modify the generated `ping.xl` with:

```
cmdline="network=0"
```

**Comment by hannesm** [comment]
I just ran into this issue (when upgrading mirage-net-xen-1.4 to 1.6), but the suggested fix to add `cmdline="network=0"` into `foo.xl` does not solve my problem, I still get:

```
Netif.connect tap0: could not find device
Fatal error: exception (Failure net11)
```

any ideas?

**Comment by hannesm** [comment]
fixed by using `mirage configure --network 0` on the command-line

**Comment by hannesm** [comment]
once more I stumbled upon this issue... is it possible that we use `0` as default for `network` (I'm not sure where this value lifes)?

**Comment by yomimono** [comment]
I think this is fixed in MirageOS 3, please reopen and comment if you disagree.
