### ISSUE TITLE
mirage configure should detect and warn re: known unsupported (transitive) deps

### ISSUE THREAD

**Issue by sgrove** [mirage/mirage#525]
I added `ocamlrss` to my mirage site, hooked it in and got it working locally, then it failed later when I went to build a unikernel because it depends on `Neturl` …. and eventually unix.

It’d be nice if `mirage configure` warned when there were some deps included that clearly wouldn’t work when building a unikernel, so I would have known up front rather than way down the line

**Comment by dinosaure** [comment]
It will be nice to have a reproducible case, thanks! I will remove it from the milestone about MirageOS 3.0 (but I let the issue open).

**Comment by hannesm** [comment]
With mirage4, the compilation model is different and we don't know at configure time whether it will compile or not (depending on the solver, opam-monorepo, and if C sources are included, on these as well). Closing as CANTFIX (sorry).
