### ISSUE TITLE
Travis is failing on master: undefined reference to `caml_check_alignment_bigstring'

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#538]
Something new in Cstruct 2.0.0 perhaps?

https://travis-ci.org/mirage/mirage/jobs/126661361

```
_build/main.native.o: In function `camlCstruct__check_alignment_1347':
/home/travis/.opam/system/build/cstruct.2.0.0/_build/lib/cstruct.ml:100: undefined reference to `caml_check_alignment_bigstring'
_build/main.native.o: In function `camlCstruct__209':
cstruct.o:(.data+0x21a68): undefined reference to `caml_check_alignment_bigstring'
```

/cc @avsm

**Comment by djs55** [comment]
It is new: https://github.com/mirage/ocaml-cstruct/blob/daafda76f03ebdbd5eae0b3963d5f48435857d27/lib/cstruct_stubs.c#L75

Are the cstruct_stubs still being duplicated in another place?

**Comment by talex5** [comment]
Yeah, the (previously-identical) Xen version is in mirage-platform still.
