### ISSUE TITLE
Unbound Module "Mirage_Version"

### ISSUE THREAD

**Issue by cr-ver** [mirage/mirage#539]
Configuration: 
ocamlfind: ........................................... /usr/bin/ocamlfind
ocamlc: .............................................. /usr/bin/ocamlc.opt
ocamlopt: ............................................ /usr/bin/ocamlopt.opt
ocamlbuild: .......................................... /usr/bin/ocamlbuild
Package name: ........................................ mirage
Package version: ..................................... 2.9.0
os_type: ............................................. Unix
system: .............................................. linux
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.02.3
standard_library_default: ............................ /usr/lib64/ocaml
standard_library: .................................... /usr/lib64/ocaml
standard_runtime: .................................... /usr/bin/ocamlrun
bytecomp_c_compiler: ................................. x86_64-pc-linux-gnu-gcc -O2 -pipe -O -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O -fPIC
native_c_compiler: ................................... x86_64-pc-linux-gnu-gcc -O2 -pipe -O  -D_FILE_OFFSET_BITS=64 -D_REENTRANT
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... /usr/lib64
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. /usr/share/doc/mirage-2.9.0/html
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
Prepend a path when installing package: .............. /var/tmp/portage/dev-ml/mirage-2.9.0/image/
findlib_version: ..................................... 1.6.2
is_native: ........................................... true
suffix_program: ...................................... 
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ false
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: ......................... 
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_functoria_runtime: ............................... /usr/lib64/ocaml/functoria
pkg_ipaddr: .......................................... /usr/lib64/ocaml/ipaddr
pkg_astring: ......................................... /usr/lib64/ocaml/astring
pkg_logs: ............................................ /usr/lib64/ocaml/logs
pkg_functoria: ....................................... /usr/lib64/ocaml/functoria
pkg_functoria_app: ................................... /usr/lib64/ocaml/functoria
ocamldoc: ............................................ /usr/bin/ocamldoc

W: Cannot find source file matching module 'Mirage_version' in library mirage
/usr/bin/ocamlopt.opt unix.cmxa -I /usr/lib64/ocaml/ocamlbuild /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
/usr/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_runtime.mli > lib_runtime/mirage_runtime.mli.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_runtime.cmi lib_runtime/mirage_runtime.mli
/usr/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_runtime.ml > lib_runtime/mirage_runtime.ml.depends
/usr/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_info.mli > lib_runtime/mirage_info.mli.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_info.cmi lib_runtime/mirage_info.mli
/usr/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_info.ml > lib_runtime/mirage_info.ml.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_runtime.cmo lib_runtime/mirage_runtime.ml
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_info.cmo lib_runtime/mirage_info.ml
/usr/bin/ocamlfind ocamlc -a -dontlink unix lib_runtime/mirage_runtime.cmo lib_runtime/mirage_info.cmo -o lib_runtime/mirage-runtime.cma
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_runtime.cmx lib_runtime/mirage_runtime.ml
/usr/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_info.cmx lib_runtime/mirage_info.ml
/usr/bin/ocamlfind ocamlopt -a -dontlink unix lib_runtime/mirage_runtime.cmx lib_runtime/mirage_info.cmx -o lib_runtime/mirage-runtime.cmxa
/usr/bin/ocamlfind ocamlopt -shared -dontlink unix lib_runtime/mirage-runtime.cmxa lib_runtime/mirage_runtime.cmx lib_runtime/mirage_info.cmx -o lib_runtime/mirage-runtime.cmxs
/usr/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage.mli > lib/mirage.mli.depends
/usr/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage_key.mli > lib/mirage_key.mli.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage_key.cmi lib/mirage_key.mli
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage.cmi lib/mirage.mli
/usr/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage.ml > lib/mirage.ml.depends
/usr/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage_key.ml > lib/mirage_key.ml.depends
/usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage.cmo lib/mirage.ml
+ /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage.cmo lib/mirage.ml
File "lib/mirage.ml", line 1526, characters 16-38:
Error: Unbound module Mirage_version
Command exited with code 2.
E: Failure("Command ''/usr/bin/ocamlbuild' lib_runtime/mirage-runtime.cma lib_runtime/mirage-runtime.cmxa lib_runtime/mirage-runtime.a lib_runtime/mirage-runtime.cmxs lib/mirage.cma lib/mirage.cmxa lib/mirage.a lib/mirage.cmxs lib/main.native' terminated with error code 10")

**Comment by samoht** [comment]
which command did you run? What is your OS? does `make lib/mirage_version.ml` help?

**Comment by cr-ver** [comment]
using gentoo. wrote an ebuild using the oasis eclass. will have a look.

**Comment by yomimono** [comment]
I don't think this should be an issue after the `topkg` conversion.  I'm closing this out, but please feel free to reopen it.
