### ISSUE TITLE
arp and ip module types should assume one ip address and default gateway

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#557]
The current state (multiple default gateways; lists for netmasks but not addresses) is inconsistent and confusing.  The types hint at functionality that is not there.

**Comment by talex5** [comment]
The netmask situation is especially confusing because of this, which could perhaps be fixed at the same time:

    and type prefix = Ipaddr.V4.t (* FIXME: Use Ipaddr.V4.Prefix.t *)

**Comment by hannesm** [comment]
IMHO that should be `ip : t -> (Ipaddr.V4.t * Ipaddr.V4.Prefix.t)` (and a `set_` if we need to set the ip dynamically (or could we just have an IP passed at instantiation time, and get away without providing a mutable IP address?) -- if you like a new address, get a new stack

**Comment by yomimono** [comment]
> (or could we just have an IP passed at instantiation time, and get away without providing a mutable IP address?) -- if you like a new address, get a new stack

So for DHCP, we'd construct a stack, get an IP, then destroy the stack and replace it with one with our new information?  I think that's OK at program initiation time, but is it fine if the IP changes while the unikernel is running?

**Comment by hannesm** [comment]
if the IP changes while the unikernel is running, what should happen?  and how will you talk to it then?  if the IP changes, all connections will be broken anyways, thus we can just make a new IP stack!?!?

**Comment by yomimono** [comment]
That sounds like pretty resounding "yes, I think?" to "is it fine?"  (Right now we don't do even close to the right thing with DHCP, just getting a lease once and assuming it's valid forever, so the question is rather hypothetical I admit.)

**Comment by mor1** [comment]
Destroying the stack and creating a new on on address change sounds like
the right thing to do to me, so long as the effect of doing so is contained
to the stack -- ie., higher layer and application state in the unikernel
isn't / doesn't have to be affected.

If someone wants fancier behaviour I guess you'd look to extract the state
from the stack as required, and then recreate the new stack from that --
cf. the Irmin/ARP prototype, or the Irmin/TCP prototype...

On 13 July 2016 at 16:30, Mindy Preston <notifications@github.com> wrote:

> That sounds like pretty resounding "yes, I think?" to "is it fine?" (Right
> now we don't do even close to the right thing with DHCP, just getting a
> lease once and assuming it's valid forever, so the question is rather
> hypothetical I admit.)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mirage/mirage/issues/557#issuecomment-232392707>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAKP4IlNdgGfU8kbw6h1gKvuKZB2V-9Hks5qVQSzgaJpZM4JLf8G>
> .
>



-- 
Richard Mortier
mort@cantab.net

**Comment by talex5** [comment]
> if the IP changes, all connections will be broken anyways, thus we can just make a new IP stack!

Most applications would deal with losing a TCP connection by trying to open a new one with the same stack. That would succeed if e.g. DHCP changed the address of the existing stack, but not if it created a new stack.

**Comment by hannesm** [comment]
the ARP interface should be extended to be able to insert static arp entries

**Comment by Drup** [comment]
I must admit, I was extremly confused when I (re)wrote the ip devices for mirage. in `Mirage`:

```ocaml
type ipv4_config = (Ipaddr.V4.t, Ipaddr.V4.t) ip_config
type ipv6_config = (Ipaddr.V6.t, Ipaddr.V6.Prefix.t list) ip_config
```

Along with other inconsistencies. I guess you could revisit that too ?

**Comment by mor1** [comment]
@drup just for clarity-- are you referring to the same inconsistency as talex5 comment above? (use of `V4.t` rather than `V4.Prefix.t`?)

**Comment by Drup** [comment]
@mor1: Yes, `V4.Prefix` seems to be very underused in the API. There is also the fact that one has is list (but that my knowledge of ipv6 is non existent, maybe that's just normal distinction).

**Comment by nojb** [comment]
Yes, in IPv6 at least it should be a list, see https://tools.ietf.org/html/rfc4861#section-5.1 ("Prefix List").

**Comment by nojb** [comment]
See also https://tools.ietf.org/html/rfc5942 for some very informative discussion.

**Comment by yomimono** [comment]
I think the current state of things is enough better to close this issue.
