### ISSUE TITLE
Mirage.io certificate has expired.

### ISSUE THREAD

**Issue by mt** [mirage/mirage#574]
`$ curl -vvIk https://mirage.io 2>&1 | grep expire`

`* 	 expire date: 2016-08-03 10:24:00 GMT`
`* 	 SSL certificate verify result: certificate has expired (10), continuing anyway.`

**Comment by avsm** [comment]
Argh! Letsencrypt has shorter certificates of course... renewing now.

**Comment by avsm** [comment]
Now fixed, thanks for reporting!  We really need to automate this via ACME...
