### ISSUE TITLE
Add an is_unix key

### ISSUE THREAD

**Issue by mato** [mirage/mirage#575]
I'd like to add an `is_unix` key to Mirage.

The immediate requirement is that I'd like to get all of `mirage-skeleton` building with `MODE=ukvm` and `MODE=virtio` to add CI for Mirage/Solo5 and some of the tests (`conduit_server`, `conduit_server_manual`) currently depend on `is_xen` to decide whether or not to include the socket stack.

Rather than naming the key `is_unikernel` which is confusing, I propose to name it `is_unix` instead and evaluate to true if the target is `unix` or `macosx`.

Any comments / objections? ISTR we had discussed this on Slack at some point and agreed that there is a need to determine if the unikernel is being built for a UNIX target.

**Comment by hannesm** [comment]
@Drup suggested this as well in https://github.com/mirage/mirage/pull/565#issuecomment-234336999 I'd appreciate to get rid of `is_xen` for 3.0 and provide a `is_unix`.

**Comment by mato** [comment]
If everyone's happy with adding an `is_unix` key to mean "target is something UNIXy" then I can have a go at implementing it.

**Comment by yomimono** [comment]
Yes, I think this is a great idea.

**Comment by mato** [comment]
See #578, not sure if this is the 100% correct way to do it...?

**Comment by yomimono** [comment]
Looks good to me and is in use, so I'm closing this out.
