### ISSUE TITLE
mirage.io gives a very bad first impression as a self hosted mirage app

### ISSUE THREAD

**Issue by fhars** [mirage/mirage#587]
The load performance of mirage.io is utterly terrible, typically between 8 and 26 seconds for a page of mostly simple text.

According to the network tab in firefox, there are occasionally some requests for included resources where the connection establishment may take a few seconds, but in the vast majority of cases it takes less than 50ms from the moment the browser starts to connect to the server until the server starts to anwser the request, and several seconds to actually transfer the few kB of PNG or CSS data.

**Comment by avsm** [comment]
see mirage/mirage-www#488 -- there is some regression in the network layer that is causing these latencies.

**Comment by hannesm** [comment]
there were recent updates to the tcpip stack, it should be better now.  please comment on the mentioned mirage-www issue if the problem persists.
