### ISSUE TITLE
doc: CLOCK -> PCLOCK

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#595]
A very common task when porting from CLOCK to PCLOCK will be to get the Unix timeofday in float.

The fragment for this:

```
Ptime.to_float_s (Ptime.v (Ptime_clock.now_d_ps ()))
```

which is equivalent to `Unix.gettimeofday` or `CLOCK.time`

Should document this in the 2.x -> 3.0 porting guide.

**Comment by hannesm** [comment]
I think this is a horrible hack.  Better to fix the libraries to not assume any floating point representation of timestamps.  Surely that is slightly more involved, but it results in much cleaner code (which then is also portable to systems without floating points).

**Comment by yomimono** [comment]
Instructions on porting unikernels are on the list of documentation noted at https://github.com/mirage/mirage/issues/592 .  There is a [mirage-dev branch of the mirage-www repository](https://github.com/mirage/mirage-www/tree/mirage-dev) to which PRs documenting MirageOS 3 behavior can be made in advance of the release, including a prototype porting guide.
