### ISSUE TITLE
mirage configure should not install depext by default

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#596]
Also depext invocation should be `-ui` so that the package manager is updated, or it'll probably not be consistent for Debian/Ubuntu.

The common case for configuration is to not install depexts and it is quite slow, so reversing the default makes sense for 3.0

**Comment by hannesm** [comment]
done by #703 AFAICS

**Comment by yomimono** [comment]
I think this isn't quite right, as it seems we don't do the right thing when we need depexts - see https://travis-ci.org/yomimono/mirage/jobs/180149763#L1607 .

**Comment by mato** [comment]
Confirmed -- I also saw this while updating unikernel-runner to the new order. Have worked around it by installing depext packages manually for now.

**Comment by hannesm** [comment]
then the question arises whether the generated `Makefile` should include an `opam install depext` in its `depend` rule?

**Comment by mato** [comment]
No, it needs to do the equivalent of `opam depext -i` but for the `--deps-only` that Mirage wants. I'll see if I can figure out what that is.

**Comment by mato** [comment]
See #718
