### ISSUE TITLE
32bit CI builds

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#614]
we want them

**Comment by mor1** [comment]
FWIW looks like Travis has considered this and decided it's not on their roadmap: https://github.com/travis-ci/travis-ci/issues/986

Would cross-compilation be enough?

(Or is this going to be a job for datakit? :)

**Comment by hannesm** [comment]
I suspect this can also be added via common TravisCI scripts since there are 32bit OCaml switches.  I wanted to look into this, but couldn't find time so far (esp. how to deal with a 32bit OCaml switch and external C files sounds like a potential problem, but maybe C cross compilation can be done)

**Comment by mor1** [comment]
Sounds plausible but C cross compilation perhaps something to tackle after 3.0 release? Unless it would fit in with work already going on re C stubs? /cc @yomimono

**Comment by haesbaert** [comment]
What do we gain from compiling to 32bit ? Would any bugs show up at compile
time ?

I'd expect most bugs regarding 32bit and c stubs to show up only at runtime
no ?

I myself would mostly be interested in int overflows, since people got used
to 63 bits int in amd64.

Am Mittwoch, 12. Oktober 2016 schrieb Richard Mortier :

**Comment by mor1** [comment]
Yup; I think this posits a world in which there are Tests(tm) ;)

**Comment by haesbaert** [comment]
Ah yea, I forgot we can run them on travis, carry on then.

Am Mittwoch, 12. Oktober 2016 schrieb Richard Mortier :

**Comment by hannesm** [comment]
a motivation is clearly https://github.com/mirage/mirage-clock/issues/17

**Comment by mato** [comment]
@hannesm Which targets would you want to compile for 32-bit? AFAICT only unix makes sense. If that's enough then we don't need any really "cross compilation", just need to make sure that travis is using a +32bit OPAM switch and the relevant "gcc -m32" capable compiler is installed.

**Comment by mato** [comment]
@hannesm / @mort Also, *if* the Travis `dist: trusty` has proper multiarch support (not sure when that landed in Debian), then we can run 32-bit test binaries on it trivially.

**Comment by hannesm** [comment]
@mato whatever we can get running. unix and xen seems plausible (since MirageOS/Xen/ARM-32bit is supported and some people actually use it)

**Comment by dinosaure** [comment]
Closed by our current `ocaml-ci` used into every repositories of the MirageOS organization - however, our `mirage-ci` does not test it (/cc @TheLortex). However, I consider it as fixed and I will close this issue. Thanks for your report.
