### ISSUE TITLE
mirage vs Makefile

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#631]
Some functionality seems to be duplicated, there is `mirage configure` generating a Makefile.

Then, both `mirage build` and `make` are available, which seem to do very much the same.

But there is also `mirage clean` vs `make clean`, the latter is much less aggressive (just calls out to `ocamlbuild -clean`), whereas the former actually removes (nearly!?) all generated files, including the Makefile.

There is also `make depend`, which calls out to `opam` (but `mirage configure` does this by default (unless `--no-opam` is specified) nowadays as well.

Is this intended behaviour?  Should there be only a `mirage configure`, and the rest done via `make`?  Should we auto-generate a `Makefile` after all (is this an unnecessary dependency on make?)?

I also don't understand the following generated rule in the Makefile (after running `mirage configure -t unix`), there the same is generated under `main.native` name (and the `build` rule depends on `main.native`):

```
main.native.o:
        $(BUILD) main.native.o
```

It would be great to have this cleaned up, and superfluous stuff removed.

**Comment by mor1** [comment]
For me, the following targets would make sense:
`mirage configure` -- create the `Makefile`, `main.ml` etc
`mirage clean` -- call `make clean` then remove all the `mirage configure` generated files
`make depend` -- call OPAM to install dependencies
`make` -- build the unikernel
`make clean` -- remove build targets (but not `configure` generated files)

Or, remove the `Makefile` parts completely and do everything through the `mirage` tool. But that seems like we just end up reimplementing things that `make` does perfectly well?

(Also I'd have to redo my hardwiring to type `make` at every available opportunity!)

**Comment by hannesm** [comment]
I have a PR to remove `mirage build` https://github.com/mirage/functoria/pull/76

**Comment by samoht** [comment]
After some thoughts, I think we should keep `mirage build`. If at one point we want to transition to: 1/ generate an opam file and 2/ maybe switch to topkg or pure myocamlbuid, then it would be convenient to have helpers to call `opam pin` and `topkg build` for us. As usual, you can do things without the `mirage` tool, but it should provide for new users the easiest path.

I know that we switched back and forth between `make` and `mirage build` but maybe it's time to switch back and be more ambitious :-)

One idea of user interaction would be:

```
$ mirage configure -t xen --dhcp --key-foo toto
# generate _build/spitting_lama/opam
spitting_llama

$ mirage build spitting_lama --deps
# opam pin _build/spitting_lama/opam, install the deps, build the package
# at the end some information of how to run it. 

$ mirage configure -t unix --dhcp --key-foo bar --name xavier
xavier
$ mirage build xavier --deps
```

So every configuration steps has its own namespace and `mirage build` knows how to call `make` in the right namespace.

**Comment by yomimono** [comment]
@samoht: while I agree that it would be nice to have this functionality, do we really want to have it under the same subcommand name as something which used to do something else?  (And if we decide that we do, adding it back in will surely be a small part of that patch.)

**Comment by mor1** [comment]
I think it's simplest to have a single path to the objective myself.
So remove now (the single path is `make`), and add back at some future date
when we have a properly thought out design and implementation and we're not
relying on make.

Or else we update all the docs and tutorials to use `mirage build`, and
treat the generated `Makefile` as a purely internal artefact. But if we do
that we should try to make the CLI stable (at least, only add options while
existing options don't change) which means thinking it through now.

**Comment by samoht** [comment]
> So remove now (the single path is `make`), and add back at some future date
when we have a properly thought out design and implementation and we're not
relying on make.

Looks like a good plan :-)

**Comment by hannesm** [comment]
@samoht my long-term goal is to get rid of `make` (after all, a MirageOS unikernel should be able to compile itself; but that will likely take some time, maybe in release 4 or 5).

at the moment there are ~7000 lines of code in mirage and functoria (excluding mirage-types), the major amount does some code generation, but then there is also code to execute programs, logging, ... .  for me, this is slightly too intricate, and I appreciate less code doing less magic, while providing the same functionality.

I'm also missing functionality, such as using my `arp` library instead of `tcpip.arpv4` (it might be possible atm, but I fail to find how).  somehow it feels like the mirage tool has slightly too much stuff hardcoded (or it has too much knowledge about other MirageOS libraries).

another problem is bitrot -- the `mirage build` command invoked on *BSD `gmake`, whereas we recently put the Mirage generated `Makefile` into shape to be agnostic on the `make` used (it is currently at least BSD make and GNUmake compatible).  I didn't notice till 11 hours ago that we still had such a conditional hidden somewhere.

**Comment by samoht** [comment]
Yes simplifying the tool is certainly a good objective an I agree to remove `mirage build` until we have a better design. Fighting bitrot is a great goal, I'am all in for that :-)

**Comment by hannesm** [comment]
for Mirage3, I'd settle to the following workflow:

```
mirage configure -t $backend -f $config (generates Makefile, main.ml, crunch - does _not_ call out to opam)
make depend (invokes opam)
make (compiles)
mirage clean
```

I'm not sure whether anyone is eager to consider feature request #582 (simultaneous multiple backend support).  This may be as straightforward as suffixing each generated file with the current backend.

**Comment by yomimono** [comment]
> I'm not sure whether anyone is eager to consider feature request #582 (simultaneous multiple backend support). This may be as straightforward as suffixing each generated file with the current backend.

I'd really like it (and think suffixing will be sufficient), but I don't have the spare cycles to implement it for a while. :(
