### ISSUE TITLE
default network interface should be named something more generic

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#644]
The current "default" network interface is named tap0, which is pretty cryptic.  Something more generic like `net0` or `default_interface` might be better.

**Comment by mato** [comment]
While trying out the current state of `-t xen` on `mirage-dev` this also came up as an issue since the backend expects `0` but the default is `tap0`. So network-using unikernels from eg. mirage-skeleton will _not_ work out of the box on Xen but need to be configured with:

    mirage configure -t xen --interface 0
