### ISSUE TITLE
IP configuration --v4 ip/mask instead of --ip X --netmask Y

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#649]
instead of using `V4[V6].ip & netmask` (read: two command-line arguments), use a single one: `ip/netmask`).  This leads to fewer potential error conditions (what happens if a is provided, but not b), and is pretty standard.

The gateway can be a separate key since it is optional anyways (it is perfectly good to have a unikernel without a default gateway -- e.g. a local syslog collector, a DHCP server, ...).

Work only to be done once #643 is in to avoid conflicts and needless rebasing.

**Comment by hannesm** [comment]
> (but default gateway that isn't on the network should be a runtime error, probably)

should error as early as we can!

**Comment by yomimono** [comment]
Is this actually the right thing to do for ipv6?  See the last couple comments in https://github.com/mirage/mirage/issues/557

**Comment by yomimono** [comment]
The current behavior came in with https://github.com/mirage/mirage/pull/643 , which addressed in part https://github.com/mirage/mirage/issues/557 .

**Comment by mato** [comment]
The current behaviour is actually two arguments, `--ip=IP` and `--network=NETWORK/MASK`.

This syntax violates POLA and is unnecessarily hard to implement in things like docker-unikernel-runner, so I'd like to bump this issue. Can we change to just `--ip=IP/MASK` please? :-)
