### ISSUE TITLE
infrastructure wishlist

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#652]
- [ ]  build ARM images from mirage/xen-arm-builder to replace the old blobs.openmirage.org site (/cc @mor1)
- [ ]  deploy avsm/mirage-ci live on ci.mirage.io
- [x] self-hosted DNS service on solo5 for mirage.io
- [x] rotate in a HTTPS mirage.io on solo5

**Comment by yomimono** [comment]
We didn't do any of this stuff, but we did release Mirage 3; I'll update the metadata.

**Comment by yomimono** [comment]
The last item ("rotate in a HTTPS mirage.io on solo5") came up again in the IRC catchup this week.  What do we need for this?  @mato mentioned reinstalling a machine to use for end-to-end solo5 CI; could that platform be the host for the solo5-backed website?

**Comment by mato** [comment]
On Wednesday, 03.01.2018 at 08:52, Mindy Preston wrote:
> The last item ("rotate in a HTTPS mirage.io on solo5") came up again in the IRC catchup this week.  What do we need for this?  @mato mentioned reinstalling a machine to use for end-to-end solo5 CI; could that platform be the host for the solo5-backed website?

Unfortunately not, its located on my home office lab network which does not
have any significant publicly routable IPv4 address range to speak of. 

Apart from hardware with public IPv4 connectivity we'd also need to
engineer a suitable CD pipeline for the Solo5 variant(s) of the website,
i.e. what the Travis stuff for mirage-www currently does for Xen.

**Comment by hannesm** [comment]
The mirage.io is nowadays (a) using a mirage-based authoritative DNS server (b) hosted on solo5/kvm. I'm closing this issue, in case there are revised wishes, please re-open with more technical information.
