### ISSUE TITLE
TCP/UDP v4/v6 woes

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#658]
I'd like to write code which is agnostic to IP versions, see e.g.:

```OCaml
module Foo (UDP : V1_LWT.UDP) = struct
  let send udp dest_ip dest_port m () =
    UDP.write ~dest_ip ~dest_port udp (Cstruct.of_string m)
end
```

That works great!  But now I'd like to log a bit information (as first line of `send` above):
```OCaml
    Printf.printf "writing to %a:%d %s" Ipaddr.pp_hum dest_ip port m ;
```

Unfortunately, this fails due to `UDP.ipaddr` not being `Ipaddr.t`, but abstract.  Can we (in `V1_LWT`) expose this information somehow, please?  Or else I need to implement the same body of code just because there is no pp (or `to_string`) for `UDP.ipaddr`...

**Comment by Drup** [comment]
```ocaml
module Foo (UDP : V1_LWT.UDP with type ipaddr = Ipaddr.t) = ...
```

?

**Comment by hannesm** [comment]
but then I won't be able to pass any actual implementation (`UDPV4` or `UDPV6`), since `Ipaddr.t` and `Ipaddr.V4.t` (`Ipaddr.V6.t`) are not related!? (or am I wrong here?)

**Comment by Drup** [comment]
Ah. Your post wasn't really clear. Why not go the usual (functorised) route ? It's pretty much how all of mirage work.

```ocaml
module type S = sig type t val pp : Format.formatter -> t -> unit ... end 
module Foo (Ip : S) (UDP : V1_LWT.UDP with type ipaddr = Ip.t) = ...
```

**Comment by hannesm** [comment]
@Drup thx!  I now would want, since UDP/UDPV4 are part of mirage-types to have this `S` being provided by mirage-types as well (or rather have something sensible (TODO: find out common operations between IPv4/IPv6 addresses) provided for the UDP.ipaddr type).

**Comment by hannesm** [comment]
another example of a bit boilerplaty code is [skeleton/dns](https://github.com/mirage/mirage-skeleton/blob/6e1015fb30b9e46d8a0f564d966678a505d01d59/dns/unikernel.ml#L63-L76) -- from a broader view this example should just get some `stack` and don't care about v4 vs v6 at all.. we can do that once the 3.0 dust settles a bit

**Comment by hannesm** [comment]
The dual stack RFC #1190 solves this, as Drup described by using UDP/TCP where ipaddr = Ipaddr.t. Closing since the dual stack will be merged soon.
