### ISSUE TITLE
platforms (xen/solo5)

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#660]
since 4.04 we should be able to have our very own os type (since @avsm got https://github.com/ocaml/ocaml/pull/674 merged)

we should use our own OS type (break early, detect breakage early)!

**Comment by yomimono** [comment]
PR for the Xen side at https://github.com/mirage/mirage-platform/pull/178 .

**Comment by hannesm** [comment]
freestanding PR https://github.com/mirage/ocaml-freestanding/pull/14

**Comment by hannesm** [comment]
both PRs have been merged
