### ISSUE TITLE
remove Str module

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#663]
The OCaml distribution provides, as part of otherlibs, a module called `Str` which has some regular expression implementation.  There are parts of this implementation written in C, and it seems to be kind of out of fashion (a very imperative implementation).

Luckily there are alternatives, on the one side [astring](http://erratique.ch/software/astring), and if you need full regular expressions there is the fine [re](https://github.com/ocaml/ocaml-re) library written purely in OCaml.

The [`mirage.runtime` ocamlfind package](https://github.com/mirage/mirage/blob/4a0ca42da8cfe5af42682688e7225468db68a098/pkg/META.mirage#L12), which is [part of every MirageOS unikernel](https://github.com/mirage/mirage/blob/4a0ca42da8cfe5af42682688e7225468db68a098/lib/mirage.ml#L1748), embeds next to `logs` also `astring`.  For simple string processing (such as split), there is no need to use the big regular expression hammer anymore.

I removed the strstubs from being part of the OCaml runtime shipped for MirageOS unikernels.  In case your unikernel uses Str, it will be a link-time error -- this is how Travis found the occurence of Str in the dhcp example.  Please consider the following PRs:
   - [x] https://github.com/mirage/mirage-skeleton/pull/195 (adjustment to the dhcp example)
   - [x] https://github.com/mirage/mirage-platform/pull/175 (mirage-xen-ocaml)
   - [x] https://github.com/mirage/ocaml-freestanding/pull/12 (ocaml-freestanding)

Have an informational look into https://github.com/mirage/mirage-dev/pull/202 to convince yourself that Travis managed to compile mirage-skeleton with the new OCaml runtimes.

This is a breaking change and will be properly documented with the MirageOS3 release notes.

**Comment by yomimono** [comment]
I don't know how widely `Str` is used or how expected its presence is.  I'm in favor of not encouraging people to use libraries that aren't of high quality (which is why I merged https://github.com/mirage/mirage-skeleton/pull/195 ), but I also can't easily run `opam list --depends-on str` to find out how many packages we make it difficult to use in Mirage unikernels with this change.

**Comment by dbuenzli** [comment]
> but I also can't easily run opam list --depends-on str

If you do an `opam pin odig --dev-repo` this will install a tool call `metagen`, a call to `metagen --raw` will output on `stdout` all the `$(opam config var lib)/$pkg/META` files `odig` found in the switch (it won't report `META.$pkg` ones though; I don't know if mirage packages do that kind of thing). 

Something like `metagen --raw | grep '[" ]str[" ]'` should give a good idea of the usage on the *installed* base.

**Comment by samoht** [comment]
Deprecating the use of `Str` in Mirage libraries is certainly a good idea.

**Comment by yomimono** [comment]
thanks @dbuenzli !  While `opam` attempts to make the installed universe as large as possible, I'll note that just `grep`ping around in repositories for packages tagged with `org:mirage` yielded a few users, including `ctypes` .

**Comment by yallop** [comment]
I think ctypes only uses `Str` during configuration and code generation, not at run time, although that distinction isn't currently made in the `META` file.

**Comment by yomimono** [comment]
Thanks @yallop; that's the case for nearly all other `Str` users too AFAICT, but I wasn't familiar enough with ctypes to see that straight away.

**Comment by hannesm** [comment]
after 24 hours without anyone against it, I merged it.

some libraries use Str in their build system atm, there is also imaplet-lwt and an example in tls.lwt which use Str.  Since these are not MirageOS unikernels, they can be fixed independently without further breakage.
