### ISSUE TITLE
(Regression) DHCP no longer works on GCE

### ISSUE THREAD

**Issue by mato** [mirage/mirage#674]
The latest batch of tcp/dhcp stack updates (presumably the switch from the inbuilt client to "charrua") has broken DHCP on Google Compute Engine.

Example log here: https://gist.github.com/mato/12298b57731b29fb3997c6e593235967

Now, GCE DHCP *is* a bit weird in its use of `/32` addressing and a non-local gateway, but this used to work, perhaps that was an accident?

Relevant pointers: 

* RFC 3442: https://tools.ietf.org/html/rfc3442
* Related GCE issue: https://code.google.com/p/google-compute-engine/issues/detail?id=77

**Comment by mato** [comment]
Log with `--logs=*:debug`: https://gist.github.com/mato/d554205daaf294345f2f997953af7e83

**Comment by yomimono** [comment]
https://github.com/yomimono/charrua-client/commit/1f633e5ad1068efd50ba9d05c67bf7ef0dac50a4 might be sufficient to fix it, since it was working before.

**Comment by mato** [comment]
Seems to work (presumably you updated charrua-client in mirage-dev last night): https://gist.github.com/mato/2653e8c3b83f233c281128c61d67de28

**Comment by haesbaert** [comment]
I think the fix is correct, the RFC doesn't specify that routers should
have any relation with subnet, IIRC.

Martin Lucina <notifications@github.com> schrieb am Di. 15. Nov. 2016 um
11:23:

**Comment by yomimono** [comment]
Great, thanks @mato for the report and the follow-up, and @haesbaert for the verification. :)
