### ISSUE TITLE
doc: explain how the the Dockerfiles work 

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#697]
We don't explicitly document how to use the published MirageOS Dockerfiles.  See the [mailing list thread](https://lists.xenproject.org/archives/html/mirageos-devel/2016-11/msg00089.html) and my reply where some recommendations need to move in.

Also ocaml/infrastructure#7

**Comment by hannesm** [comment]
Closing since there are atm no "published MirageOS Dockerfiles". Please re-open with more detailed information what the issue is, and how to move forward. Thanks.
