### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#698]
as post-remarked on #690

The downside of this is that, as @talex5 remarked in https://github.com/mirage/mirage-console/pull/50#issuecomment-260770648, the errors are now closed.

Especially for `FLOW` this is a bit sad, since TLS has two kinds of failures: recoverable (such as `please reconfigure your required TLS version, or add some ciphersuite the other host understands`) and irrecoverable (no shared implemented ciphersuite).  When writing client code, I might want to handle the first by reconfiguring the stack and re-try to establish a connection, whereas the second is a hard failure.

Now, `FLOW` dictates which errors may happen: `` `Msg of string ``.  This needs some more consideration and a followup PR before 3.0 IMHO (I wouldn't count on myself having the time to work on that, unfortunately).

Having said this, I'd guess it depends very much on the specific device where we need flexible (user-extensible) errors and where not. My assumption is that there is no need for `NETIF` or `CONSOLE` to be flexible (apart from if we want to have uniformity across everything), whereas there are incentives for `FLOW` being flexible.

**Comment by yomimono** [comment]
I was thinking about this particular case and it seems there's generally a useful distinction between transient errors (or recoverable ones) and errors where nothing the caller can do (including wait) has a chance of making the call succeed.

I'd love to see followup PRs on the current errors work before 3.0.

**Comment by yomimono** [comment]
I've exacerbated this with #705 .

**Comment by lpw25** [comment]
I happened to arrive at this from skim reading mirageOS-devel. I have a suggestion that might help with what @talex5 mentioned in the linked comment. You could do something like:

```
(* In mirage-types -- or whatever your central place is *)
type flow_error = [
  `Some_error
  `Some other_error
]

val pp_flow_error : fmt -> flow_error -> ()

module type Flow = sig
  type error

**Comment by yomimono** [comment]
Belated thanks, @lpw25 , this was exactly the kind of "um just do this" advice I needed to face ever looking at this again.  Patches are coming but as always, I won't be heartbroken in the case that someone else gets to it first.

**Comment by hannesm** [comment]
I spend some hours in order to get this working, but failed so far.

What I discovered on the way:
- `Kv_ro.error` now contains `` `Unknown_key`` (previously: `` `Unknown_key of string `` -- what was the reason to drop the string (IMHO it was useful for error messages)
- `Flow.error` and `Flow.write_error` (and `Flow.or_eof`) -- I don't understand why there are two error types (and why `read` returns ``Ok `Eof``, while `write` returns ``Error `Closed``), this requires us to define our own set of combinators (see the two cases in https://github.com/mirage/mirage-channel/blob/0b128b61fd864e25e2e1e7d80a7376803c53171e/src/channel.ml#L50-L65) --> could we use a single representation (I prefer ``('a, [ `Msg of string | `Closed ]) result``) for both (and then use `Lwt_result`)?
- according to leo, `Tcp.error` should then be moved into the TCP implementation (but there should also be the type definition in `module type TCP`, so that consumers can dispatch on `` `Timeout | `Refused ``!?!?); `error` looks like the type to extend here
- extending TLS errors (which is a flow): this is where I wanted to get to, but didn't quite yet.

A first PR is #728 which removes type error from DEVICE, and should be good to go.
I'm looking for the reasoning behind `` `Eof `` and `` `Closed ``.

**Comment by yomimono** [comment]
> Kv_ro.error now contains `Unknown_key (previously: `Unknown_key of string -- what was the reason to drop the string (IMHO it was useful for error messages)

I dropped a number of strings from the FS-related error types because they usually reflected information that the caller would already have -- the case of `Unknown_key` is a good one, as if you're getting it you just called the function that generated it with a key.

> Flow.error and Flow.write_error (and Flow.or_eof) -- I don't understand why there are two error types 

I'm happy to replace this; it does feel awkward.

> (and why read returns Ok `Eof, while write returns Error `Closed), 

A bit of discussion on the last mirage call re: wtf I was thinking; this is a sensible way to think about connections that can be half-closed IMO but it seems people find it unintuitive.

> this requires us to define our own set of combinators (see the two cases in https://github.com/mirage/mirage-channel/blob/0b128b61fd864e25e2e1e7d80a7376803c53171e/src/channel.ml#L50-L65) --> could we use a single representation (I prefer ('a, [ `Msg of string | `Closed ]) result) for both (and then use Lwt_result)?

I have no objection to this.

> according to leo, Tcp.error should then be moved into the TCP implementation (but there should also be the type definition in module type TCP, so that consumers can dispatch on `Timeout | `Refused!?!?); error looks like the type to extend here

I agree & have patches for this in the works.

**Comment by avsm** [comment]
The new proposed use of `private` by @lpw25 is is broadly the same as 'System 5' in @talex5's writeup in https://github.com/mirage/mirage-www/pull/274/files#diff-abb8c0c60c75065f86ff29942a483ec4R238, which is a good sign :-) The drawbacks that @talex5 notes are:

> - There is a performance penalty to wrapping every success value in an `Ok` variant, and a cost to matching on `Error` at every step.

This is acceptable at this stage. We are focussing on a clean typed interface and not on individual boxing issues (for MirageOS 3.0 anyway).

> - Programmers often don't care about error cases when writing code. If the error is considered "unlikely" then they often insert poor handling (e.g. `assert false` or `failwith "Error!"`).
> When the error does one day occur, it will be very difficult to track down.
> When using many libraries, the error must be correctly propagated at every step (`P(error_seen) = P(one_step_correct) ^ n_steps`).

This one is mitigated by new libraries such as Logs being consistently used, and also the `pp_` functions making it easy to print out errors as they happen.  I believe Logs and Fmt didn't exist when the original post was written.

> - Code that wants to take action on error (e.g. rolling back or moving to a "failed" state) must consider two code paths (error codes and exceptions). It is tempting to handle only one case, but they should almost always be treated identically.

Exceptions remain an issue, but we are heavily moving towards exception-free interfaces.  Mirage libraries are being more careful about leaking exceptions, although we need to be defensive with 3rd party libraries in practise.
 
> - The code becomes cluttered and the system is difficult to explain to new users.

Can't help this one :-) I think having explicit errors does makes things more clear, if it is indeed more verbose.

So I am in favour of the (hopefully last) shuffle to move to using `private` types in the module interface as Leo suggests, especially given @talex5's examination of the problem earlier last year.

**Comment by avsm** [comment]
Regarding combining `error` and `write_error`, I would suggest keeping them distinct for the moment.  In practise the error handling for read and write paths are quite different, and especially the blocking semantics vary (with write being generally more non-blocking).  If there really is a lot of commonality in libraries that emerges, it will be relatively easy to merge them in the future.

Otherwise this seems like an interface decision that will be juggled around without a firm decision either way and just delay our release...

**Comment by hannesm** [comment]
thanks to @samoht this is done now
