### ISSUE TITLE
io-page dependency

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#699]
as remarked on https://github.com/mirage/mirage/pull/585#issuecomment-261794358, the dependency onto `io-page` should be there due to `method deps = [ abstract default_io_page ]` in mirage.ml, but it looks like it does not get added.  it might be an issue in functoria.

worth digging into (maybe re-try after #691)

**Comment by hannesm** [comment]
I tested by removing the dependency, and both `io-page` and `io-page.unix` were still present when using crunch (using mirage-skeleton's kv_ro_crunch).

**Comment by hannesm** [comment]
surprisingly this works for unix/macosx and xen/qubes, but fails for virtio/ukvm (see travis run at https://travis-ci.org/hannesm/mirage-dev/jobs/179095516

@Drup any idea where this could come from?

**Comment by Drup** [comment]
What's the output of `describe` in the failing cases ?

**Comment by hannesm** [comment]
unclear. cannot reproduce this behaviour locally... weird..

**Comment by samoht** [comment]
`io-page` and `io-page.unix` unfortunately relies on a very bad linking trick to work: you need to specify the dependencies in the right order (and hope that ocamlfind will not re-order them for you).

tbh, I wish we could remove that horrible hack.

**Comment by hannesm** [comment]
since #940 was merged, this is no longer an issue
