### ISSUE TITLE
generation of Makefile for building unikernels

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#700]
is brittle, replace with some OCaml code based on bos/topkg?  not needed for 3.0, but a nice to have afterwards...  would also ease integration of other things, such as

![bytes](https://www.cl.cam.ac.uk/~hm519/mirage-console-bytes.svg)

![deps](https://www.cl.cam.ac.uk/~hm519/mirage-console-xen.svg)

(via https://hannes.nqsb.io/Posts/BottomUp)

**Comment by mor1** [comment]
(All IMO.)

No objection so long as invocation is as straightforward (`make` or `build` or similar; `mirage build` if you must), and it doesn't end up involving a twisty-turny maze of scripts (or `_tags` and `myocamlbuild.ml` or all the other many things that the many OCaml build systems seem to end up introducing) and and other such goop. Being able to see reasonably directly which commands are being invoked, as with a `Makefile`, is really useful -- moving to a simple `make` was such an improvement over the thousand and one ways that were explored prior to that...

(Ok, maybe I exaggerate slightly :) but please make it as simple to use. Also, what's actually brittle about the current practice?)

**Comment by hannesm** [comment]
evaluation order, differences between BSD make and GNU make, see https://github.com/mirage/mirage/pull/691#issuecomment-261815803.  The Makefile is just a string from the OCaml perspective - there's no type checking happening.  I'm pretty sure if we have whitespaces or unicode characters in anything, it will all break.

The build tool in my mind should be very independent from mirage code wise.  Just calling out to `pkg-config`, `ocamlbuild`, and `ocamlfind`.  I guess in history the configure and build phases were not strictly separated, as is with #691, thus leading to confusion and unneeded complexity.

**Comment by mato** [comment]
A partial step to improving this would be to use some kind of template engine type thingy for the Makefile generation rather than just appending to a string with `fmt`.

**Comment by hannesm** [comment]
now that #703 is in, what is left is to integrate generation of pictures (but these are new feature enhancements, the core of this issue is done)
