### ISSUE TITLE
`mirage --version` reports error without correct config.ml

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage#732]
With the `mirage-dev` remote.
```
$ mirage --version
mirage: [ERROR] config.ml does not exist, stopping.
%%VERSION%%
```
I'd expect this flag should work independently of `config.ml`

**Comment by hannesm** [comment]
it's probably my fault... and there are somewhere on my disk further changes to the command line argument handling in functoria... I will try to remind myself of this issue when I continue to work on those changes

**Comment by mato** [comment]
It looks like `--version` is also broken _with_ a `config.ml`, on latest `mirage-dev` it just prints

    $ mirage --version
    %%VERSION%%

**Comment by hannesm** [comment]
this is fixed now (see https://github.com/mirage/functoria/issues/97)
