### ISSUE TITLE
Page fault crash on Xen

### ISSUE THREAD

**Issue by TImada** [mirage/mirage#738]
I am having a trouble when using a combination of OCaml 4.03.0 and MirageOS from the mirage-dev branch on Xen.
MirageOS crashes by a page fault just after launching it by the xl command.

I have already tried four combinations including the above, and had no problems on the others.
result.txt below includes logs obtained when I tried mirage-skeleton/hello from the mirage-dev branch.
(1) OCaml 4.03.0 - MirageOS(mirage-dev) on Xen -> NG
(2) OCaml 4.04.0 - MirageOS(mirage-dev) on Xen -> OK
(3) OCaml 4.03.0 - MirageOS(mirage-dev) on KVM(virtio) -> OK
(4) OCaml 4.04.0 - MirageOS(mirage-dev) on KVM(virtio) -> OK
[result.txt](https://github.com/mirage/mirage/files/657063/result.txt)

The following includes the execution output of "opam list".
[opam_list.txt](https://github.com/mirage/mirage/files/657072/opam_list.txt)

**Comment by yomimono** [comment]
Does this happen with every unikernel you try building with 4.03.0 and mirage-dev ?  For example, does the `console` example from the `mirage-dev` branch of `mirage-skeleton` give you this result too?

**Comment by yomimono** [comment]
Ha, sorry, just looked at your `result.txt` and it looks like this *is* the `console` example.

**Comment by yomimono** [comment]
I couldn't reproduce this on my Qubes machine (Xen plus goodies), but I'll try on my Xen machine later today.

**Comment by TImada** [comment]
Thanks a lot for your help.

I have also tried ethv4, network, stackv4 and clock in mirage-skeleton from the mirage-dev branch, and had the same result.
[result2.txt](https://github.com/mirage/mirage/files/657540/result2.txt)

My Xen environment (Dom0: Ubuntu 16.04-1 LTS x86_64) is in the following file.
[xen.txt](https://github.com/mirage/mirage/files/657561/xen.txt)

**Comment by yomimono** [comment]
I wasn't able to reproduce this on my Ubuntu 14.04.5 Xen setup -- the `hello` example compiled and ran there as expected.  I've e-mailed you the `console.xen` I generated and was able to boot and run -- please let me know whether you can run that one, or whether it crashes as well.

**Comment by TImada** [comment]
I have confirmed that the binary file you provided worked fine on my environment.

```
root@xen-2:/home/test# xl create ./console.xl -c
Parsing config from ./console.xl
MirageOS booting...
Initialising timer interface
Initialising console ... done.
Hello World!
Hello World!
Hello World!
Hello World!
```

I also found that there was the following warning message during the compilation phase when I used OCaml 4.03.0 for both Xen and KVM(virtio). This message did not show up when I used OCaml 4.04.0.
`findlib: [WARNING] Interface V1_LWT.cmi occurs in several directories: /root/.opam/4.03.0/lib/mirage-types-lwt, /root/.opam/4.03.0/lib/mirage-types`

**Comment by hannesm** [comment]
@TImada the warning is because the `V1_LWT` module recently changed ownership (used to be part of mirage-types, is now part of mirage-types-lwt).  could you manually `rm /root/.opam/4.03.0/lib/mirage-types/V1_LWT*`, recompile and see whether you still get a page fault, please?

**Comment by TImada** [comment]
@hannesm 
I still get the same page fault error after executing the `rm` command and recompiling.
(though the warning massage did not show up)

**Comment by hannesm** [comment]
you may want to try to remove (or move away) the entire `/root/.opam/4.03.0` and recompile all opam packages, and see whether you still get the page fault... might be some temporary failure

**Comment by TImada** [comment]
I have removed `/root/.opam/4.03.0` completely, then installed packages I needed again.
The newly installed environment worked fine and did not have the page fault problem!

 Many thanks for your comments and supports.

**Comment by avsm** [comment]
I'm wondering where the linking mismatch came from here, so we understand the cause. Did you do some sort of a system package upgrade here after installing OPAM?

**Comment by TImada** [comment]
Yes, I think I have used three different versions from the mirage-dev branch.
1st: 15th Dec.
2nd: 16th Dec. (by opam update/upgrade)
3rd: 19th Dec. (by newly installation)
