### ISSUE TITLE
add unikernels which test the following libraries

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#739]
in #735 we discovered that several core libraries are not tested by any mirage-skeleton unikernel, namely:

- [ ] fat-filesystem
- [ ] hvsock
- [ ] logs-syslog
- [ ] mirage-block
- [ ] mirage-block-ccm
- [ ] mirage-block-ramdisk
- [ ] mirage-fs-unix
- [x] mirage-net-unix (mirage-skeleton/network does so!)
- [ ] mirage-net-macosx
- [x] mirage-stdlib-random
- [ ] protocol-9p
- [ ] tar-format
- [ ] vchan
- [ ] qcow-format
- [x] git
- [ ] vhd-format
- [ ] mbr-format

**Comment by yomimono** [comment]
`mirage-net-unix` should be tested at least by `network` (and really by anything using `default_network`) when MODE=unix.  This works locally; does it not happen in Travis somewhere that you could point me to?

**Comment by hannesm** [comment]
somehow #735 didn't capture the `mirage-net-unix` (or rather its travis run) error...

**Comment by yomimono** [comment]
A quick mapping of missing libraries to the [Mirage](http://docs.mirage.io/Mirage) functions, to be called from `config.ml`, which might request them:

```
    fat-filesystem -> [fat_of_files](https://github.com/mirage/mirage/blob/master/lib/mirage.mli#L211)
    hvsock -> no simple function
    logs-syslog -> [syslog_udp](https://github.com/mirage/mirage/blob/master/lib/mirage.mli#L440), [syslog_tcp](https://github.com/mirage/mirage/blob/master/lib/mirage.mli#L444), or [syslog_tls](https://github.com/mirage/mirage/blob/master/lib/mirage.mli#L448)
    mirage-block
    mirage-block-ccm
    mirage-block-ramdisk
    mirage-fs-unix [direct_kv_ro](https://github.com/mirage/mirage/blob/master/lib/mirage.mli#L193)
    mirage-net-unix (mirage-skeleton/network does so!)
    mirage-net-macosx (no simple function -- this is dynamically selected based on the backend)
    protocol-9p
    tar-format [archive_of_files](https://github.com/mirage/mirage/blob/master/lib/mirage.mli#L191)
    vchan
    qcow-format
    git
    vhd-format
    mbr-format

```

**Comment by miranda0615** [comment]
Hi @hannesm ,I'm a student from UT Austin. I am taking a virtualization class that requires us to work on an open source project, so I was wondering if you are still looking for people to contribute to this. If so, can I get more information on this issue? Thank you very much!

**Comment by hannesm** [comment]
yes, I'm not sure what further information you need for the issue... the above mentioned devices / implementations are not used by any of our mirage-skeleton examples... so e.g. an example (or family of examples) that use syslog -- i.e. the devices here http://mirage.github.io/mirage/mirage/Mirage/index.html#syslog-configuration -- would be great to have in mirage-skeleton so it does not bitrot (but is tested by CI on every mirage release)

**Comment by miranda0615** [comment]
Hi @hannesm , thanks so much for the reply! And thanks for the suggestions! Would you mind assigning this issue to me then? Thanks very much!

**Comment by hannesm** [comment]
@miranda0615 assigned to you

**Comment by hannesm** [comment]
Closing, more testing is always nice, but keeping lists up-to-date is not. ;)
