### ISSUE TITLE
potential regression in log level configuration

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#768]
From a comment in https://github.com/mirage/mirage/issues/571 by @hannesm: 

> I might have stumbled upon some regression -- after mirage configure -t unix I don't seem to be able to configure the logging level (make and `./foo -l *:debug' doesn't seem to work) -- anyone can reproduce this?

**Comment by yomimono** [comment]
I wasn't able to reproduce this when writing the porting guide for Mirage2 -> Mirage3 -- log level specification during runtime worked as expected.  Do you still have this problem?

**Comment by hannesm** [comment]
seems to be all good then. thx!

**Comment by hannesm** [comment]
I encountered this again, and the problem is entirely on my side (shell escaping): using `./main.native -l '\*:debug'` does not work, but `./main.native -l '*:debug'` does. sorry for the noise.
