### ISSUE TITLE
POLL: 4.02 compat for MirageOS3?

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#771]
as noted by @samoht: "It's just that if we can keep compat with 4.02 without too much work, I think we should try. If it is too much work, it is fine to drop it.

I've tried to add/keep support for 4.02 for some of the packages that I refactored during the previous weeks, but again, not a big deal if it is too much trouble." (in https://github.com/mirage/mirage-protocols/pull/3#issuecomment-272015536)

I suspect we need a decision (please vote with +1 emoji if you want MirageOS to support 4.02, -1 for dropping 4.02 support), and either remove 4.02 compatibility entirely (no need for a `result` package), or re-add 4.02 to the following packages.

```
mirage-dev/packages# git grep '>= "4.03'
charrua-client/charrua-client.dev~mirage/opam:available: [ocaml-version >= "4.03"]
crunch/crunch.dev~mirage/opam:available:     [ ocaml-version >= "4.03.0" ]
datakit-ci/datakit-ci.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
functoria/functoria.dev~mirage/opam:available: [ocaml-version >= "4.03"]
logs-syslog/logs-syslog.dev~mirage/opam:available: [ ocaml-version >= "4.03.0"]
mirage-block-ramdisk/mirage-block-ramdisk.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console-solo5/mirage-console-solo5.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console/mirage-console-unix.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console/mirage-console-xen-cli.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-console/mirage-console-xen.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
mirage-protocols/mirage-protocols.dev~mirage/opam:available: [ ocaml-version >= "4.03.0"]
mirage-qubes/mirage-qubes.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
protocol-9p/protocol-9p.dev~mirage/opam:available: [ocaml-version >= "4.03.0"]
```

**Comment by avsm** [comment]
I vote for a firm: drop 4.02. There is no demand for it that I can see, and I'd rather focus the time on trying out new features like flambda that have a potentially huge impact for us.

**Comment by samoht** [comment]
I don't have a strong opinion. As I said elsewhere, I am trying to keep the compatibility of the packages that I develop but I don't expect all the other MirageOS libs to do the same thing.

**Comment by jonludlam** [comment]
We're just about to upgrade to 4.03 or 4.04, so I'm happy to wave goodbye to 4.02.

**Comment by yomimono** [comment]
I vote (for at least the third time, possibly more?) to drop support for 4.02.

**Comment by avsm** [comment]
By the time we decide to drop 4.02, we'll have 4.05 out and will have to decide to drop 4.03 or not :)

**Comment by haesbaert** [comment]
+1 for dropping 4.02.

**Comment by yomimono** [comment]
So far we have four in support of dropping 4.02 and one "I don't have a strong opinion".

Considering the number of times we seem to have revisited this decision, I'm inclined to mention that the community has asked me to manage this release, and that the outcome of this discussion, each time it has occurred, has been a dearth of any real argument for retaining support for 4.02.
