### ISSUE TITLE
more than one generic_kv_ro can get a Functoria assert failure 

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#786]
The following `config.ml`:

```
open Mirage

let disk1 = generic_kv_ro "one_directory"
let disk2 = generic_kv_ro "another_directory"

let main =
  foreign
    ~packages:[package "duration"]
    "Unikernel.Main" (kv_ro @-> kv_ro @-> job)

let () =
  register "kv_ro" [main $ disk1 $ disk2]
```

works fine when the user doesn't set anything for the `kv_ro` key.  But if they pass a `--kv_ro` value, `mirage configure` fails:

```
4.04.0🐫  (reconcile) mirageos:~/mirage-skeleton/device-usage/kv_ro$ mirage configure -t unix
4.04.0🐫  (reconcile) mirageos:~/mirage-skeleton/device-usage/kv_ro$ mirage configure -t unix --kv_ro=direct
Fatal error: exception "Assert_failure lib/functoria_misc.ml:119:36"
```

It looks like `mirage` is attempting to register the same key more than once and violating a Functoria invariant.  At the very least, we can put a more helpful error message here, but it seems to me that configurations like this should be supported.

**Comment by samoht** [comment]
I though the name of the key would contain the device path/name (eg. `"one_directory"), so this would this kind of clashes. I guess something went wrong somewhere :-) /cc @drup any idea?

**Comment by yomimono** [comment]
I'm trying a patch that includes the directory name as a `group` parameter to `Key.kv_ro` which I think will work; if so I'll submit a PR and link it here.

**Comment by yomimono** [comment]
Hm, yeah, trying to guess a reasonable and non-clashing group from the directory is probably not a great approach.  Instead we should probably expose `group` as an argument to `generic_kv_ro` so the user can do something reasonable themselves.

**Comment by samoht** [comment]
hum I see. Having simple default when you only have one device is indeed a good idea. Would it be possible to do something different when you have 1 device or N>1 devices? Or maybe we just need to fix the error message.

**Comment by samoht** [comment]
@yomimono yes, exposing `group` as an optional argument is a good idea + fixing that awful error message :-)

**Comment by Drup** [comment]
> Would it be possible to do something different when you have 1 device or N>1 devices

erg, not without doing terrible things. Also, I feel it would be a bit surprising "I added a new device, why does my old configuration command line fail now ?"

The problem with adding group is that it would be ignored if you use ~key. And you can solve it by passing the key explicitly anyway. Maybe it's enough to document that ?

**Comment by yomimono** [comment]
I think I'd prefer `group` being ignored when `key` is specified (which will universally be true), to having the user need to specify `key` in `config.ml` when there's more than one device.  I'm strongly biased against requiring users to specify implementations in `config.ml`.

**Comment by Drup** [comment]
> I'm strongly biased against requiring users to specify implementations in config.ml.

I don't disagree with the rest, it's fine either to me, but I don't understand what that means.

**Comment by yomimono** [comment]
Having to edit `config.ml` when I build/run the unikernel in a different environment stinks.

**Comment by yomimono** [comment]
(In other words, I'm spoiled by how I never have to do that anymore with Functoria.)

**Comment by Drup** [comment]
Ah, actually, I think you misunderstand something, I'm talking about the key optional argument, which already work:

```
let disk1 = generic_kv_ro ~key:(Key.value @@ Key.kv_ro ~group:"potato") "one_directory"
```

**Comment by yomimono** [comment]
Ah, indeed we're talking about two different things; I was imagining the user passing the key directly as `Crunch` or `Fat` or whatever in the call to `generic_kv_ro` rather than calling `Key.kv_ro`.  Sorry for my confusion!

**Comment by yomimono** [comment]
And for the accidental close; why is GUI :(

**Comment by yomimono** [comment]
I guess I would prefer to expose a nicer interface to the user than this `Key` soup -- I discovered this bug while doing some rewrites to the Mirage tutorial, and so I'd like solutions that are simple to explain and easy to remember.  There's a bit on configuration keys in the earlier prose, but it doesn't go the extent of pointing users at the documentation for `value` or any of the items provided by `Mirage_key`.

**Comment by yomimono** [comment]
#102 gave a better error message for this problem, and the rest of this thread is just me being confused, so I'll close this.
