### ISSUE TITLE
mirage --help fails

### ISSUE THREAD

**Issue by yallop** [mirage/mirage#789]
```
$ mirage --version
3.0.0
$ mirage --help
Fatal error: exception (Invalid_argument "config must be an existing file (single segment)")
```

**Comment by hannesm** [comment]
hmm, could you try with functoria pinned to its dev-repo (`opam pin add functoria --dev-repo`)?  this should be fixed in master (via https://github.com/mirage/functoria/pull/101)

**Comment by yallop** [comment]
Thanks, @hannesm.  Pinning functoria to `--dev-repo` fixes things.

**Comment by hannesm** [comment]
we should stage a release of functoria. what are the rules, @yomimono?  a) who does it b) do we increment version numbers (2.0.1?)?

**Comment by yomimono** [comment]
Agreed.  We should increment to 2.0.1.  I think any volunteer is qualified but if nobody else has time, I'll do it later today.
