### ISSUE TITLE
things to do once Mirage 3 & friends are released into opam

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#792]
- [x] remove `EXTRA_REMOTES` from `travis.yml` and the equivalent from `appveyor.yml` on all repositories that had them added
- [x] unmark "pre-release" on all GitHub release pages
- [ ] fill in release dates on all changelogs
- [x] delete mirageos-3-beta (if possible, leave a breadcrumb leading to release announcement)
- [x] reset `mirage-dev` to a blank slate (mirageos 4 staging area)
- [ ] find release manager for MirageOS 4
- [ ] braindump feels & lessons to document somewhere and publish it

**Comment by amirmc** [comment]
> find release manager for MirageOS 4

I literally LOLd 😂 -- Think you for your (now sleepless) efforts on MirageOS 3 😊

**Comment by yomimono** [comment]
I never did find a release manager for MirageOS 4; if you're reading this message, you're qualified. ;)
