### ISSUE TITLE
Mirage build forces ANSI colour escapes

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#797]
This breaks e.g. Vim's quickfix feature because it doesn't strip the escape codes before matching error patterns.

Looks like this was added in https://github.com/mirage/mirage/commit/85b6932f61f25d50c5f878518089534174da083e#diff-7727aac76b5d1f16253b3426f63177d4R1592.

/cc @hannesm

**Comment by hannesm** [comment]
see https://github.com/ocaml/ocamlbuild/issues/87 for further discussion on how `-color {always,never,auto}` is not sufficient, and I submitted https://github.com/ocaml/ocaml/pull/1098 which reads the `OCAML_COLOR` environment variable.
