### ISSUE TITLE
make depend doesn't install the dependencies

### ISSUE THREAD

**Issue by argent-smith** [mirage/mirage#809]
Hello, I've just installed mirage on my macosx. Everything works fine except that `make depend` instead of installing the dependencies says everything's OK. After that, make falls with errors about not-installed dependencies. What am I doing wrong?

**Comment by hannesm** [comment]
which version of mirage are you using?  did you run `mirage configure` before `make depend`?

**Comment by argent-smith** [comment]
Yes, I did;

```
⟩ mirage describe
Name       hello
Root       /Users/paul/Development/own/mirage/hello
Keys       logs= (default), target=macosx (default),
  warn_error=false (default)
```

**Comment by argent-smith** [comment]
On Linux, this reproduces. I have to install the deps manually.

**Comment by hannesm** [comment]
the generated `Makefile` contains a `depend` target which does a `opam pin ..` followed by `opam install --deps-only ...`?

**Comment by argent-smith** [comment]
```
⟩ cat Makefile
# Generated by mirage configure (Sun, 12 Mar 2017 13:44:54 GMT).

-include Makefile.user

OPAM = opam
DEPEXT ?= opam depext --yes mirage-unikernel-hello-macosx

.PHONY: all depend clean build
all:: build

depend::
	$(OPAM) pin add --no-action --yes mirage-unikernel-hello-macosx .
	$(DEPEXT)
	$(OPAM) install --yes --deps-only mirage-unikernel-hello-macosx
	$(OPAM) pin remove --no-action mirage-unikernel-hello-macosx

build::
	mirage build

clean::
	mirage clean
```

**Comment by argent-smith** [comment]
Here's further shell output: https://gist.github.com/argent-smith/99e4fdbd83721060fc0f9af25664a3c6

**Comment by argent-smith** [comment]
This is unexpected:
```
opam install --yes --deps-only mirage-unikernel-hello-macosx

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[mirage-unikernel-hello-macosx] /Users/paul/Development/own/mirage/hello/ already up-to-date
```

Maybe I'm missing some opam plugin?

**Comment by hannesm** [comment]
could you edit the generated opam file, and remove the `name` field (if that does not help, replace `_` by `-` in its name), and run `make depend`, please?

**Comment by argent-smith** [comment]
Didn't help

**Comment by hannesm** [comment]
which version of `opam` do you use?

**Comment by argent-smith** [comment]
```
⟩ opam --version
1.2.2
```

**Comment by hannesm** [comment]
and do you have an external solver installed (such as aspcud)?  for me, a `make depend` actually installs the dependencies.

**Comment by argent-smith** [comment]
```
⟩ brew info aspcud
aspcud: stable 1.9.1 (bottled)
Package dependency solver
https://potassco.sourceforge.io/
/usr/local/Cellar/aspcud/1.9.1 (10 files, 512.1K) *
  Poured from bottle on 2015-06-29 at 15:45:49
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/aspcud.rb
==> Dependencies
Build: boost ✔, cmake ✔, re2c ✔
Required: gringo ✔, clasp ✔
```

**Comment by argent-smith** [comment]
Once last week it worked for me, too. I don't quite remember what's changed in the system.

**Comment by hannesm** [comment]
I expect `opam info mirage-clock-unix | grep installed` lists nothing?  does a manual `opam pin add --no-action --yes mirage-unikernel-hello-macosx` followed by `opam install --deps-only --yes mirage-unikernel-hello-macosx` do something on your system?

does `opam switch` complain that you should set environment variables (``eval `opam config env` ``)?

**Comment by argent-smith** [comment]
`opam switch` doesn't complain

```
~/Development/own/mirage/hello · (master)
⟩ opam info mirage-clock-unix | grep installed
   installed-version:

~/Development/own/mirage/hello · (master)
⟩ opam pin add --no-action --yes mirage-unikernel-hello-macosx .
Package mirage-unikernel-hello-macosx does not exist, create as a NEW package ? [Y/n] y
mirage-unikernel-hello-macosx is now path-pinned to /Users/paul/Development/own/mirage/hello

[mirage-unikernel-hello-macosx] /Users/paul/Development/own/mirage/hello/ synchronized
[mirage-unikernel-hello-macosx] Installing new package description from /Users/paul/Development/own/mirage/hello


~/Development/own/mirage/hello · (master)
⟩ opam install --deps-only --yes mirage-unikernel-hello-macosx

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[mirage-unikernel-hello-macosx] /Users/paul/Development/own/mirage/hello/ already up-to-date
```

**Comment by hannesm** [comment]
hmm, I don't have a clue what is going wrong here, hoping someone else has and will jump in.

**Comment by argent-smith** [comment]
Solved. My dependencies listed "lwt.ppx" which opam considered the wrong thing. Cleaned up, re-run, works. Thank you @hannesm for ideas :) BTW —debug key of opam is very useful :)

**Comment by hannesm** [comment]
good catch!  but the name should disappear from the opam file (since it is different from the opam file name)...

**Comment by argent-smith** [comment]
👍
