### ISSUE TITLE
node.js build is broken

### ISSUE THREAD

**Issue by cgreenhalgh** [mirage/mirage#81]
(there may be other issues but) the problems i saw were due to the openflow module's use of Net facilities which don't yet have dummies in the node version of the networking, e.g. OS.Netif, Net.Manager.interface.
The build is only attempted when js_of_ocaml is installed (which i only just installed) so I'm not sure when it stopped building.

**Comment by talex5** [comment]
I don't understand what this issue is about, but I assume it's old enough it should just be closed?

**Comment by talex5** [comment]
Seems Mirage used to have js support, but doesn't any longer.

**Comment by avsm** [comment]
Yes, in a source tree many, many branches away :-)
