### ISSUE TITLE
Docker MirageOS general questions.

### ISSUE THREAD

**Issue by aafanasyev** [mirage/mirage#819]
After reading http://unikernel.org/blog/2015/contain-your-unikernels and http://unikernel.org/blog/2015/unikernels-meet-docker i got idea to deploy [official docker wordpress](https://hub.docker.com/_/wordpress/) docker image in unikernel (Mirage OS). 

I'm using Xen running on Ubuntu Server 16.04.2 LTS, [Docker-CE ](https://docs.docker.com/engine/installation/linux/ubuntu/) and [MirageOS](https://mirage.io/wiki/install). Further as far as I understood I need to deploy the MirageOS Docker image to create some kind of [environment](https://hub.docker.com/r/unikernel/mirage/) which can be used to deploy/convert docker images in to MirageOS. However here I am stuck.

In addition I found other [ways](https://github.com/mato/docker-unikernel-runner) to deploy Docker in to MirageOS, but I do not got how convert docker images in to MirageOS Xen configs.

Any help will be appreciated.
 
Thank you.

**Comment by g2p** [comment]
MirageOS cannot run WordPress. The demo you linked uses rump kernels, a different technology, to convert legacy applications into something like unikernels.
