### ISSUE TITLE
Need a working example of how to use the mirage docker image

### ISSUE THREAD

**Issue by mjbright** [mirage/mirage#821]
The repository README states that

> There is a maintained Docker image at unikernel/mirage. You can also use the Dockerfile in this repository:

```
> docker build -t mirage .
> docker run -v <your-source>:/src opam config exec -- mirage
```

There are 2 problems here.

a) In the above example the image name is missing, it should be
```
> docker build -t mirage .
> docker run -v <your-source>:/src unikernel/mirage opam config exec -- mirage

e.g.

> docker run -v <your-source>:/src unikernel/mirage opam config exec -- mirage configure -t unix
```

b) For this to be of practical use we need then to be able to build artifacts using the same image.

For this we would need the contents of /home/opam/.opam to persist across container instances.

However, we can't just mount this as a volume as it exists already within the image.

Looks like we need some more sophisticated build process to create this image.

Thoughts?

**Comment by talex5** [comment]
In qubes-mirage-firewall, I use a Dockerfile to build an image with `mirage configure` done and the dependencies installed, and then use `docker run` to build the unikernel itself:

https://github.com/talex5/qubes-mirage-firewall/blob/master/Dockerfile
https://github.com/talex5/qubes-mirage-firewall/blob/master/build-with-docker.sh

(I didn't use `unikernel/mirage` as the base, but I could have done)

**Comment by mjbright** [comment]
Yes, thanks.
I see that you perform the "dependent" steps within the Dockerfile and so
your Dockerfile is specifically to perform a xen based build - of course as
it's for qubes.

So this mirage Dockerfile is a very basic template.

I'd suggest it would be useful to document here how you might extend that
Dockerfile to include the appropriate "mirage configure/make depend/make"
commands.

This would allow newbies to mirage to very easily build the mirage-skeleton
examples for example.

**Comment by hannesm** [comment]
Thanks for your report, I believe @talex5 comment has fixed the issue for you. In the meantime the Dockerfile from this repository was removed. Closing this issue, please re-open if there are further points to discuss.
