### ISSUE TITLE
Web Certificate Error from 4/18

### ISSUE THREAD

**Issue by DAMANgoldberg** [mirage/mirage#824]
![vb-fireshot pro screen capture 272 - privacy error](https://cloud.githubusercontent.com/assets/8891054/25261912/b6b2fed4-2622-11e7-96ad-4e85f7e4619d.jpg)

The browser information was inserted into this image, instead of uploading 2 separate ones. Not a browser issue as the same warning came up on Chrome 58 and Firefox 53.

**Comment by yomimono** [comment]
Thanks for the report, @DAMANgoldberg - I'm going to close this since https://github.com/ocaml/ocaml.org/issues/876 exists; any overlap between readers of the Mirage issue tracker and maintainers of `ocaml.org` is happy coincidence rather than design.
