### ISSUE TITLE
Mirage.io is down 

### ISSUE THREAD

**Issue by neuronsguy** [mirage/mirage#827]
Not sure if it's appropriate to post this as an issue, but the site contains relevant project documentation so it seems relevant.

**Comment by yomimono** [comment]
Indeed, thanks for the report!  @avsm has access to investigate this, but unfortunately I don't.

If there's something you wanted to have a look at right now, the (lagging) mirror at http://solo5.mirage.io/ is still up.

**Comment by avsm** [comment]
the VM isnt booting at all, investigating...

**Comment by avsm** [comment]
fixed by b2abdba184dc0ba06e9f6fa7ccf6b97c4ac976f0
