### ISSUE TITLE
Error: Unbound module Console_xen

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#830]
My last PR (#829) failed with:

    Error: Unbound module Console_xen

I rebuilt master on Travis and it failed in the same way:

https://travis-ci.org/mirage/mirage/jobs/236639117

Anyone know what happened to mirage-console-xen? @djs55?

**Comment by talex5** [comment]
Maybe this is a fix: https://github.com/mirage/mirage-console/pull/62

**Comment by djs55** [comment]
Indeed - opam repo PR is: https://github.com/ocaml/opam-repository/pull/9472
