### ISSUE TITLE
`make depend` adds a pin but doesn't remove it after failing

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#852]
`make depend` adds a pin in order to install dependencies for the unikernel before building.  If the dependency installation succeeds, the pin is removed, but in the case of failure (network problem, solver failure, etc) the pin is not removed.

**Comment by hannesm** [comment]
I agree this is a bug.  Unfortunately my Makefile skills are not sufficient to formulate "in any case, please `opam pin remove` after opam install --deps-only".   Is there a way to get away without `pinning` at all in opam?

As alternative, we could move the `opam pin` and `depext` into the mirage cli...

**Comment by Drup** [comment]
> Is there a way to get away without pinning at all in opam?

Well, yes. Opam 2.0 :)

**Comment by hannesm** [comment]
now, opam pin is only used during depext. this can be removed once depext gets support for local opam files.
