### ISSUE TITLE
put old, unmaintained, unused repositories in the attic

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#866]
Looking at the list of repositories owned by `mirage`, there are several that are unused and unmaintained.  This makes it harder to find user issues in the software we *are* using and maintaining.  Let's ~~move some of these historical packages to the [attic](https://github.com/ocaml-attic), as we did in https://github.com/mirage/mirage/issues/384~~ mark them as "archived" or move them back to personal repositories, so they can be excluded from searches.

- [x] [mirage-xentropyd](https://github.com/mirage/mirage-xentropyd), no longer used (archived)
- [x] [mirage-vagrant-vms](https://github.com/mirage/mirage-vagrant-vms), unmaintained and probably superseded by ukvm/virtio and containerized builds (moved)
- [x] [xen-testvm](https://github.com/mirage/xen-testvm), "Test VM to run on the Xen Hypervisor, based on Mirage", we now autogenerate these all the time :) (archived)
- [x] [testvm-idl](https://github.com/mirage/testvm-idl) (companion to xen-testvm) (archived)
- [x] [xenbigarray](https://github.com/mirage/xenbigarray), not used anywhere AFAICT (archived)
- [x] [megamirage](https://github.com/mirage/megamirage) (deleted)
- [x] [is-mirage-broken](https://github.com/mirage/is-mirage-broken) (archived; too big for @yomimono's home internet uplink to save a local copy of quickly)
- [x] [mirage-seal](https://github.com/mirage/mirage-seal) (moved)
- [x] [ocaml-re](https://github.com/mirage/ocaml-re), moved to ocaml organisation (deleted)
- [x] [ocaml-named-pipe](https://github.com/mirage/ocaml-named-pipe), contains `Deprecated bindings to Win32 named pipe APIs. Please use https://github.com/fdopen/uwt instead` (archived)
- [x] [mirage-ci.logs](https://github.com/mirage/mirage-ci.logs), orphaned (deleted)
- [x] [mirage-bushel-www](https://github.com/mirage/mirage-bushel-www), abandoned!? (archived)
- [x] [mirage-stable](https://github.com/mirage/mirage-stable), used by anyone?, destroy? (archived; @yomimono thinks @avsm may still have a plan for this and be interested in unarchiving/claiming it)
- [x] [mirage-http](https://github.com/mirage/mirage-http), now part of cohttp (archived)
- [x] [ocaml-ci-scripts](https://github.com/mirage/ocaml-ci-scripts), moved to ocaml organisation (deleted)
- [x] [xen-disk](https://github.com/mirage/xen-disk), incompatible with current module types (@djs55 claimed) (archived)
- [x] [ocaml-bloom-filters](https://github.com/mirage/ocaml-bloom-filters), never released, no license, no docs, last commit 3 years ago (moved)
- [x] [dyntype](https://github.com/mirage/dyntype), there is a replacement [depyt](https://github.com/mirage/depyt) (moved)
- [x] [mirage-tutorial](https://github.com/mirage/mirage-tutorial), examples and prose are at [mirage-skeleton](https://github.com/mirage/mirage-skeleton) and in [mirage-www](https://github.com/mirage/mirage-www/blob/master/tmpl/wiki/hello-world.md) (moved)
- [x] [mirage-tc](https://github.com/mirage/mirage-tc), used in old versions of Irmin and Datakit but looks abandoned now (moved)
- [x] [mirage-block-volume](https://github.com/mirage/mirage-block-volume), usage and status unknown? (@djs55 claimed) (archived)
- [x] [mirage-iperf](https://github.com/mirage/mirage-perf), superseeded by https://github.com/TImada/mirage_iperf (archived)
- [x] [crypto-keys](https://github.com/mirage/ocaml-crypto-keys) fork of a fork, no commits (deleted)
- [x] [shelf](https://github.com/mirage/shelf), a serialisation library (moved)
- [x] [jitsu](https://github.com/mirage/jitsu), which is not buildable and has had no maintenance in quite some time (@magnuss claimed) (archived)

Please add others or discuss if you oppose mothballing any of these.

**Comment by avsm** [comment]
lgtm -- cc @magnus about jitsu

**Comment by samoht** [comment]
some of these old repos could move to my account (instead of going to attic): like shelf, mirage-tc, dyntype, ocaml-bloom-filters and mirage-seal. Not sure I will maintain them better but at least the responsible for the lack of maintenance would be easier to spot.

**Comment by MagnusS** [comment]
I'm planning to update jitsu + demo, but not sure when it will be - as @samoht, I'm happy to move it back to my account if that's better

**Comment by olleolleolle** [comment]
There was mention in the IRC channel of the GitHub feature ["Archiving a Repository"](https://help.github.com/articles/archiving-a-github-repository/).

**Comment by yomimono** [comment]
I just tried archiving one of my old repositories to see whether it would accomplish the goal as I see it (get old, irrelevant stuff out of search results easily).  Opinion: it's good!

There's an `archived:false` tag which is included in many searches by default and excludes items in the archived repositories, so I think we should probably do that instead of moving stuff to `ocaml-attic`.

**Comment by yomimono** [comment]
I think moving repositories back to people's personal accounts is also a good solution to this - if you do so, please check off the repository in the list above :)

**Comment by mor1** [comment]
`mirage-vagrant-vms`-- go ahead, or happy to take it to my account, whichever (any preference?). There were some issues against it, and I had some longstanding todos to fix them but it seems clear I won't any time soon (and I agree, largely superseded now except I don't think we have an alternative means for testing builds for Xen other than a physical Xen box do we?)

`mirage-tutorial`-- this is a webhosted tutorial that was used at ECOOP a few years ago by @avsm and myself. Until the recent confusion over a replacement for hosting on `punk`, it was up and working at http://tutorial.openmirage.org. If the content is badly out of date now (and it probably is), it ought to be taken down but perhaps worth putting a redirect unikernel in place to explain and point to where equivalent material now exists?

**Comment by yomimono** [comment]
If you have any intention of doing work on it in the future it's probably better to take it your personal account, since you can't push branches to an archived repository.

**Comment by djs55** [comment]
I should probably take back

- `mirage-block-volume`
- `xen-disk`

**Comment by samoht** [comment]
I have moved back my libraries back to my account (and ticked the appropriate boxes).

**Comment by hannesm** [comment]
I annotated several repositories above with `destroy?` -- I don't think these need to be preserved.  the reasoning:
- `ocaml-re` and `ocaml-ci-scripts` are both hosted and actively developed at the ocaml organisation
- `megamirage`, `is-mirage-broken`, `mirage-ci.logs`, `mirage-stable` don't seem to contain any interesting code or data

if you have a different opinion, simply remove he `destroy?` remark above :)

**Comment by mor1** [comment]
I'll take `mirage-vagrant-vms` and `mirage-tutorial` back.
Shout at me today if you object :)

**Comment by mor1** [comment]
Moved to my account as notified, boxes ticked :)

@hannesm I wouldn't object to `destroy` for the ones you list.

**Comment by yomimono** [comment]
@djs55 and @MagnusS , I've archived `xen-disk`, `mirage-block-volume`, and `jitsu` in addition to the outstanding unclaimed repositories.  Please feel free to unarchive them (in `settings`) and claim them if you still wish to do so.

Thanks, everyone! :)
