### ISSUE TITLE
Mirage_logs/Logs doesn't work at top-level

### ISSUE THREAD

**Issue by kit-ty-kate** [mirage/mirage#873]
Suppose we have the following ```config.ml```:
```ocaml
open Mirage

let main = foreign "Unikernel" job

let () =
  let packages = [] in
  register "test" ~packages [main]
```
and the following ```unikernel.ml```:
```ocaml
let start =
  Logs.info (fun f -> f "Hello world !");
  Lwt.return_unit
```
If we execute it, the hello world is not displayed. This behaviour doesn't happen if ```start``` become a function as ```Mirage_logs``` will be initialized before the call to ```Logs.info```.

I wonder if something can be done in [mirage/functoria](https://github.com/mirage/functoria). Maybe there is a way to enforce or warn if we don't have a functor/function or something.

**Comment by Drup** [comment]
Unfortunately, the design for Logs in mirage was precisely done in order for this kind of code to be allowed. So I'm not sure we can really do anything about that. @talex5  ?

**Comment by talex5** [comment]
It seems reasonable to me to reject pure `job` unikernels, since we can't ensure any initialisation has happened before they start. This might also affect e.g. the random number generator. Perhaps there could be a `unit` device to help with this (so `unit -> job` runs `start ()`)?

**Comment by talex5** [comment]
Alternatively, we could just add a `()` argument to `start` in all cases. So it looks like
```ocaml
let start dev1 .. devn () =
  ...
```

**Comment by hannesm** [comment]
@talex5 I think this is a fine suggestion to always include a `unit` argument as the last one to start. Since this breaks all existing unikernels, we should do this in the 4.0 release. //cc @samoht

**Comment by samoht** [comment]
Or we can add a `()` only if there are no arguments

**Comment by hannesm** [comment]
@samoht that sounds rather magic to me, and hard to communicate to potential developers.

**Comment by dinosaure** [comment]
I agree to put systematically a `()` on the start function

**Comment by samoht** [comment]
I am a bit uncomfortable by adding a `()` to every existing start function: it's a large breaking change for a very narrow use-case.

We should document that behaviour, maybe even make the tool provide a warning if that happens, and provide a `unit` device instead.

**Comment by hannesm** [comment]
@samoht I like one of the following solutions (as suggested by @talex5 and others above):
- reject pure job unikenels (and provide a `nop` / `noop` / `unit` device - which is already present https://mirage.github.io/mirage/mirage/Mirage/index.html#val-noop)
- add `()` to every `start` function

**Comment by samoht** [comment]
Let's go with 1/ then :-)

**Comment by hannesm** [comment]
What about this issue? Should this be fixed within the mirage4 release?
