### ISSUE TITLE
Trouble building documentation locally because of missing ipv4 definition

### ISSUE THREAD

**Issue by typesanitizer** [mirage/mirage#875]
Running `odig odoc mirage` after `opam install mirage` (version `3.0.7`) gives:

```
[... bunch of warnings]
odig: [WARNING] mirage: /home/varun/.opam/4.06.0+afl/lib/mirage/mirage.cmi: no cmi found for 
                Sexplib0__Sexp (--------------------------------)
Error lib/mirage.mli, line 309, col 0 to line 313, col 2: Invalid reference: "unknown qualifier `ipv4'"
```
which is a problem with [this line](https://github.com/mirage/mirage/blob/76bd99a3cbcbf322294a4446df392eade1f08e57/lib/mirage.mli#L310) as the module [V4](https://github.com/mirage/mirage/blob/76bd99a3cbcbf322294a4446df392eade1f08e57/lib/mirage_key.mli#L101) doesn't contain the `ipv4`. If I understand correctly, this type is coming from the `ipaddr` package [here](https://github.com/mirage/ocaml-ipaddr/blob/4b711c4deb066c6bae5d451da4733ed059216fba/lib/ipaddr.mli#L39).

**Comment by dinosaure** [comment]
With the current version of `mirage`, I'm able to run: `odig odoc mirage` (you need to `pin` all of our versions). I consider it as fixed so. Thanks for your report.
