### ISSUE TITLE
mirage build and missing packages results in unexpected behaviour

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#876]
unintuitive behaviour on missing packages (expected: hard fail)

```
# mirage build
ocamlfind: Package `mirage-clock-unix' not found
ocamlfind ocamldep -package tls.mirage -package tls -package tcpip.unix -package tcpip.udpv4-socket -package tcpip.tcpv4-socket -package tcpip.stack-socket -package tcpip -package nocrypto.lwt -package nocrypto -package mirage-unix -package mirage-types-lwt -package mirage-types -package mirage-runtime -package mirage-logs -package mirage-fs-unix -package mirage-clock-unix -package lwt -package functoria-runtime -package cohttp-mirage -predicates mirage_unix -modules main.ml > main.ml.depends
...
```

here, `mirage-clock-unix` is clearly missing, but the compilation carries on.  IMHO the `ocamlfind` warning should be an error.

OCaml 4.06.0, mirage 3.0.7, ocamlfind 1.7.3

**Comment by dinosaure** [comment]
Not sure to be able to reproduce this error with MirageOS 4.0. I will close this issue but feel free to re-open it if you want to talk more precisely about this specific problem.
