### ISSUE TITLE
docs.mirage.io is down

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#886]
/cc @mirage/core

**Comment by yomimono** [comment]
I unfortunately have no idea where this lives or how to revive it. :/ at-mentioning those who I think might: @samoht @avsm @djs55

**Comment by avsm** [comment]
Sorry about this -- inclement weather lead to this due to a data centre shutdown. It's fixed, but I'm keeping this issue open to migrate/document the setup properly.

**Comment by avsm** [comment]
I've pushed some of the new scripts to build the docs into https://github.com/mirage/mirage-docs and https://mirage.github.io/docs/, and will update this issue when the https://docs.mirage.io website is moved over as well.

**Comment by hannesm** [comment]
My observation is that https://docs.mirage.io has rather old versions (3.5.1 -- which predates solo5 multi-device support) of the mirage libraries, and various (unfortunately very inconsistently) links point to that website (others point to https://mirage.github.io/<repo> (usually in opam files)) -- the mirage.io website uses docs.mirage.io, and README.md around the project use docs.mirage.io as well.

I was not able to figure out how/when/why the docs.mirage.io website is updated (anyone can help?). It would be great if it could contain a "last updated on yyy with opam-repository my_hash" in the footer.

**Comment by avsm** [comment]
it's updated from Cloud.drone.io via https://github.com/mirage/docs/blob/master/.drone.yml

I'll add that hash as you suggest. Currently porting it to use ocurrent.org on the side.

**Comment by avsm** [comment]
Rebuilding the docs site with newer packages now, and the date stamp

**Comment by avsm** [comment]
I'll close this now as the github.com/mirage/docs README has the info on how to update, and the site is not down :)
