### ISSUE TITLE
preparing for lwt 4.0.0

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#889]
[lwt 4.0.0 will have a number of changes which impact mirageos repositories](https://github.com/ocsigen/lwt/issues/453#issuecomment-352897664).  A partial list of users of deprecated functions is below (please feel free to edit more in, or comment here and I will add them if you can't edit):

soon-to-be-deprecated lwt function users:
  + [mirage-tcpip](https://github.com/mirage/mirage-tcpip) (lwt_sequence, a lot (user_buffer, segment))
  + [ezjsonm](https://github.com/mirage/ezjsonm) (waiter_of_wakener and others, but only in test code)
  + [ocaml-vmnet](https://github.com/mirage/ocaml-vmnet) (lwt_sequence, a lot)
  + [shared-memory-ring](https://github.com/mirage/shared-memory-ring) (lwt_sequence, heavily in lwt_ring.ml)
  + [mirage-solo5](https://github.com/mirage/mirage-solo5) (lwt_sequence, hooks registration; also lwt_pqueue in lib/time)
  + [mirage-xen](https://github.com/mirage/mirage-xen) (lwt_sequence, hooks registration (similar to solo5); also lwt_pqueue in xen/lib/time)
  + [mirage-unix](https://github.com/mirage/mirage-unix) (lwt_sequence, hooks registration (similar to solo5))
  + [mirage-net-xen](https://github.com/mirage/mirage-net-xen) (lwt_sequence, in backend)

There is also the matter of [the change in the semantics of bind](https://github.com/ocsigen/lwt/pull/500), which the lwt maintainer has requested users adjust to.  To my knowledge no such testing or adjustment work has been done in Mirage so far.  Information on what will break with this change would be useful to have when determining which packages, in which versions, will need to have their `lwt` dependencies constrained to `< 4.0.0`.

**Comment by aantron** [comment]
Thanks @yomimono. Concerning `Lwt.bind` specifically, see https://github.com/mirage/capnp-rpc/pull/149#issuecomment-372138235.

**Comment by hannesm** [comment]
I updated the list above to reflect the recent changes (creation of mirage-xen and mirage-unix repository which moved out of mirage-platform)

**Comment by avsm** [comment]
lwt-dllist is now out, and am steadily porting stuff to use it

**Comment by dinosaure** [comment]
I think, we can close this PR - `mirage` and its eco-system use `>= lwt.5.0.0`.
