### ISSUE TITLE
suggestion: provide a way to print used libraries and their versions on startup

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#896]
I usually don't keep track of which library versions I compiled into a unikernel, but would like to see this information at startup (and/or via a different way, a monitoring service should be able to receive this information and issue notifications about newly released dependencies).

at the moment, there exists the mirage_info module in the mirage-runtime library http://docs.mirage.io/mirage-runtime/Mirage_info/index.html but i don't know how to use it.

**Comment by Drup** [comment]
Well, that's what `Mirage.info` is for. You add it as a `deps` for your foreign module, and then you get an argument of type `Mirage_info.t`.

Do you have propositions to make it easier to use ?

**Comment by hannesm** [comment]
I found https://github.com/mirage/mirage-skeleton/tree/master/tutorial/app_info which uses `Mirage_info` -- which looks fine, but I'm more interested in _all transitive depedencies_, since at the end of the day I like to keep track of which libraries and versions I have deployed (to be able to reason which unikernels need to be updated once a security issue is discovered in (or a new release is done of) an opam package).  any idea how to achieve this?

**Comment by Drup** [comment]
That might be doable. The `info` combinator already has a built step where opam is called (currently, to obtain the exact versions), we could extend that to get all the dependencies as well.

**Comment by hannesm** [comment]
I looked slightly deeper into this.  I couldn't find a way with `opam` (1.2.2) to list all runtime dependencies for a given package (`opam info -f depends tcpip` lists all build and runtime dependencies).

Since the build process of mirage involves `ocamlfind`, I looked into that utility (to have the `requires` line of `META` files exposed: `ocamlfind query -r -format "%p %(version) %(requires)" tcpip` -- which we could script and unify in `functoria_app` in the build step of `app_info` (I'll push a wip branch soon).

Then I discovered that our `META` files are not completely correct anymore, it looks that `jbuilder` inserts a `unix` dependency to all our packages (see `tcpip`, `cstruct`, etc.) :( -- is this intentional and known?

**Comment by hannesm** [comment]
The current output of `mirage-skeleton/tutorial/app_info` with `mirage configure -t ukvm`:

```
packages = [solo5-kernel-ukvm.dev~solo5; mirage-types-lwt.3.0.7;
            mirage-types.3.0.7; mirage-solo5.dev~solo5; mirage-runtime.3.0.7;
            mirage-logs.0.3.0; mirage-console-solo5.dev~solo5;
            mirage-clock-freestanding.1.3.0; mirage-bootvar-solo5.dev~solo5;
            lwt.3.2.1; functoria-runtime.2.2.0; fmt.0.8.5]
libraries = [fmt; functoria-runtime; lwt; mirage-bootvar-solo5;
             mirage-clock-freestanding; mirage-console-solo5; mirage-logs;
             mirage-runtime; mirage-solo5; mirage-types; mirage-types-lwt]
```

the output using https://github.com/hannesm/functoria/tree/rdeps

```
packages = [astring.0.8.3; bigarray.; bytes.; cmdliner.1.0.2; cstruct.3.2.1;
            fmt.0.8.5; functoria-runtime.2.2.0; io-page.2.0.1; ipaddr.2.8.0;
            logs.0.6.2; lwt.3.2.1; mirage-block.1.1.0;
            mirage-block-lwt.1.1.0; mirage-bootvar-solo5.dev~solo5;
            mirage-channel.3.1.0; mirage-channel-lwt.3.1.0;
            mirage-clock.1.3.0; mirage-clock-freestanding.1.3.0;
            mirage-clock-lwt.1.3.0; mirage-console.2.3.5;
            mirage-console-lwt.2.3.5; mirage-console-solo5.dev~solo5;
            mirage-device.1.1.0; mirage-flow.1.3.0; mirage-flow-lwt.1.4.0;
            mirage-fs.1.1.1; mirage-fs-lwt.1.1.1; mirage-kv.1.1.1;
            mirage-kv-lwt.1.1.0; mirage-logs.0.3.0; mirage-net.1.1.1;
            mirage-net-lwt.1.1.0; mirage-profile.0.8.2;
            mirage-protocols.1.2.0; mirage-protocols-lwt.1.2.0;
            mirage-random.1.1.0; mirage-runtime.3.0.7;
            mirage-solo5.dev~solo5; mirage-stack.1.1.0;
            mirage-stack-lwt.1.1.0; mirage-time.1.1.0; mirage-time-lwt.1.1.0;
            mirage-types.3.0.7; mirage-types-lwt.3.0.7; ocplib-endian.1.0;
            parse-argv.0.1.0; ptime.0.8.3; result.1.3; sexplib.v0.10.0;
            uchar.0.0.2; unix.]
libraries = [astring; bigarray; bytes; cmdliner; cstruct; fmt;
             functoria-runtime; io-page; ipaddr; logs; lwt; mirage-block;
             mirage-block-lwt; mirage-bootvar-solo5; mirage-channel;
             mirage-channel-lwt; mirage-clock; mirage-clock-freestanding;
             mirage-clock-lwt; mirage-console; mirage-console-lwt;
             mirage-console-solo5; mirage-device; mirage-flow;
             mirage-flow-lwt; mirage-fs; mirage-fs-lwt; mirage-kv;
             mirage-kv-lwt; mirage-logs; mirage-net; mirage-net-lwt;
             mirage-profile; mirage-protocols; mirage-protocols-lwt;
             mirage-random; mirage-runtime; mirage-solo5; mirage-stack;
             mirage-stack-lwt; mirage-time; mirage-time-lwt; mirage-types;
             mirage-types-lwt; ocplib-endian; ocplib-endian.bigstring;
             parse-argv; ptime; result; sexplib; sexplib.0; uchar; unix]
```

imho this is an improvement and more honest of our runtime dependencies.  The implementation relies on both `ocamlfind` (to find the runtime dependencies using `ocamlfind query -r -format "%p" <direct dependencies>`) and `opam` (to substitute the installed package version in `%{package_name:version}%`, as before).

some questions:
- anyone _at runtime_ interested in the direct opam dependencies (as specified in `config.ml` or generated by the `mirage` utility (including version constraints)? (my branch does not emit this information anymore)
- anyone interested in the ocamlfind versions (from the `META` file)?
- are the opam runtime dependencies and the ocamlfind depends (in `META`) in sync? `mirage` uses the information from `META` to compile and link the unikernel image
- the implementation uses some assumptions: (1) the ocamlfind library name and the opam package name are the same, (2) X.Y is an ocamlfind sublibrary (and thus dropped from the package list), X itself will be part of the dependency as well.
- we're missing some dependencies, such as the ocaml-freestanding / ocaml-src (and likely as well gmp-freestanding) packages due to missing `META` information - I guess we should add proper `META` files (including their runtime opam dependencies) for these libraries as well.

**Comment by hannesm** [comment]
NB: with my [second commit](https://github.com/hannesm/functoria/commit/cd9049897dfe89b7e4cf99ec474b93f864b24516), the `solo5-kernel-ukvm` is as well part of the package list:

```
packages = [astring.0.8.3; bigarray.; bytes.; cmdliner.1.0.2; cstruct.3.2.1;
            fmt.0.8.5; functoria-runtime.2.2.0; io-page.2.0.1; ipaddr.2.8.0;
            logs.0.6.2; lwt.3.2.1; mirage-block.1.1.0;
            mirage-block-lwt.1.1.0; mirage-bootvar-solo5.dev~solo5;
            mirage-channel.3.1.0; mirage-channel-lwt.3.1.0;
            mirage-clock.1.3.0; mirage-clock-freestanding.1.3.0;
            mirage-clock-lwt.1.3.0; mirage-console.2.3.5;
            mirage-console-lwt.2.3.5; mirage-console-solo5.dev~solo5;
            mirage-device.1.1.0; mirage-flow.1.3.0; mirage-flow-lwt.1.4.0;
            mirage-fs.1.1.1; mirage-fs-lwt.1.1.1; mirage-kv.1.1.1;
            mirage-kv-lwt.1.1.0; mirage-logs.0.3.0; mirage-net.1.1.1;
            mirage-net-lwt.1.1.0; mirage-profile.0.8.2;
            mirage-protocols.1.2.0; mirage-protocols-lwt.1.2.0;
            mirage-random.1.1.0; mirage-runtime.3.0.7;
            mirage-solo5.dev~solo5; mirage-stack.1.1.0;
            mirage-stack-lwt.1.1.0; mirage-time.1.1.0; mirage-time-lwt.1.1.0;
            mirage-types.3.0.7; mirage-types-lwt.3.0.7; ocplib-endian.1.0;
            parse-argv.0.1.0; ptime.0.8.3; result.1.3; sexplib.v0.10.0;
            solo5-kernel-ukvm.dev~solo5; uchar.0.0.2; unix.]
libraries = [astring; bigarray; bytes; cmdliner; cstruct; fmt;
             functoria-runtime; io-page; ipaddr; logs; lwt; mirage-block;
             mirage-block-lwt; mirage-bootvar-solo5; mirage-channel;
             mirage-channel-lwt; mirage-clock; mirage-clock-freestanding;
             mirage-clock-lwt; mirage-console; mirage-console-lwt;
             mirage-console-solo5; mirage-device; mirage-flow;
             mirage-flow-lwt; mirage-fs; mirage-fs-lwt; mirage-kv;
             mirage-kv-lwt; mirage-logs; mirage-net; mirage-net-lwt;
             mirage-profile; mirage-protocols; mirage-protocols-lwt;
             mirage-random; mirage-runtime; mirage-solo5; mirage-stack;
             mirage-stack-lwt; mirage-time; mirage-time-lwt; mirage-types;
             mirage-types-lwt; ocplib-endian; ocplib-endian.bigstring;
             parse-argv; ptime; result; sexplib; sexplib.0; uchar; unix]
```

**Comment by samoht** [comment]
I wrote something similar for JITSU demos:

https://github.com/MagnusS/mirage-stats-demo/blob/master/manifest/manifest.ml

**Comment by avsm** [comment]
> anyone interested in the ocamlfind versions (from the META file)?
Nope!  But the opam-repository version (git version if possible) and remotes would be useful to record, so that the precise metadata can be reconstructed in the future.

**Comment by Drup** [comment]
I suggest (with opam 2): `opam list --nobuild --depopts --installed --rec --required-by <PKG>`.

`--resolve` is not exactly what we want here, as it computes a *new* solution. We don't want a new one, we want the one that is currently installed, including the alternative and optional dependencies that might be installed even if they are not strictly needed, as they might affect the current build.

**Comment by hannesm** [comment]
version information: when I do a `opam pin add functoria https://github.com/hannesm/functoria.git#rdeps`, `opam info -f version functoria` returns `2.2.0` (whereas I'd have expected a commit id), and `ocamlfind query -format %v functoria` returns `1.1.0-194-gcd90498` -- any hints how to get a more appropriate version number, anyone?

**Comment by hannesm** [comment]
moved to https://github.com/mirage/functoria/pull/151
