### ISSUE TITLE
MirageOS point release for Solo5 v0.3.0

### ISSUE THREAD

**Issue by mato** [mirage/mirage#907]
Now that the long-overdue Solo5 0.3.0 release is [out](https://github.com/Solo5/solo5/releases/tag/v0.3.0), and the MirageOS dependencies are publushed in OPAM, it'd be good to do a point release of MirageOS to accompany it.

The major new user-visible features for the Solo5 backends are:

- _ukvm_: Now runs natively on FreeBSD vmm and OpenBSD vmm.
- _ukvm_: ARM64 support.
- _muen_: New target, for the [Muen Separation Kernel](https://muen.sk/).
- _ukvm_: Improved and documented support for [debugging](https://github.com/Solo5/solo5/blob/master/docs/debugging.md) Solo5-based unikernels.

Questions:

1. Are mirage/mirage and major components in a state suitable for a release?
2. Should this be a 3.1.0 release? I think the amount of new features justify it.
3. How much PR should accompany this release? My preference is to release more or less "quietly", partly to not hold things up and partly due to planned [renaming](https://github.com/solo5/solo5/issues/172) on the Solo5 side which will result in, at least, the _ukvm_ target being renamed to _vt_, and a bunch user-visible terminology changing.
4. @mirage/core: Are folks around and available over the next week or so to help with this? I don't want to be doing all the work myself. If not, when's a good time?

**Comment by samoht** [comment]
I'm around and happy to help.

**Comment by yomimono** [comment]
>     Are mirage/mirage and major components in a state suitable for a release?

Yes, as far as I know.

>     Should this be a 3.1.0 release? I think the amount of new features justify it.

Yes, I think that's sensible.

>     How much PR should accompany this release? My preference is to release more or less "quietly", partly to not hold things up and partly due to planned renaming on the Solo5 side which will result in, at least, the ukvm target being renamed to vt, and a bunch user-visible terminology changing.

As long as we make sure to remember to brag about the increased support in a later larger release, this is fine by me.

>     @mirage/core: Are folks around and available over the next week or so to help with this? I don't want to be doing all the work myself. If not, when's a good time?

I'll be around this week and am happy to help.

**Comment by samoht** [comment]
+1 to what Mindy said :-)

Rregarding the release, a solution to have a "quiet but useful" release is to announce the new solo5 backends (muen, arm64) as experimental and seek feedback from users. This way we can still use these in the 4.0 announcement to brag about increased support.

**Comment by mato** [comment]
> Regarding the release, a solution to have a "quiet but useful" release is to announce the new solo5 backends (muen, arm64) as experimental and seek feedback from users. This way we can still use these in the 4.0 announcement to brag about increased support.

I agree, and in fact those targets are documented as experimental in the Solo5 documentation as well.

For arm64, I'm 90% certain that all of the stack (as defined by `static_website_tls`) does not build correctly, but am currently unable to test this fully as all the arm64 hardware I have is too slow to sanely build from source on it.

Since we all seem to be in agreement here, and I can see @hannesm has already started some work in #908 in preparation for a 3.1.0 release, what are the next steps?

**Comment by mato** [comment]
One thing which should be done is giving the docs at https://mirage.io/wiki/install a once-over from the Solo5 backend PoV (including derpeter's ARM64 HOWTO bits). I'll take a look at that over the course of tomorrow, since I'll be on mobile most of the day so not in a position to (reliably) push things or click green buttons.

**Comment by mato** [comment]
See https://github.com/mirage/mirage-www/pull/611 for a minimal set of documentation updates.

**Comment by mato** [comment]
All done here, thanks to @hannesm and @yomimono for help! 3.1.0 announcement is now out on the list.
