### ISSUE TITLE
How to stop Mirage_stack.listen?

### ISSUE THREAD

**Issue by ehirdoy** [mirage/mirage#915]
I'm using **listen_udpv4** and **listen** to capture some packet and I want to stop listening after some special packet is gotten. Currently there seems no way to go out from infinite-loop. I can decompose a socket version of **listen_updv4** into my code but then I would loose the direct version of it to be configured. I think that it's one of MirageOS advantages to configure backend flexibly.

What's the best way to stop listening if you start listening with listen_udpv4?

**Comment by hannesm** [comment]
The interface [`Mirage_stack.listen`](https://docs.mirage.io/mirage-stack/Mirage_stack/module-type-V4/index.html#val-listen) is implemented by the direct stack ([here](https://github.com/mirage/mirage-tcpip/blob/v3.4.2/src/stack-direct/tcpip_stack_direct.ml#L96)) by calling `Netif.listen` - documented [here](https://docs.mirage.io/mirage-net/Mirage_net/module-type-S/index.html#val-listen).

This says that you can stop the function by calling `disconnect` on the "device layer" -- i.e. if you have access to the `Netif` (as in this example unikernel https://github.com/mirage/mirage-skeleton/tree/master/device-usage/ping6, the `N : NETWORK`), you can call `N.disconnect n`.  There is no function provided by `Mirage_stack` with the same functionality (there is a `disconnect`, but its implementation does nothing).

Unfortunately, the `direct stack` and `socket stack` differ in their semantics here - the `socket stack` does not use a network interface (and thus, `disconnect` won't do anything).  The `direct stack` works in the way described above.  In my opinion, the implementation of `disconnect` on the mirage-stack layer should be finished to tear down all listeners.  If you'd like to look into this, it should be a change to `disconnect` in mirage-tcpip (`src/stack-direct` and `src/stack-unix`).

**Comment by hannesm** [comment]
there's a workaround (stolen from @samoht):
```OCaml
let cancel, cancel_th = Lwt.task () in
    S.listen_tcpv4 s ~port (fun flow ->
        S.TCPV4.read flow >>= function
        | Ok `Eof -> Lwt.return_unit
        | Error e -> Lwt.return_unit
        | Ok (`Data b) ->
          Printf.printf  "read: %d bytes:\n%s" (Cstruct.len b) (Cstruct.to_string b);
          S.TCPV4.close flow >|= fun () ->
          Lwt.wakeup cancel_th ()
      );
    Lwt.pick [ S.listen s; cancel ] >|= fun () ->
    Printf.printf "BYE \n%!"
```

and I'm still in favour of extending our IP signature to include this functionality

**Comment by dinosaure** [comment]
I think we are now able to _unlisten_ a socket since `tcpip.6.4.0`: https://github.com/mirage/mirage-tcpip/issues/452
