### ISSUE TITLE
should mirage organisation releases be prefixed with v?

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#949]
use :+1: if you prefer `vX.Y`, and :-1: if you prefer `X.Y`

**Comment by djs55** [comment]
I have no preference.

**Comment by yomimono** [comment]
I also have no preference but am in favor of consistency.

**Comment by hannesm** [comment]
I'll close this issue, and at some soonish point document that the `v` prefix is what the mirage organisation usually uses on our webpage. thanks for the discussion.
