### ISSUE TITLE
mirage-kv 2.0.0

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#974]
as described in #973, major API breaking changes https://github.com/mirage/mirage-kv/pull/14 thanks to @samoht @linse

- [x] add upper bounds to users of mirage-kv (`<2.0.0`) https://github.com/ocaml/opam-repository/pull/13497
- [x] mirage-kv 2.0.0 release  https://github.com/ocaml/opam-repository/pull/13525
- [x] mirage-kv-mem 2.0.0 release https://github.com/ocaml/opam-repository/pull/13531
- [x] mirage-kv-unix 2.0.0 release https://github.com/ocaml/opam-repository/pull/13532
- [x] crunch release 3.0.0 ~~(PR https://github.com/mirage/ocaml-crunch/pull/47)~~ ~~(depends on mirage-kv-mem being available)~~ https://github.com/ocaml/opam-repository/pull/13549
- [x] dns release ~~1.1.2~~ (mirage-dns 3.1.2) ~~(PR https://github.com/mirage/ocaml-dns/pull/156)~~ https://github.com/ocaml/opam-repository/pull/13546
- [x] tls release ~~0.10.0~~ 0.10.1 ~~(PR https://github.com/mirleft/ocaml-tls/pull/392 includes https://github.com/mirleft/ocaml-tls/pull/384)~~ ~~https://github.com/ocaml/opam-repository/pull/13547~~ https://github.com/ocaml/opam-repository/pull/13553
- [x] mirage changes #975 
- [x] ~~fat?~~
- [x] mirage-fs 2.0.0 ~~(remove functor to provide KV_RO)~~ ~~https://github.com/mirage/mirage-fs/pull/23 adapt to new kv interface~~ https://github.com/ocaml/opam-repository/pull/13545
- [x] cohttp-mirage 2.1.0 ~~(PR https://github.com/mirage/ocaml-cohttp/pull/636) (depends on dns)~~ https://github.com/ocaml/opam-repository/pull/13560
- [x] mirage-skeleton changes https://github.com/mirage/mirage-skeleton/pull/267
- [ ] tar-mirage https://github.com/mirage/ocaml-tar/pull/65

**Comment by samoht** [comment]
Just to be 100% sure: you expressed issues on https://github.com/mirage/mirage-kv/pull/14 that I think are perfectly valid. Are we really sure we want to proceed with that new API ? It clearly improves a lot of things compared to what we had before but it also introduced complexity, as you pointed out rightly on that PR.

**Comment by hannesm** [comment]
@samoht in my opinion, the concerns can be addressed in future revisions. the main being that keys are now paths instead of strings, but `Mirage_kv.Key.v` easily converts from a plain string to a key :)

**Comment by samoht** [comment]
Works for me!

**Comment by hannesm** [comment]
the release versions of `tar-mirage` are constrained to `mirage-kv < 2.0.0`. the release thereof can be done separately (until then, generic_kv_ro won't work with archive).
