### ISSUE TITLE
Support EXT2/3/4 filesystems along with FAT

### ISSUE THREAD

**Issue by XVilka** [mirage/mirage#989]
While FAT is omnipresent in the Windows world, EXT filesystem is much less restricted, did not covered by patents (hello exFAT!), and can be read/written by almost any UNIX operating system.
So it makes an obvious choice to support it along with FAT16/32.

**Comment by samoht** [comment]
Feel free to start an implementation of EXT in OCaml :-) I think that would be a fun project!
