### ISSUE TITLE
Solo5: Multiple devices support, spt target

### ISSUE THREAD

**Issue by mato** [mirage/mirage#992]
This issue tracks the work being done to update MirageOS to the new Solo5 APIs with support for multiple devices and application manifest (Solo5/solo5#372). Additionally, these changes also enable and add support for the spt (seccomp) target to Mirage.

Current work in progress is available as an OPAM remote, at `git+https://github.com/Solo5/opam-solo5.git`, which includes the following changes:

- ~~solo5-bindings-*: Point to Solo5 `master`.~~ Now in OPAM as 0.6.2.
- mirage#993 ([branch](/mato/mirage/tree/solo5-manifest)): Add support for spt target, generate application manifest at configure time using information from config.ml and link into unikernel at build time.
- ~~mirage/mirage-solo5#46 ([branch](/mato/mirage-solo5/tree/solo5-manifest)): Update C stubs to new multiple-device APIs.~~ Now in OPAM as 0.6.0.
- ~~mirage/mirage-block-solo5#18 ([branch](/mato/mirage-block-solo5/tree/solo5-manifest)): Update to new multiple-device APIs.~~ Now in OPAM as 0.6.0.
- ~~mirage/mirage-net-solo5#32 ([branch](/mato/mirage-net-solo5/tree/solo5-manifest)): Update to new multiple-device APIs.~~ Now in OPAM as 0.6.0.

@mirage/core: Please review these changes and test the remote.

At least the following remains to be addressed:

1. ~~The Lwt main loop (in mirage-solo5:lib/main.ml) has not been updated to take multiple devices into account and wake up only those threads that have work ready. The current implementation works "by accident" even with multiple networks, but results in spurious wakeups. mirage-net-solo5 will also need to be updated to match any changes here.~~ Done, changes pushed to mirage#993 and mirage/mirage-net-solo5#32.
2. The meaning of `block_of_file X` is unclear for Solo5; I have modified the mirage tool to just pass `X` through verbatim as the Solo5 block device name, however this precludes having a single config.ml that would be portable to all targets without changes.
3. Should we also introduce a a `default_block`, similar to `default_network`, for the "single block device" case?
4. The code in `generate_manifest` in the mirage tool should check that device names are unique and alphanumeric (as per the Solo5 manifest [documentation](https://github.com/Solo5/solo5/issues/372).
5. ~~Decide on version numbers for the Mirage/Solo5 packages to be released. Am thinking of skipping some in favour of keeping these all in sync, so that would mean `0.6.0` for all of them (and probably also for the Solo5 packages).~~ Solo5 will be 0.6.x, mirage-solo5 will match this version number.

**Comment by hannesm** [comment]
@mato imho it is easier to read and comment code if a PR exists for it, would you mind to open (possibly `[WIP]`) PRs with your mirage-* changes?

**Comment by mato** [comment]
@hannesm Done. I've just opened straightforward PRs from my current branches, have not attempted to do anything to make CI pass due to the various inter-dependencies involved. I've updated the description with the WIP PRs.

**Comment by cfcs** [comment]
regarding block devices and `block_of_file` there's this open discussion: https://github.com/mirage/mirage/issues/890
  - perhaps also relevant: https://github.com/mirage/mirage/issues/791

**Comment by mato** [comment]
Update: I have resolved the first point by adding an `OS.Main.wait_for_work_on_handle h` and using a `Map` from `Int64` (`solo5_handle_t`) to `Lwt_condition`. Changes pushed to the relevant PRs, please take a look. Thanks to @hannesm for input and help with debugging.

**Comment by hannesm** [comment]
merged into master, released as 3.6.0. thanks!
