### ISSUE TITLE
MirageOS-xen goes unikraft^WPVH

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#998]
Dear @mirage/core, thanks to @yomimono here are various branches you'll need to pin to get a mirage-xen backed by unikraft (based on 0.3.1) instead of the patched minios (and on the way get rid of mirage-platform etc, and use ocaml-freestanding instead). This will (as earlier) result in a PV image, there's some work to get PVH into unikraft (in some branch somewhere):

- xenplat from https://github.com/yomimono/unikraft.git#xen-on-freestanding-on-0.3.1
- ocaml-freestanding from https://github.com/yomimono/ocaml-freestanding.git#xen-on-freestanding
- io-page (+io-page-xen) from https://github.com/yomimono/io-page.git#xen-on-freestanding
- mirage-bootvar-xen from https://github.com/yomimono/mirage-bootvar-xen.git#xen-on-freestanding
- mirage-xen from https://github.com/yomimono/mirage-xen.git#xen-on-freestanding-pv-only
- ocb-stubblr from https://github.com/yomimono/ocb-stubblr.git#xen-on-freestanding

if you (esp. @avsm and @djs55 who asked for it) use these and compile a mirage-skeleton hello example, you'll see unikraft booting up, but failing to print hello world 4 times, since something is a bit funny with timers (or, according to my memory and printf debugging, the xs.read in bootvar-xen never returns). iirc, unikraft comes with some special `free` for the pages you allocate from it (in `io-page`), which is not yet called (but should be); there are various TODO in Mindy's commits. happy hacking! :)

**Comment by avsm** [comment]
Many thanks for this hard work @yomimono! At a first read through the diffs, it looks like you've done most of the heavy lifting to get us to a refreshed Xen backend.  I'll look in more detail next week when I'm back from travels and have my local Xen machine to try building and booting this.

I'm most excited about not having to work on our crufty old MiniOS fork from a thousand years ago ;-)

**Comment by djs55** [comment]
Thanks for the pins. I've hit a problem with is probably newbie error on my part with `ocaml-freestanding`:
```
#=== ERROR while installing ocaml-freestanding.0.4.6 ==========================#
# context     2.0.4 | linux/x86_64 | ocaml-system.4.05.0 | pinned(git+file:///home/djs/pins/ocaml-freestanding#xen-on-freestanding#81cc45d4)
# path        ~/.opam/default/.opam-switch/build/ocaml-freestanding.0.4.6
# command     ~/.opam/opam-init/hooks/sandbox.sh install make install PREFIX=/home/djs/.opam/default
# exit-code   2
# env-file    ~/.opam/log/ocaml-freestanding-10375-d474c2.env
# output-file ~/.opam/log/ocaml-freestanding-10375-d474c2.out
### output ###
# [...]
# + sed -f ../tools/cleanup-header caml/memory.h
# + sed -f ../tools/cleanup-header caml/misc.h
# + sed -f ../tools/cleanup-header caml/mlvalues.h
# + sed -f ../tools/cleanup-header caml/printexc.h
# + sed -f ../tools/cleanup-header caml/signals.h
# + sed -f ../tools/cleanup-header caml/compatibility.h
# + cp build/ocaml/otherlibs/bigarray/bigarray.h /home/djs/.opam/default/include/ocaml-freestanding/caml/bigarray.h
# + cp build/ocaml/asmrun/libasmrun.a /home/djs/.opam/default/lib/ocaml-freestanding/libasmrun.a
# + ln -s /home/djs/.opam/default/lib/ocaml-freestanding/libasmrun.a /home/djs/.opam/default/lib/ocaml/libasmrunfreestanding.a
# ln: failed to create symbolic link '/home/djs/.opam/default/lib/ocaml/libasmrunfreestanding.a': No such file or directory
# Makefile:122: recipe for target 'install' failed
# make: *** [install] Error 1
```
This is on a clean `opam init` with opam 2.0.4 on an Ubuntu LTS machine.

I guess the error is that `~/.opam/default/lib/ocaml` doesn't exist. Is this because I'm using a system compiler? I'll try again with a recompiled compiler.

**Comment by hannesm** [comment]
@djs55 yes, this sounds like a system compiler issue.. I think in freestanding-master this is already solved (there was some discussion about what to symlink etc. in respect to the mirage-dune port (I already forgot which symlinks and naming conventions should be active now)), so maybe rebasing the unikraft branch for ocaml-freestanding is worth a try

**Comment by mato** [comment]
@djs55 Yeah, `system` switches don't get much testing, it's possible something has (again) broken there. As @hannesm says, if possible update to latest `ocaml-freestanding` `master`, and try with OCaml 4.07+.

**Comment by djs55** [comment]
I've gotten a bit further now :) It does indeed work better with a non-system compiler. I created a simple `Dockerfile` using `ocaml/opam2:4.07`: https://github.com/djs55/mirage-unikraft-experiments/blob/master/Dockerfile . I had to make 2 tweaks to make it build:
1. I needed to expose `Os.{Xs,Start_info}` for `mirage-bootvar-xen` to compile: https://github.com/djs55/mirage-xen/commit/67a345746f34a311943e7602728fd55872f79960
2. I had to remove an upper-bound `< 0.6.0` on `mirage-bootvar-xen` in the generated opam file from the `mirage-skeleton/tutorial/hello` example: https://github.com/djs55/mirage-unikraft-experiments/blob/7194d8b0198ef0ccd9e571962688c1152f5d67ce/mirage-unikernel-hello-xen.opam#L8

I also rebased to `ocaml-freestanding` `master` as suggested.

After this the kernel seems to build but I've not been able to run it on Xen yet:
```
# xl create hello.xl
Parsing config from hello.xl
xc: error: panic: xc_dom_core.c:702: xc_dom_find_loader: no loader found: Invalid kernel
libxl: error: libxl_dom.c:671:libxl__build_dom: xc_dom_parse_image failed: No such file or directory
libxl: error: libxl_create.c:1217:domcreate_rebuild_done: Domain 14:cannot (re-)build domain: -3
libxl: error: libxl_domain.c:1003:libxl__destroy_domid: Domain 14:Non-existant domain
libxl: error: libxl_domain.c:962:domain_destroy_callback: Domain 14:Unable to destroy guest
libxl: error: libxl_domain.c:889:domain_destroy_cb: Domain 14:Destruction of domain failed
```
I've got an old Mirage kernel lying around which still works so I think there must be a problem with the build or final link?

The final link line looks like
```
mirage: [INFO] linking with ld -d -static -nostdlib _build/main.native.o
                              -L/home/opam/.opam/4.07/lib/io-page-xen
                              -lio_page_xen_stubs
                              -L/home/opam/.opam/4.07/lib/pkgconfig/../../lib/ocaml-freestanding
                              -L/home/opam/.opam/4.07/lib/pkgconfig/../../lib/xenplat
                              /home/opam/.opam/4.07/lib/pkgconfig/../../lib/mirage-xen/bindings/libmirage_xen_bindings_stubs.a
                              /home/opam/.opam/4.07/lib/pkgconfig/../../lib/mirage-xen/bindings-minios/libmirage_xen_bindings_minios_stubs.a
                              -lasmrun -lnolibc -lopenlibm -lxenplat
                              -T/home/opam/.opam/4.07/lib/pkgconfig/../../lib/xenplat/link64.lds
                              -o hello.xen
mirage: [INFO] Build succeeded: hello.xen
```
which mentions both `minios` and `xenplat` which might be wrong, but I'm not sure. There are full build logs here: https://cloud.docker.com/repository/registry-1.docker.io/djs55/mirage-unikraft-experiments/builds/885e4d22-a749-4482-9bfd-128453331fc6 (I hope that's visible) -- anyone have any suggestions?

**Comment by hannesm** [comment]
@djs55 your cloud.docker.com link wants me to login with a docker id

mirage-xen still has `mirage_xen_bindings_minios` (in `bindings/dune`), which should be fine (though I'm curious why there is a `mirage-xen/bindings-minios` subdirectory, it doesn't show up in the `mirage-xen` branch). I unfortunately don't have my xen machine with me to check.

**Comment by hannesm** [comment]
I'll close this issue for now. The last released unikraft still does not contain support for PVH, we'll wait for that. In the meantime, some work was done to update mini-os and use the PVH support in mini-os (see #1007 for details). The path forward is to get that out of the door, as another step use ocaml-freestanding instead of mirage-xen-*, and then eventually use unikraft (or a direct solo5 port) for PVH.
